(function(){
const BUILD='10.0.0-alpha.3';
let rows=[],meta={mode:'loading',marketDataVerified:false},history={snapshots:[],meta:{}};
const labels={NOW:'الآن',FORMING:'يتكوّن',WATCH:'مراقبة',AVOID:'تجنب',ABSTAIN_DATA:'بيانات ناقصة'};
const states={DORMANT:'خامل',ACCUMULATION:'تجميع',PRESSURE:'ضغط مبكر',IGNITION:'اشتعال',EXPANSION:'توسع',FAILURE_RISK:'خطر فشل'};
const money=v=>Number.isFinite(+v)?`$${(+v).toFixed(+v<1?3:2)}`:'—',pct=v=>Number.isFinite(+v)?`${+v>=0?'+':''}${(+v).toFixed(1)}%`:'—';
function ageText(ts){if(!ts)return'غير متوفر';const ms=Date.parse(ts);if(!Number.isFinite(ms))return'غير متوفر';const m=Math.max(0,(Date.now()-ms)/60000);return m<60?`${m.toFixed(0)} د`:`${(m/60).toFixed(1)} س`}
function card(z){if(!z.probabilities||!z.targets?.length)return'';const t=z.targets[1];return`<article class="stock-card" data-t="${z.ticker}"><div class="row"><span class="ticker">${z.ticker}</span><b class="${z.changePct>=0?'pos':'neg'}">${pct(z.changePct)}</b></div><div class="row muted"><span>${states[z.state]||z.state}</span><span>${money(z.price)}</span></div><div class="target">P(+10%) ${(z.probabilities.pUp10*100).toFixed(0)}% · T2 ${money(t.price)} · ${(t.probability*100).toFixed(0)}%</div><div class="muted">قابلية التنفيذ ${(z.tradeability*100).toFixed(0)}% · جودة ${(z.evidence.quality*100).toFixed(0)}%</div></article>`}
function historyHtml(){if(!history.snapshots.length)return`<section class="panel"><div class="row"><div><b>الجلسات السابقة</b><div class="muted">السجل التاريخي غير متاح حاليًا. لا يتم إنشاء تاريخ اصطناعي.</div></div><button id="reloadHistory" class="badge">إعادة المحاولة</button></div></section>`;const list=history.snapshots.slice(0,12).map(s=>`<article class="history-row"><div><b>${s.timestamp?new Date(s.timestamp).toLocaleString('ar-SA'):'وقت غير معروف'}</b><small>${s.bucket} · ${s.count} سهم · ${s.source}</small></div><div class="history-movers">${s.top.length?s.top.map(x=>`<span>${x.ticker} ${pct(x.change)}</span>`).join(''):'لا توجد movers قابلة للقراءة'}</div><div class="history-integrity">${s.reconciliation}${s.trainingEligible?' · مؤهل تدريب':' · ملاحظة فقط'}</div></article>`).join('');return`<section class="panel history-panel"><div class="row"><div><b>الجلسات السابقة</b><div class="muted">${history.meta.sessionCount||0} جلسة · ${history.meta.snapshotCount||history.snapshots.length} لقطة محفوظة · آخر سجل ${ageText(history.meta.latest)}</div></div><button id="reloadHistory" class="badge">تحديث التاريخ</button></div><div class="history-list">${list}</div></section>`}
function emptyState(){return`<section class="panel"><div class="empty-state"><h2>لا توجد بيانات سوق موثوقة حاليًا</h2><p>تم إيقاف الترتيب والأهداف والاحتمالات. TAG10 لا تستخدم بيانات تجريبية أو enrichment كبديل لسوق حي.</p><div class="muted">المصدر: ${meta.source||'غير متاح'} · الحالة: ${meta.reconciliation||'NO_DATA'}${meta.error?` · ${meta.error}`:''}</div><button id="reload" class="badge">إعادة المحاولة</button></div></section>`}
function render(){const verifiedFeed=meta.marketDataVerified===true&&rows.length>0,analyzed=verifiedFeed?rows.map(TAG10.analyze).filter(z=>z.probabilities&&z.targets?.length):[],lanes=['NOW','FORMING','WATCH','AVOID'],now=analyzed.filter(x=>x.decision==='NOW').length,forming=analyzed.filter(x=>x.decision==='FORMING').length,q=analyzed.length?analyzed.reduce((s,x)=>s+x.evidence.quality,0)/analyzed.length:0,mode=verifiedFeed?'بيانات سوق موثقة':meta.mode==='error'?'المصدر غير متاح':'جاري التحميل';document.querySelector('#app').innerHTML=`<div class="shell"><header class="top"><div class="brand"><small>TAG10 · ${BUILD}</small><h1>محرك الفرص المبكرة</h1></div><div class="status"><span class="badge build">BUILD ${BUILD}</span><span class="badge">${mode}</span><span class="badge">${meta.source||'—'}</span><span class="badge">${meta.reconciliation||'UNKNOWN'}</span><span class="badge">Fail-Closed</span></div></header><section class="grid"><div class="metric"><small>الكون المرصود</small><strong>${verifiedFeed?rows.length:0}</strong></div><div class="metric"><small>فرص الآن</small><strong>${now}</strong></div><div class="metric"><small>تحت التكوين</small><strong>${forming}</strong></div><div class="metric"><small>متوسط جودة الأدلة</small><strong>${verifiedFeed?(q*100).toFixed(0)+'%':'—'}</strong></div></section><section class="panel"><div class="row"><div><b>حالة المصدر</b><div class="muted">آخر تحديث: ${ageText(meta.updatedAt)} · الجلسة: ${meta.bucket||meta.session||'—'} · مصادر مستقلة: ${meta.independentSourceCount||0}</div></div><button id="reloadTop" class="badge">تحديث الآن</button></div></section>${verifiedFeed?`<section class="columns">${lanes.map(l=>`<section class="panel lane"><h3>${labels[l]}</h3><div>${analyzed.filter(x=>x.decision===l).map(card).join('')||'<p class="muted">لا توجد حالات</p>'}</div></section>`).join('')}</section>`:emptyState()}${historyHtml()}</div>`;document.querySelectorAll('.stock-card[data-t]').forEach(el=>el.onclick=()=>openDetail(analyzed.find(x=>x.ticker===el.dataset.t));document.querySelector('#reloadTop')?.addEventListener('click',loadLive);document.querySelector('#reload')?.addEventListener('click',loadLive);document.querySelector('#reloadHistory')?.addEventListener('click',loadHistory)}
function openDetail(z){if(!z?.probabilities||!z.targets?.length)return;const d=document.querySelector('#drawer'),p=z.probabilities;d.innerHTML=`<button class="close">إغلاق ×</button><p class="muted">${labels[z.decision]||z.decision} · ${states[z.state]||z.state}</p><h2>${z.ticker} ${money(z.price)}</h2><div class="prob"><div><small>P(+10%)</small><strong>${(p.pUp10*100).toFixed(0)}%</strong></div><div><small>P(+20%)</small><strong>${(p.pUp20*100).toFixed(0)}%</strong></div><div><small>P(+40%)</small><strong>${(p.pUp40*100).toFixed(0)}%</strong></div><div><small>P(Fail)</small><strong>${(p.pFail*100).toFixed(0)}%</strong></div></div><h3>المسارات المستهدفة</h3><div class="drawer-grid">${z.targets.map(t=>`<div class="evidence"><b>${t.name} ${money(t.price)}</b><br><span>${pct(t.upsidePct)} · احتمال ${(t.probability*100).toFixed(0)}%</span><br><small>ETA ${t.etaHours<6?t.etaHours.toFixed(1)+' س':'1–'+Math.ceil(t.etaHours/6)+' جلسة'}</small></div>`).join('')}</div><h3>مصدر البيانات</h3><div class="evidence">${z.source} · ${z.sourceTimestamp}<br>تكامل البيانات: ${z.dataIntegrityState||'UNKNOWN'}</div>`;d.classList.add('open');d.querySelector('.close').onclick=()=>d.classList.remove('open')}
async function loadLive(){rows=[];meta={mode:'loading',marketDataVerified:false};render();try{const out=await TAG10Data.load();rows=Array.isArray(out.rows)?out.rows:[];meta={...out.meta,mode:out.meta?.marketDataVerified?'connected':'error'};if(!meta.marketDataVerified)rows=[]}catch(e){rows=[];meta={mode:'error',marketDataVerified:false,reconciliation:'NO_MARKET_DATA',independentSourceCount:0,source:'NONE',updatedAt:null,error:e.message}}render()}
async function loadHistory(){try{history=await TAG10Data.loadHistory()}catch(e){history={snapshots:[],meta:{error:e.message}}}render()}
Promise.allSettled([loadLive(),loadHistory()]);setInterval(loadLive,5*60*1000);
})();