(function(){
const demo=[
{ticker:'ALFA',price:.82,changePct:6.2,volume:6400000,avgVolume:900000,float:7200000,spreadPct:.8,catalystAgeHours:3,orderFlowImbalance:.38,bookDepthImbalance:.24,persistenceSlope:.42,gainRetention:.88,sympathyScore:72,dilutionRisk:18,haltHazard:12},
{ticker:'BETA',price:1.44,changePct:15.8,volume:9100000,avgVolume:1600000,float:11200000,spreadPct:1.1,catalystAgeHours:10,orderFlowImbalance:.25,bookDepthImbalance:.12,persistenceSlope:.31,gainRetention:.8,sympathyScore:54,dilutionRisk:24,haltHazard:20},
{ticker:'GAMA',price:.34,changePct:74,volume:88000000,avgVolume:2100000,float:5100000,spreadPct:2.8,catalystAgeHours:5,orderFlowImbalance:-.08,bookDepthImbalance:-.18,persistenceSlope:-.35,gainRetention:.48,sympathyScore:49,dilutionRisk:58,haltHazard:72}];
let rows=[],meta={mode:'loading'};
const labels={NOW:'الآن',FORMING:'يتكوّن',WATCH:'مراقبة',AVOID:'تجنب',ABSTAIN_DATA:'بيانات ناقصة'};
const states={DORMANT:'خامل',ACCUMULATION:'تجميع',PRESSURE:'ضغط مبكر',IGNITION:'اشتعال',EXPANSION:'توسع',FAILURE_RISK:'خطر فشل'};
const money=v=>`$${(+v).toFixed(+v<1?3:2)}`; const pct=v=>`${v>=0?'+':''}${(+v).toFixed(1)}%`;
function ageText(ts){if(!ts)return 'وقت غير معروف';const ms=Date.parse(ts);if(!Number.isFinite(ms))return 'وقت غير معروف';const m=Math.max(0,(Date.now()-ms)/60000);return m<60?`${m.toFixed(0)} د`:`${(m/60).toFixed(1)} س`;}
function card(z){const t=z.targets[1];return `<article class="stock-card" data-t="${z.ticker}"><div class="row"><span class="ticker">${z.ticker}</span><b class="${z.changePct>=0?'pos':'neg'}">${pct(z.changePct)}</b></div><div class="row muted"><span>${states[z.state]}</span><span>${money(z.price)}</span></div><div class="target">P(+10%) ${(z.probabilities.pUp10*100).toFixed(0)}% · T2 ${money(t.price)} · ${(t.probability*100).toFixed(0)}%</div><div class="muted">قابلية التنفيذ ${(z.tradeability*100).toFixed(0)}% · جودة ${(z.evidence.quality*100).toFixed(0)}%</div></article>`}
function render(){const analyzed=rows.map(TAG10.analyze);const lanes=['NOW','FORMING','WATCH','AVOID'];const now=analyzed.filter(x=>x.decision==='NOW').length,forming=analyzed.filter(x=>x.decision==='FORMING').length,abstain=analyzed.filter(x=>x.decision==='ABSTAIN_DATA').length,q=analyzed.length?analyzed.reduce((s,x)=>s+x.evidence.quality,0)/analyzed.length:0;const mode=meta.mode==='connected'?'بيانات متصلة':meta.mode==='demo'?'بيانات تجريبية':'جاري التحميل';const integrity=meta.reconciliation||'UNKNOWN';document.querySelector('#app').innerHTML=`<div class="shell"><header class="top"><div class="brand"><small>TAG10 · Probabilistic State Intelligence</small><h1>محرك الفرص المبكرة</h1></div><div class="status"><span class="badge">${mode}</span><span class="badge">${integrity}</span><span class="badge">الفلتر الشرعي متوقف</span><span class="badge">ABSTAIN للبيانات فقط</span></div></header><section class="grid"><div class="metric"><small>الكون المرصود</small><strong>${rows.length}</strong></div><div class="metric"><small>فرص الآن</small><strong>${now}</strong></div><div class="metric"><small>تحت التكوين</small><strong>${forming}</strong></div><div class="metric"><small>جودة البيانات</small><strong>${(q*100).toFixed(0)}%</strong></div></section><section class="panel"><div class="row"><div><b>حالة المصدر</b><div class="muted">آخر تحديث: ${ageText(meta.updatedAt)} · الجلسة: ${meta.bucket||meta.session||'—'} · مصادر مستقلة: ${meta.independentSourceCount||0}</div></div><button id="reload" class="badge">تحديث الآن</button></div></section><section id="lanes" class="columns">${lanes.map(l=>`<section class="panel lane"><h3>${labels[l]}</h3><div>${analyzed.filter(x=>x.decision===l).map(card).join('')||'<p class="muted">لا توجد حالات</p>'}</div></section>`).join('')}</section><section class="panel"><b>بيانات غير كافية</b><div class="muted">${abstain} سهم لم يجتز حد جودة البيانات فقط. حالة الشرعية لا تؤثر على الترتيب أو الظهور.</div></section></div>`;document.querySelectorAll('.stock-card').forEach(el=>el.onclick=()=>openDetail(analyzed.find(x=>x.ticker===el.dataset.t)));document.querySelector('#reload').onclick=loadConnected;}
function openDetail(z){const d=document.querySelector('#drawer'),p=z.probabilities;d.innerHTML=`<button class="close">إغلاق ×</button><p class="muted">${labels[z.decision]||z.decision} · ${states[z.state]}</p><h2>${z.ticker} ${money(z.price)}</h2><div class="prob"><div><small>P(+10%)</small><strong>${(p.pUp10*100).toFixed(0)}%</strong></div><div><small>P(+20%)</small><strong>${(p.pUp20*100).toFixed(0)}%</strong></div><div><small>P(+40%)</small><strong>${(p.pUp40*100).toFixed(0)}%</strong></div><div><small>P(Fail)</small><strong>${(p.pFail*100).toFixed(0)}%</strong></div></div><h3>المسارات المستهدفة</h3><div class="drawer-grid">${z.targets.map(t=>`<div class="evidence"><b>${t.name} ${money(t.price)}</b><br><span>${pct(t.upsidePct)} · احتمال ${(t.probability*100).toFixed(0)}%</span><br><small>ETA ${t.etaHours<6?t.etaHours.toFixed(1)+' س':'1–'+Math.ceil(t.etaHours/6)+' جلسة'}</small></div>`).join('')}</div><h3>الأدلة والمخاطر</h3><div class="drawer-grid"><div class="evidence">RVOL ${z.evidence.rvol.toFixed(1)}×<br>Float turnover ${z.evidence.turnover.toFixed(2)}×<br>Dollar volume $${Math.round(z.evidence.dollarVol).toLocaleString()}</div><div class="evidence">Microstructure ${z.evidence.micro===null?'غير متوفر':(z.evidence.micro*100).toFixed(0)+'%'}<br>Persistence ${(z.evidence.persistence*100).toFixed(0)}%<br>Freshness ${(z.evidence.fresh*100).toFixed(0)}%</div><div class="evidence">Execution risk ${(z.evidence.executionRisk*100).toFixed(0)}%<br>Dilution ${(z.evidence.dilution*100).toFixed(0)}%<br>Halt ${(z.evidence.halt*100).toFixed(0)}%</div><div class="evidence">Tradeability ${(z.tradeability*100).toFixed(0)}%<br>Evidence strength ${(z.evidenceStrength*100).toFixed(0)}%<br>Invalidation ${money(z.invalidation)}</div></div><h3>التتبّع الزمني</h3><div class="evidence">أول رصد: ${z.firstObservedTimestampET||'غير متوفر'}<br>أول إشارة قابلة للتنفيذ: ${z.firstActionableSignalTimestampET||'غير متوفر'}<br>تكامل البيانات: ${z.dataIntegrityState||'UNKNOWN'}</div>`;d.classList.add('open');d.querySelector('.close').onclick=()=>d.classList.remove('open');}
async function loadConnected(){meta={mode:'loading'};render();try{const out=await TAG10Data.load();rows=out.rows;meta={...out.meta,mode:'connected'};}catch(e){rows=demo;meta={mode:'demo',reconciliation:'OFFLINE_FALLBACK',updatedAt:new Date().toISOString(),error:e.message};}render();}
loadConnected();setInterval(loadConnected,5*60*1000);
})();