(function(){
const N=v=>{if(typeof v==='number')return v;const s=String(v??'').replace(/[$,%]/g,'').trim();const m=s.match(/^(-?[\d.]+)\s*([KMBT])?$/i);if(!m)return Number(s)||0;const p={K:1e3,M:1e6,B:1e9,T:1e12};return Number(m[1])*(p[(m[2]||'').toUpperCase()]||1)};
function pick(o,names){for(const k of Object.keys(o||{})){const z=k.toLowerCase().replace(/[^a-z0-9]/g,'');if(names.includes(z))return o[k]}return null}
function normalizeFinviz(o){return {ticker:String(pick(o,['ticker','symbol'])||'').toUpperCase(),price:N(pick(o,['price'])),changePct:N(pick(o,['change','changepct','perfday'])),volume:N(pick(o,['volume'])),avgVolume:N(pick(o,['avgvolume','averagevolume','avgvol'])),float:N(pick(o,['float','sharesfloat'])),pmChange:N(pick(o,['premarketchange','premktchange','pmchange'])),ahChange:N(pick(o,['afterhourschange','postmarketchange','ahchange'])),ahVolume:N(pick(o,['afterhoursvolume','postmarketvolume','ahvolume'])),spreadPct:N(pick(o,['spreadpct','spread'])),catalystAgeHours:999,firstObservedTimestampET:o._firstObservedTimestampET||null,firstActionableSignalTimestampET:o._firstActionableSignalTimestampET||null,persistenceSlope:Number.isFinite(+o._persistenceSlopePctPts)?Math.max(-1,Math.min(1,+o._persistenceSlopePctPts/25)):undefined,gainRetention:Number.isFinite(+o._gainRetentionPct)?Math.max(0,Math.min(1,+o._gainRetentionPct/100)):undefined,dataIntegrityState:o._dataIntegrityState||'UNKNOWN'} }
function normalizeEnrichment(o){const p=o.price||{},news=Array.isArray(o.news)?o.news:[];let age=999;if(news[0]?.published){const d=Date.parse(news[0].published);if(Number.isFinite(d))age=Math.max(0,(Date.now()-d)/36e5)}return {ticker:String(o.ticker||'').toUpperCase(),price:N(p.last),changePct:N(p.changePct),volume:N(p.volume),avgVolume:0,float:0,pmChange:0,ahChange:0,ahVolume:0,spreadPct:0,catalystAgeHours:age,newsCount:news.length,catalystTitle:news[0]?.title||null,source:p.source||'Yahoo Finance chart',dataIntegrityState:'ENRICHMENT_FALLBACK'} }
async function getJson(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status+' '+url);return r.json()}
async function load(){
 const finvizUrls=['../tag/data/finviz.json','https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/finviz.json'];
 for(const u of finvizUrls){try{const p=await getJson(u);const raw=Array.isArray(p.data)?p.data:Array.isArray(p.rows)?p.rows:[];const rows=raw.map(normalizeFinviz).filter(x=>x.ticker&&x.price>0);if(rows.length)return {rows,meta:{updatedAt:p.updatedAt||p.snapshotTimestampUTC||null,session:p.session||null,bucket:p.sessionBucket||null,reconciliation:p.finalSnapshotReconciliation||'UNKNOWN',independentSourceCount:p.independentSourceCount||0,source:'FINVIZ_SNAPSHOT'}}}catch(e){}}
 const e=await getJson('https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/enrichment.json');const raw=e.rows&&typeof e.rows==='object'?Object.values(e.rows):[];const rows=raw.map(normalizeEnrichment).filter(x=>x.ticker&&x.price>0);if(!rows.length)throw new Error('No usable market rows');return {rows,meta:{updatedAt:e.updatedAt||null,session:'extended/latest',bucket:'enrichment',reconciliation:'PARTIAL_DATA',independentSourceCount:Array.isArray(e.sources)?e.sources.length:0,source:'ENRICHMENT_FALLBACK'}}
window.TAG10Data={load};
})();