(function(){
const N=v=>{if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;const s=String(v).replace(/[$,%]/g,'').replace(/,/g,'').trim();const m=s.match(/^(-?[\d.]+)\s*([KMBT])?$/i);if(!m)return null;const p={K:1e3,M:1e6,B:1e9,T:1e12};const n=Number(m[1])*(p[(m[2]||'').toUpperCase()]||1);return Number.isFinite(n)?n:null};
function pick(o,names){for(const k of Object.keys(o||{})){const z=k.toLowerCase().replace(/[^a-z0-9]/g,'');if(names.includes(z))return o[k]}return null}
function normalizeFinviz(o,meta){const ticker=String(pick(o,['ticker','symbol'])||'').toUpperCase();const price=N(pick(o,['price']));const volume=N(pick(o,['volume']));const avgVolume=N(pick(o,['avgvolume','averagevolume','avgvol']));const flt=N(pick(o,['float','sharesfloat']));return {ticker,price,changePct:N(pick(o,['change','changepct','perfday'])),volume,avgVolume,float:flt,pmChange:N(pick(o,['premarketchange','premktchange','pmchange'])),ahChange:N(pick(o,['afterhourschange','postmarketchange','ahchange'])),ahVolume:N(pick(o,['afterhoursvolume','postmarketvolume','ahvolume'])),spreadPct:N(pick(o,['spreadpct','spread'])),catalystAgeHours:null,firstObservedTimestampET:o._firstObservedTimestampET||null,firstActionableSignalTimestampET:o._firstActionableSignalTimestampET||null,persistenceSlope:Number.isFinite(+o._persistenceSlopePctPts)?Math.max(-1,Math.min(1,+o._persistenceSlopePctPts/25)):null,gainRetention:Number.isFinite(+o._gainRetentionPct)?Math.max(0,Math.min(1,+o._gainRetentionPct/100)):null,dataIntegrityState:o._dataIntegrityState||meta.dataIntegrityState||'UNKNOWN',marketDataVerified:Boolean(ticker&&price>0&&volume>0&&meta.updatedAt),source:'FINVIZ_SNAPSHOT',sourceTimestamp:meta.updatedAt||null,independentSourceCount:Number(meta.independentSourceCount||0)} }
async function getJson(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status+' '+url);return r.json()}
function metaFrom(p){return {updatedAt:p.updatedAt||p.snapshotTimestampUTC||null,session:p.session||null,bucket:p.sessionBucket||null,reconciliation:p.finalSnapshotReconciliation||'UNKNOWN',independentSourceCount:Number(p.independentSourceCount||0),dataIntegrityState:p.dataIntegrityState||'UNKNOWN',source:'FINVIZ_SNAPSHOT'}}
async function load(){
 const finvizUrls=['../tag/data/finviz.json','https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/finviz.json'];let lastError=null;
 for(const u of finvizUrls){try{const p=await getJson(u);const raw=Array.isArray(p.data)?p.data:Array.isArray(p.rows)?p.rows:[];const meta=metaFrom(p);if(!meta.updatedAt)throw new Error('MARKET_TIMESTAMP_MISSING');const rows=raw.map(o=>normalizeFinviz(o,meta)).filter(x=>x.marketDataVerified);if(!rows.length)throw new Error('NO_VERIFIED_MARKET_ROWS');return {rows,meta:{...meta,marketDataVerified:true}}}catch(e){lastError=e}}
 // Enrichment remains context-only. It must never become a ranking feed because avg volume/float/session semantics can be incomplete.
 try{const e=await getJson('https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/enrichment.json');return {rows:[],meta:{updatedAt:e.updatedAt||null,session:null,bucket:null,reconciliation:'NO_MARKET_SNAPSHOT',independentSourceCount:0,source:'ENRICHMENT_CONTEXT_ONLY',marketDataVerified:false,error:lastError?.message||'PRIMARY_MARKET_SOURCE_UNAVAILABLE'}}}catch(e){throw new Error(lastError?.message||e.message||'PRIMARY_MARKET_SOURCE_UNAVAILABLE')}
}
window.TAG10Data={load};
})();