(function(){
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(+v)?+v:0));
const num=v=>Number.isFinite(+v)?+v:0;
const sig=x=>1/(1+Math.exp(-x));
function normEvidence(x){
 const price=Number.isFinite(+x.price)&&+x.price>0?+x.price:null, vol=Number.isFinite(+x.volume)&&+x.volume>0?+x.volume:null, avg=Number.isFinite(+x.avgVolume)&&+x.avgVolume>0?+x.avgVolume:null, flt=Number.isFinite(+x.float)&&+x.float>0?+x.float:null, spread=Number.isFinite(+x.spreadPct)&&+x.spreadPct>=0?+x.spreadPct:null;
 const rvol=vol&&avg?vol/avg:null, turnover=vol&&flt?vol/flt:null, dollarVol=price&&vol?price*vol:null;
 const fresh=Number.isFinite(+x.catalystAgeHours)?(+x.catalystAgeHours<=6?1:+x.catalystAgeHours<=24?.85:+x.catalystAgeHours<=72?.55:+x.catalystAgeHours<=168?.25:0):null;
 const ofi=Number.isFinite(+x.orderFlowImbalance)?clamp((+x.orderFlowImbalance+1)/2):null;
 const depth=Number.isFinite(+x.bookDepthImbalance)?clamp((+x.bookDepthImbalance+1)/2):null;
 const micro=ofi!==null||depth!==null?((ofi??.5)*.6+(depth??.5)*.4):null;
 const volAccel=rvol!==null?clamp(Math.log2(1+rvol)/5):null, floatVelocity=turnover!==null?clamp(turnover/3):null, spreadQ=spread!==null?clamp(1-spread/5):null, liquidity=dollarVol!==null?clamp((Math.log10(1+dollarVol)-5)/3):null;
 const persistence=Number.isFinite(+x.persistenceSlope)?clamp((+x.persistenceSlope+1)/2):null;
 const retention=Number.isFinite(+x.gainRetention)?clamp(+x.gainRetention):null;
 const sector=Number.isFinite(+x.sympathyScore)?clamp(+x.sympathyScore/100):null;
 const dilution=Number.isFinite(+x.dilutionRisk)?clamp(+x.dilutionRisk/100):null, halt=Number.isFinite(+x.haltHazard)?clamp(+x.haltHazard/100):null, exhaustion=Number.isFinite(+(x.exhaustionMemory??x.formerRunnerMemory))?clamp(+(x.exhaustionMemory??x.formerRunnerMemory)/100):null;
 const executionRisk=spread!==null&&dollarVol!==null?clamp((spread/5)*.45+(dollarVol<5e5?.35:dollarVol<2e6?.18:0)+(flt&&flt<1e6?.15:0)):null;
 const coreValid=Boolean(x.marketDataVerified&&price&&vol&&avg&&x.sourceTimestamp&&x.source);
 const data=[price!==null,vol!==null,avg!==null,flt!==null,fresh!==null,micro!==null,dilution!==null,halt!==null];
 const quality=data.filter(Boolean).length/data.length;
 return {price,vol,avg,flt,spread,rvol,turnover,dollarVol,fresh,ofi,depth,micro,volAccel,floatVelocity,spreadQ,liquidity,persistence,retention,sector,dilution,halt,exhaustion,executionRisk,quality,coreValid};
}
function stateMachine(x,e){if(!e.coreValid)return 'DORMANT';const ch=num(x.changePct),ah=Number.isFinite(+x.ahChange)?+x.ahChange:0,m=e.micro??.5;const pressure=(e.volAccel??0)*.24+(e.floatVelocity??0)*.16+m*.22+(e.persistence??.5)*.15+(e.fresh??.5)*.13+(e.sector??.5)*.10;if((e.exhaustion??0)>.72||ch>95||(ah<-20&&ch>40))return 'FAILURE_RISK';if(ch>45||(e.halt??0)>.65)return 'EXPANSION';if(ch>12&&pressure>.55)return 'IGNITION';if(pressure>.62&&ch<15)return 'PRESSURE';if((e.volAccel??0)>.38&&(e.floatVelocity??0)>.18&&Math.abs(ch)<12)return 'ACCUMULATION';return 'DORMANT'}
function paths(x,e,state){if(!e.coreValid)return null;const m=e.micro??.5;const positive=(e.volAccel??0)*.18+(e.floatVelocity??0)*.12+m*.19+(e.persistence??.5)*.15+(e.retention??.5)*.10+(e.fresh??.5)*.10+(e.sector??.5)*.08+(e.spreadQ??.5)*.08;const negative=(e.dilution??.5)*.22+(e.halt??.5)*.17+(e.executionRisk??.5)*.18+(e.exhaustion??.5)*.20+(1-e.quality)*.23;const stateBoost={DORMANT:-.35,ACCUMULATION:-.05,PRESSURE:.28,IGNITION:.42,EXPANSION:.05,FAILURE_RISK:-.65}[state]||0;const base=positive-negative+stateBoost;return {pUp10:sig((base-.22)*4.2),pUp20:sig((base-.43)*4.4),pUp40:sig((base-.72)*4.8),pFail:sig((negative-positive*.55+(state==='FAILURE_RISK'?.45:0))*4.1),pHalt:clamp((e.halt??0)*.65+Math.max(0,num(x.changePct)-35)/140)}}
function targetSet(e,p){if(!e.coreValid||!p)return[];const v=Math.max(.5,((e.volAccel??0)*.9+(e.micro??.5)*.8+(e.persistence??.5)*.65+(e.retention??.5)*.55-(e.executionRisk??.5)*.6-(e.exhaustion??.5)*.55));const ups=[8+18*p.pUp10,15+35*p.pUp20,25+75*p.pUp40],probs=[p.pUp10,p.pUp20,p.pUp40];return ups.map((u,i)=>({name:`T${i+1}`,price:e.price*(1+u/100),upsidePct:u,probability:probs[i],etaHours:u/(v*8)}))}
function analyze(x){const e=normEvidence(x),state=stateMachine(x,e);if(!e.coreValid){return {...x,evidence:e,state:'DORMANT',probabilities:null,targets:[],tradeability:null,evidenceStrength:null,decision:'ABSTAIN_DATA',invalidation:null,dataBlockReason:'MARKET_SOURCE_NOT_VERIFIED'}}const probabilities=paths(x,e,state),targets=targetSet(e,probabilities);const tradeability=clamp(1-((e.executionRisk??.5)*.45+(e.dilution??.5)*.22+(e.halt??.5)*.18+(e.exhaustion??.5)*.15));const evidenceStrength=clamp((e.volAccel??0)*.18+(e.floatVelocity??0)*.12+(e.micro??.5)*.18+(e.persistence??.5)*.13+(e.fresh??.5)*.12+(e.sector??.5)*.08+(e.spreadQ??.5)*.08+(e.liquidity??0)*.05+e.quality*.06);let decision='WATCH';if(e.quality<.5)decision='ABSTAIN_DATA';else if(state==='FAILURE_RISK'||probabilities.pFail>.58)decision='AVOID';else if(['PRESSURE','IGNITION'].includes(state)&&probabilities.pUp10>.62&&tradeability>.55)decision='NOW';else if(['ACCUMULATION','PRESSURE'].includes(state)&&probabilities.pUp10>.50)decision='FORMING';const invalidation=e.price*(1-Math.min(.14,.045+(e.executionRisk??.5)*.05+(e.exhaustion??.5)*.03));return {...x,evidence:e,state,probabilities,targets,tradeability,evidenceStrength,decision,invalidation}}
const api={analyze};if(typeof window!=='undefined')window.TAG10=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();