'use strict';
(function(){
 const URL='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/extended-hours.json';
 let last=null,busy=false;
 const N=v=>{const n=parseFloat(v);return Number.isFinite(n)?n:null};
 const F=v=>v==null?'—':(v>=0?'+':'')+v.toFixed(1)+'%';
 const M=v=>v==null?'—':'$'+v.toFixed(v<1?3:2);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function etSession(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false,weekday:'short'}).formatToParts(new Date()),g=k=>p.find(x=>x.type===k)?.value,m=(+g('hour'))*60+(+g('minute'));if(['Sat','Sun'].includes(g('weekday')))return'CLOSED';if(m>=240&&m<570)return'pre-market';if(m>=960&&m<1200)return'after-hours';return'other'}
 function fresh(r){if(!r?.timestampUTC)return false;return (Date.now()-new Date(r.timestampUTC).getTime())/60000<=15}
 function classify(r){const ch=N(r.sessionChangePct),first=N(r.firstAHChangePct),v15=N(r.priceVelocity15mPct),v5=N(r.priceVelocity5mPct),give=N(r.peakGivebackPts)||0;if(ch==null||!fresh(r)||ch<3)return null;if(v15!=null&&v15<=-3)return null;if(first!=null&&first>=10)return null;if(give>=7)return null;if(ch>=35)return null;if(ch>=20&&!(v15!=null&&v15>=2.5))return null;let score=58;score+=Math.min(18,ch*1.35);if(first!=null&&first<5)score+=8;else if(first!=null&&first<10)score+=5;if(v15!=null)score+=Math.max(-6,Math.min(12,v15*1.8));if(v5!=null)score+=Math.max(-3,Math.min(6,v5));if(r.persistencePass===true)score+=7;if(give>0)score-=Math.min(10,give*1.5);score=Math.max(0,Math.min(96,Math.round(score)));if(score<68)return null;return{r,score,stage:ch>=20?'MOMENTUM':ch>=8?'EARLY':'BUILDING'}}
 function picks(j){return Object.values(j?.rows||{}).map(classify).filter(Boolean).sort((a,b)=>b.score-a.score).slice(0,8)}
 function html(z,i){const r=z.r,t=String(r.ticker||'').toUpperCase(),ch=N(r.sessionChangePct),first=N(r.firstAHChangePct),v15=N(r.priceVelocity15mPct),v5=N(r.priceVelocity5mPct);return '<article class="opp '+(i===0?'best ':'')+(i>=4?'extra ':'')+'ah-v22" data-ticker="'+esc(t)+'"><div class="rank">'+(i===0?'أفضل فرصة ممتدة':'#'+(i+1))+' · '+z.stage+'</div><div class="ticker">'+esc(t)+'</div><div class="move">'+F(ch)+'</div><div class="score">TAGX AH '+z.score+'/100</div><div class="meta">'+M(N(r.last))+' · أول رصد AH '+F(first)+'<br>سرعة 15د '+F(v15)+' · سرعة 5د '+F(v5)+'</div><div class="why">لماذا الآن: رُصد مبكرًا بعد الإغلاق وما زال داخل نافذة قابلة للتنفيذ'+(r.persistencePass===true?' · استمرار متعدد النوافذ':'')+'</div><div style="margin-top:7px;font-size:11px;font-weight:900;color:#1d4ed8">AH ACTIONABLE V22</div></article>'}
 function paint(){if(etSession()!=='after-hours'&&etSession()!=='pre-market')return;const host=document.querySelector('#topOpps');if(!host||!last)return;const age=(Date.now()-new Date(last.updatedAtUTC||0).getTime())/60000;const ps=picks(last);if(age>15){host.innerHTML='<div class="empty"><b>بيانات الجلسة الممتدة قديمة ('+Math.round(age)+'د).</b><br>تم إيقاف التوصيات حتى تصل لقطة حديثة.</div>';return}if(!ps.length){host.innerHTML='<div class="empty"><b>لا توجد فرصة After-Hours قابلة للتنفيذ الآن.</b><br>توجد تحركات، لكن الحالات الحالية إما متأخرة أو فقدت الزخم أو لم تُرصد مبكرًا.</div>';return}host.innerHTML=ps.map(html).join('');host.querySelectorAll('[data-ticker]').forEach(el=>el.onclick=()=>{try{window.openStock?.(el.dataset.ticker)}catch{}});const hero=host.closest('.hero');const h2=hero?.querySelector('h2');const p=hero?.querySelector('p');if(h2)h2.textContent=etSession()==='after-hours'?'فرص TAGX القابلة للتنفيذ بعد الإغلاق':'فرص TAGX القابلة للتنفيذ قبل الافتتاح';if(p)p.innerHTML='تعرض فقط الحالات التي رُصدت مبكرًا في الجلسة الممتدة وما زالت محافظة على الزخم. <b>Late/Exhaustion لا تدخل هنا.</b>'}
 async function load(){if(busy)return;busy=true;try{const r=await fetch(URL+'?v='+Date.now(),{cache:'no-store'});if(r.ok){last=await r.json();paint()}}catch(e){console.error('AH V22',e)}finally{busy=false}}
 const obs=new MutationObserver(()=>{if(last&&document.querySelector('#topOpps')&&!document.querySelector('#topOpps .ah-v22'))setTimeout(paint,50)});const start=()=>{const h=document.querySelector('#topOpps');if(h)obs.observe(h,{childList:true});load();setInterval(load,15000);setInterval(paint,4000)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();window.TAGXAHV22={load,paint,picks};
})();