'use strict';
(function(){
  const RELEASE='TAGX 1.2';
  const style=document.createElement('style');
  style.textContent='.proj12{margin:10px 0;padding:10px;border-radius:12px;background:#eff6ff;color:#1e3a8a}.proj12 small{display:block;color:#64748b}.proj12 b{font-size:17px}.date12{color:#64748b;font-size:12px;margin-top:5px}';
  document.head.appendChild(style);
  document.title='TAGX 1.2 — Early Market Intelligence';
  const ey=document.querySelector('.ey'); if(ey) ey.textContent='TAGX 1.2 · EARLY MARKET INTELLIGENCE';
  const footer=document.querySelector('footer'); if(footer) footer.innerHTML='<b>TAGX 1.2</b> — جميع التواريخ بالتقويم الميلادي. توقعات السعر ونسبة الارتفاع تقديرات نموذجية وليست ضمانًا للعائد.';
  function gd(v,time=true){if(!v)return'—';let d;if(/^\d{4}-\d{2}-\d{2}$/.test(String(v)))d=new Date(String(v)+'T12:00:00Z');else d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);const o={timeZone:'America/New_York',day:'2-digit',month:'2-digit',year:'numeric'};if(time)Object.assign(o,{hour:'2-digit',minute:'2-digit',hour12:false});return new Intl.DateTimeFormat('en-GB',o).format(d)+(time?' ET':'')}
  function proj(x){const sc=trace(x).score,rv=N(x['Rel Volume'])||0,fl=N(x.Float),st=stage(x),p=N(x.Price);let hi=sc>=90?55:sc>=85?48:sc>=80?40:sc>=75?32:25;if(rv>=4)hi+=8;else if(rv>=2)hi+=4;if(fl!=null&&fl<=5)hi+=10;else if(fl!=null&&fl<=20)hi+=5;if(st==='IGNITION')hi+=4;if(st==='DISCOVERY')hi-=3;hi=Math.max(18,Math.min(85,Math.round(hi)));const lo=Math.max(10,Math.round(hi*.55));return{lo,hi,maxPrice:p!=null?p*(1+hi/100):null}}
  window.TAGXProjectionV12={release:RELEASE,projection:proj,gregorianDate:gd};
  const originalRender=render;
  render=function(){originalRender();const ts=latestMeta?.snapshotTimestampUTC||latestMeta?.snapshotTimestampET||latestMeta?.updatedAt;const st=document.querySelector('#status');if(st&&ts&&!st.querySelector('[data-gregorian]'))st.insertAdjacentHTML('beforeend','<span class="chip" data-gregorian="1">'+gd(ts)+'</span>');document.querySelectorAll('#topOpps .opp[data-ticker]').forEach(card=>{const x=rowMap.get(card.dataset.ticker);if(!x)return;const p=proj(x),fi=firstInfo(x);const old=card.querySelector('.proj12');if(old)old.remove();const div=document.createElement('div');div.className='proj12';div.innerHTML='<small>نطاق الارتفاع المتوقع من السعر الحالي</small><b>+'+p.lo+'% إلى +'+p.hi+'%</b><br><small>السعر الأقصى التقديري</small><b>'+M(p.maxPrice)+'</b><div class="date12">أول رصد: '+gd(fi.ts)+'</div>';const why=card.querySelector('.why');card.insertBefore(div,why||null)});const table=document.querySelector('#radarRows')?.closest('table');if(table){const hr=table.querySelector('thead tr');if(hr&&!hr.querySelector('[data-maxprice]'))hr.insertAdjacentHTML('beforeend','<th data-maxprice="1">أقصى سعر تقديري</th>');table.querySelectorAll('tbody tr[data-ticker]').forEach(tr=>{const x=rowMap.get(tr.dataset.ticker);if(!x)return;const p=proj(x);let td=tr.querySelector('[data-maxprice]');if(!td){td=document.createElement('td');td.dataset.maxprice='1';tr.appendChild(td)}td.innerHTML='<b>'+M(p.maxPrice)+'</b><br><span class="sub">+'+p.hi+'%</span>'})}}
  openStock=function(ticker){const x=rowMap.get(ticker);if(!x)return;const e=enrichment?.rows?.[ticker]||{},fi=firstInfo(x),t=trace(x),p=proj(x),news=Array.isArray(e.news)?e.news:[],filings=Array.isArray(e.filings)?e.filings:[],price=e.price||{};const risk=Math.min(100,(stage(x)==='IGNITION'?35:20)+(sharia(x)==='UNVERIFIED'?25:0)+(news.length?0:15)+(N(x.Float)!=null&&N(x.Float)<5?15:5));document.querySelector('#drawerBody').innerHTML='<div class="detail-title"><div><div class="ticker">'+esc(ticker)+'</div><div class="sub">'+esc(x.Company||'')+' · '+esc(x.Sector||'—')+' / '+esc(x.Industry||'—')+'</div></div><div><div class="score">TAGX '+t.score+'</div><div class="move">'+F(N(x.Change))+'</div></div></div><div class="detail-grid">'+box('السعر الحالي',M(N(x.Price)))+box('الارتفاع المتوقع','+'+p.lo+'% إلى +'+p.hi+'%')+box('السعر الأقصى التقديري',M(p.maxPrice))+box('أول رصد',F(fi.ch)+' · '+gd(fi.ts))+box('المرحلة',stage(x))+box('RVOL',(N(x['Rel Volume'])||0).toFixed(2))+box('الحجم',C(N(x.Volume)))+box('Float',(N(x.Float)?.toFixed(2)??'—')+'M')+box('Short Float',x['Short Float']||'—')+box('Market Cap',x['Market Cap']||'—')+box('الشرعية',sharia(x))+box('Yahoo',price.last?M(N(price.last))+' · '+F(N(price.changePct)):'—')+box('وقت سعر Yahoo',gd(price.timestampUTC))+box('مصادر الرصد',(x._sources||[]).join(' + ')||'—')+'</div><div class="section"><h4>لماذا اختاره TAGX؟</h4><div class="riskline"><b>عوامل الرفع:</b> '+esc(t.up.join(' · ')||'لا يوجد')+'<br><b>عوامل الخفض:</b> '+esc(t.down.join(' · ')||'لا يوجد')+'<br><b>إبطال المتابعة:</b> انتقال Late/Exhaustion، انهيار RVOL/التسارع، أو ظهور تعارض بيانات/تمويل جوهري.</div></div><div class="section"><h4>التوقع والمخاطر</h4><div class="riskline"><b>نطاق الارتفاع:</b> +'+p.lo+'% إلى +'+p.hi+'% من السعر الحالي · <b>السعر الأقصى التقديري:</b> '+M(p.maxPrice)+'<br>Risk Score: <b>'+risk+'/100</b>. التقدير ديناميكي وليس ضمانًا أو هدفًا سعريًا ملزمًا.</div></div><div class="section"><h4>الأخبار الحديثة ('+news.length+')</h4><div class="news">'+(news.length?news.slice(0,10).map(n=>'<a href="'+esc(n.url)+'" target="_blank" rel="noopener"><b>'+esc(n.title)+'</b><small>'+esc(n.source||'')+' · '+gd(n.published)+'</small></a>').join(''):'<div class="note">لا توجد أخبار موثقة في التحديث الحالي.</div>')+'</div></div><div class="section"><h4>SEC / Filings ('+filings.length+')</h4><div class="news">'+(filings.length?filings.slice(0,8).map(f=>'<div class="riskline">'+esc(f.form||f.type||'Filing')+' · '+gd(f.filedAt||f.filingDate||f.timestamp)+'</div>').join(''):'<div class="sub">لا توجد filings موثقة.</div>')+'</div></div>';document.querySelector('#backdrop').classList.add('open');document.querySelector('#drawer').classList.add('open')}
  const originalPerf=renderPerf;
  renderPerf=function(){originalPerf();document.querySelectorAll('#earlyRows tr td:nth-child(4),#historyWrap tbody tr td:first-child').forEach(td=>{const s=td.textContent.trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))td.textContent=gd(s,false)})}
  browserNotify=async function(z){const x=z.x,p=proj(x),body='TAGX '+z.s+'/100 · '+F(N(x.Change))+' · متوقع +'+p.lo+'% إلى +'+p.hi+'% · أقصى '+M(p.maxPrice);try{if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.ready;await reg.showNotification('TAGX · '+x.Ticker+' فرصة مبكرة',{body,tag:'tagx-'+x.Ticker,renotify:false,data:{ticker:x.Ticker}})}else if(Notification.permission==='granted')new Notification('TAGX · '+x.Ticker,{body})}catch{}toast('🔔 رصد جديد: '+x.Ticker+' · TAGX '+z.s)}
  try{render()}catch(e){console.error('TAGX 1.2 enhancement',e)}
})();