'use strict';
(function(){
 const RELEASE='TAGX 1.6 · NATIVE EXTENDED-HOURS V21';
 const URL='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/extended-hours.json';
 const ext={rows:{},updatedAtUTC:null,session:null,dataConfidence:'UNAVAILABLE',candidateCount:0,universeCount:0,discoveryCount:0,scanPolicy:null};
 const style=document.createElement('style');style.textContent='.session16{margin-top:8px;padding:8px 10px;border-radius:10px;font-size:12px;font-weight:800;background:#f1f5f9;color:#334155}.session16.good{background:#ecfdf5;color:#047857}.session16.warn{background:#fff7ed;color:#b45309}.session16.bad{background:#fef2f2;color:#b91c1c}.ext16-stale{opacity:.55}.ah-native-badge{display:inline-block;margin-top:6px;padding:4px 7px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:11px;font-weight:900}.ah-opportunity{border:2px solid #93c5fd}.ah-opportunity.hot{border-color:#16a34a}.ah-session-move{font-size:20px;font-weight:950;color:#15803d}.ah-velocity{font-size:12px;color:#475569;font-weight:800;margin-top:4px}';document.head.appendChild(style);
 function et(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false,weekday:'short'}).formatToParts(new Date());const g=k=>p.find(x=>x.type===k)?.value;return{day:g('weekday'),m:(+g('hour'))*60+(+g('minute'))}}
 function session(){const z=et();if(['Sat','Sun'].includes(z.day))return'CLOSED';if(z.m>=240&&z.m<570)return'pre-market';if(z.m>=570&&z.m<960)return'regular';if(z.m>=960&&z.m<1200)return'after-hours';return'CLOSED'}
 function age(){if(!ext.updatedAtUTC)return null;const n=(Date.now()-new Date(ext.updatedAtUTC).getTime())/60000;return Number.isFinite(n)?n:null}
 function live(x){const r=ext.rows?.[x.Ticker]||null;return r?{row:r,last:N(r.last),sessionCh:N(r.sessionChangePct),dayCh:N(r.changeVsPreviousClosePct),vel5:N(r.priceVelocity5mPct),vel15:N(r.priceVelocity15mPct),vel30:N(r.priceVelocity30mPct),volAccel:N(r.volumeAcceleration15m),extVol:N(r.extendedVolume),ts:r.timestampUTC}:null}
 function state(x){const s=session();if(s==='regular'||s==='CLOSED')return{s,active:false,blocked:false,penalty:0,boost:0,why:'',confidence:'RTH'};const a=age(),l=live(x),fresh=a!=null&&a<=12&&ext.session===s&&l&&l.ts&&((Date.now()-new Date(l.ts).getTime())/60000)<=15;if(!fresh)return{s,active:true,blocked:true,penalty:70,boost:0,why:'بيانات الساعات الممتدة مفقودة/قديمة — Fail Closed',confidence:'UNVERIFIED',l};let penalty=0,boost=0,blocked=false,why=[];const ch=l.sessionCh,vel=l.vel15;if(ch!=null&&ch<=-12){blocked=true;penalty=65;why.push('انهيار الجلسة الممتدة ≥12%')}else if(ch!=null&&ch<=-8){penalty+=38;why.push('ضعف ممتد ≥8%')}else if(ch!=null&&ch<=-5){penalty+=22;why.push('ضعف ممتد ≥5%')}if(vel!=null&&vel<=-5){blocked=true;penalty=Math.max(penalty,55);why.push('سرعة 15د هابطة ≥5%')}else if(vel!=null&&vel<=-3){penalty+=18;why.push('تدهور سرعة 15د')}if(ch!=null&&ch>=3&&vel!=null&&vel>0){boost+=6;why.push('استمرار ممتد إيجابي')}if(vel!=null&&vel>=3){boost+=5;why.push('تسارع سعري 15د')}if(l.volAccel!=null&&l.volAccel>=1.5&&vel!=null&&vel>0){boost+=4;why.push('تسارع حجم ممتد')}boost=Math.min(12,boost);return{s,active:true,blocked,penalty,boost,why:why.join(' · ')||'بيانات ممتدة مستقرة',confidence:ext.dataConfidence||'LIMITED',l}}
 function extView(x,q){return q.active&&q.l?{...x,Price:q.l.last,Change:(q.l.dayCh==null?x.Change:q.l.dayCh),Volume:q.l.extVol||x.Volume}:x}
 function mergeNativeCandidates(){if(ext.session!=='after-hours'&&ext.session!=='pre-market')return;const active=new Set();for(const [rawTicker,r] of Object.entries(ext.rows||{})){const ticker=String(rawTicker||r?.ticker||'').toUpperCase();if(!ticker)continue;const sch=N(r.sessionChangePct),vel=N(r.priceVelocity15mPct);const qualified=r.discoveryQualified===true||(sch!=null&&sch>=2)||(vel!=null&&vel>=3);if(!qualified)continue;active.add(ticker);const first=N(r.firstAHChangePct);const day=N(r.changeVsPreviousClosePct);const px=N(r.last);const ev=N(r.extendedVolume)||0;let x=rowMap.get(ticker);if(!x){x={Ticker:ticker,Company:ext.session==='after-hours'?'After-Hours native discovery':'Pre-Market native discovery',Price:px,Change:day==null?sch:day,Volume:ev,'Rel Volume':0,Float:null,_sources:['extended-native'],_ahNativeSynthetic:true,_firstFastObservedChange:first==null?sch:first,_firstFastObservedTimestampUTC:r.firstAHSeenUTC||r.timestampUTC};rows.push(x);rowMap.set(ticker,x)}else if(x._ahNativeSynthetic){x.Price=px;x.Change=day==null?sch:day;x.Volume=ev;x._firstFastObservedChange=first==null?x._firstFastObservedChange:first;x._firstFastObservedTimestampUTC=r.firstAHSeenUTC||x._firstFastObservedTimestampUTC||r.timestampUTC}}rows=rows.filter(x=>!x._ahNativeSynthetic||active.has(x.Ticker));rowMap=new Map(rows.map(x=>[x.Ticker,x]))}
 function ahScore(r){const ch=N(r.sessionChangePct)||0,v15=N(r.priceVelocity15mPct)||0,v5=N(r.priceVelocity5mPct)||0,v30=N(r.priceVelocity30mPct)||0;let score=54+Math.min(28,ch*2.1)+Math.max(-10,Math.min(10,v15*1.45))+Math.max(-4,Math.min(4,v5*.7))+Math.max(-3,Math.min(3,v30*.25));if(ch>=8&&v15>=0)score+=5;if(ch>=5&&v15>=2)score+=4;if(v15<=-3)score-=12;if(ch>=25&&v15<=1)score-=8;return Math.max(0,Math.min(98,Math.round(score)))}
 function ahStage(r){const ch=N(r.sessionChangePct)||0,v15=N(r.priceVelocity15mPct)||0;if(ch>=35)return'EXHAUSTION';if(ch>=20&&v15<1)return'LATE';if(ch>=12&&v15>=0)return'BREAKOUT';if(ch>=7&&v15>=-1)return'EARLY';if(ch>=3&&v15>=0)return'BUILDING';if(v15>=3)return'ACCEL';return'WATCH'}
 function ahQualified(r){const ch=N(r.sessionChangePct),v15=N(r.priceVelocity15mPct),ts=r.timestampUTC;if(ch==null||ch<3||!ts)return false;const fresh=(Date.now()-new Date(ts).getTime())/60000<=15;if(!fresh)return false;if(v15!=null&&v15<=-5)return false;if(ch>=35&&!(v15!=null&&v15>=3))return false;return ahScore(r)>=65}
 function renderAHNativeOpportunities(){const s=session();if(s!=='after-hours'&&s!=='pre-market')return;const host=document.querySelector('#topOpps');if(!host)return;const picks=Object.values(ext.rows||{}).filter(ahQualified).sort((a,b)=>ahScore(b)-ahScore(a)).slice(0,10);if(!picks.length)return;host.innerHTML=picks.map((r,i)=>{const t=String(r.ticker||'').toUpperCase(),ch=N(r.sessionChangePct),v15=N(r.priceVelocity15mPct),px=N(r.last),sc=ahScore(r),st=ahStage(r),hot=sc>=75;return '<div class="opp ah-opportunity '+(hot?'hot ':'')+(i===0?'best':'extra')+'" data-ticker="'+esc(t)+'" onclick="openStock(\''+esc(t)+'\')"><div class="rank">'+(i===0?'أفضل فرصة ممتدة':'#'+(i+1))+' · '+esc(st)+'</div><div class="ticker">'+esc(t)+'</div><div class="ah-session-move">'+F(ch)+'</div><div class="score">TAGX '+sc+'</div><div class="meta">السعر '+M(px)+' · '+(s==='after-hours'?'After-Hours':'Pre-Market')+'</div><div class="ah-velocity">سرعة 15د '+F(v15)+' · سرعة 5د '+F(N(r.priceVelocity5mPct))+'</div><div class="why">اكتشاف مستقل في الجلسة الممتدة'+(v15!=null&&v15>0?' · استمرار لحظي إيجابي':'')+'</div><div class="ah-native-badge">EXTENDED NATIVE</div></div>'}).join('')}
 const baseTrace=trace;trace=function(x){const q=state(x),v=extView(x,q),t=baseTrace(v);let score=Math.max(0,Math.min(100,Math.round(t.score-q.penalty+q.boost)));if(q.active&&q.l){const ns=ahScore(q.l.row||{});if(x._ahNativeSynthetic||q.s==='after-hours'||q.s==='pre-market')score=Math.max(score,ns)}if(q.active&&q.confidence==='UNVERIFIED')score=Math.min(score,49);const up=[...(t.up||[])],down=[...(t.down||[])];if(x._ahNativeSynthetic)up.push('Extended-native universe');if(q.active&&q.l?.sessionCh!=null&&q.l.sessionCh>=2)up.push('Extended move '+F(q.l.sessionCh));if(q.boost)up.push('Native extended-hours +'+q.boost);if(q.penalty)down.push(q.why);if(q.blocked)down.push('Extended-Hours Gate: BLOCKED');return{...t,score,up,down,extended:q}}
 const baseStage=stage;stage=function(x){const q=state(x);if(q.blocked)return'EXHAUSTION';if(q.active&&q.l&&q.l.sessionCh!=null&&q.l.sessionCh>=2)return ahStage(q.l.row||{});return baseStage(extView(x,q))}
 const baseEligible=eligible;eligible=function(x){const q=state(x);if(q.active&&q.blocked)return false;if(q.active&&q.l&&ahQualified(q.l.row||{}))return true;return baseEligible(extView(x,q))}
 const baseReason=reason;reason=function(x){const q=state(x);if(q.active&&q.l){const lead=[];const r=q.l.row||{};if(x._ahNativeSynthetic)lead.push('اكتشاف مستقل في الجلسة الممتدة');if(r.firstAHChangePct!=null)lead.push('أول رصد '+F(N(r.firstAHChangePct)));if(q.l.sessionCh!=null&&q.l.sessionCh>=2)lead.push('الآن '+F(q.l.sessionCh));if(q.l.vel15!=null&&q.l.vel15>0)lead.push('سرعة15د '+F(q.l.vel15));const rest=baseReason(extView(x,q));return(lead.slice(0,4).join(' · ')+(lead.length&&rest?' · ':'')+rest)||'تحول ممتد تحت المراقبة'}return baseReason(x)}
 function decorate(){const s=session(),a=age();const status=document.querySelector('#status');if(status){let el=status.querySelector('[data-ext16]');if(!el){el=document.createElement('span');el.dataset.ext16='1';el.className='chip';status.appendChild(el)}const good=s==='regular'||s==='CLOSED'||(a!=null&&a<=12&&ext.session===s&&ext.dataConfidence!=='UNAVAILABLE');el.className='chip '+(good?'ok':'bad');const breadth=ext.candidateCount?(' · scan '+ext.candidateCount):'';const dc=ext.discoveryCount?(' · discoveries '+ext.discoveryCount):'';el.textContent=(s==='pre-market'?'قبل الافتتاح':s==='after-hours'?'بعد الإغلاق':s==='regular'?'الجلسة النظامية':'مغلق')+' · Extended '+(a==null?'غير متاح':Math.round(a)+'د')+breadth+dc}document.querySelectorAll('#topOpps .opp[data-ticker]').forEach(card=>{const x=rowMap.get(card.dataset.ticker);if(!x)return;const q=state(x),t=trace(x);if(q.active&&q.blocked){card.remove();return}if(x._ahNativeSynthetic&&!card.querySelector('.ah-native-badge')){const b=document.createElement('div');b.className='ah-native-badge';b.textContent='EXTENDED NATIVE';card.appendChild(b)}let d=card.querySelector('.session16');if(!d){d=document.createElement('div');d.className='session16';card.appendChild(d)}const c=q.boost?'good':q.penalty?'warn':'';d.className='session16 '+c;if(q.active&&q.l)d.textContent=(q.s==='pre-market'?'قبل الافتتاح':'بعد الإغلاق')+' · '+F(q.l.sessionCh)+' · سرعة15د '+F(q.l.vel15)+' · TAGX '+t.score;else d.textContent='الجلسة النظامية · Extended gate غير مطلوب'});document.querySelectorAll('#radarRows tr[data-ticker]').forEach(tr=>{const x=rowMap.get(tr.dataset.ticker);if(x&&state(x).blocked)tr.classList.add('ext16-stale')})}
 const baseRender=render;render=function(){baseRender();renderAHNativeOpportunities();decorate()}
 const baseOpen=openStock;openStock=function(ticker){baseOpen(ticker);const x=rowMap.get(ticker);if(!x)return;const q=state(x),body=document.querySelector('#drawerBody');if(!body)return;let sec=body.querySelector('[data-ext16-detail]');if(!sec){sec=document.createElement('div');sec.className='section';sec.dataset.ext16Detail='1';body.insertBefore(sec,body.querySelector('.section')||null)}const l=q.l,r=l?.row||{};sec.innerHTML='<h4>الساعات الممتدة</h4><div class="riskline"><b>الحالة:</b> '+esc(q.s)+' · <b>الثقة:</b> '+esc(q.confidence)+(x._ahNativeSynthetic?' · <b>Extended Native</b>':'')+'<br><b>السعر الممتد:</b> '+(l?M(l.last):'—')+' · <b>تغير الجلسة الممتدة:</b> '+(l?F(l.sessionCh):'—')+' · <b>من الإغلاق السابق:</b> '+(l?F(l.dayCh):'—')+'<br><b>سرعة 5/15/30 دقيقة:</b> '+(l?F(l.vel5):'—')+' / '+(l?F(l.vel15):'—')+' / '+(l?F(l.vel30):'—')+'<br><b>TAGX Extended Score:</b> '+(l?ahScore(r):'—')+' · <b>المرحلة الممتدة:</b> '+(l?ahStage(r):'—')+' · <b>قرار البوابة:</b> '+(q.blocked?'🔴 مستبعد':'🟢 صالح للرصد')+'<br><span class="sub">الجلسة الممتدة لها أهلية مستقلة ولا تعتمد على RVOL أو مرحلة الجلسة النظامية.</span></div>'}
 async function loadExt(){try{const r=await fetch(URL+'?v='+Date.now(),{cache:'no-store'});if(r.ok){const j=await r.json();ext.rows=j.rows||{};ext.updatedAtUTC=j.updatedAtUTC||null;ext.session=j.session||null;ext.dataConfidence=j.dataConfidence||'LIMITED';ext.candidateCount=j.candidateCount||0;ext.universeCount=j.universeCount||0;ext.discoveryCount=j.discoveryCount||0;ext.scanPolicy=j.scanPolicy||null;mergeNativeCandidates()}}catch(e){console.error('TAGX extended load',e)}try{render()}catch(e){console.error('TAGX extended render',e)}}
 window.TAGXExtendedHoursV16={release:RELEASE,state,session,ext,mergeNativeCandidates,ahScore,ahQualified,renderAHNativeOpportunities};document.title='TAGX 1.6 — Native Extended-Hours Intelligence';const ey=document.querySelector('.ey');if(ey)ey.textContent='TAGX 1.6 · NATIVE EXTENDED-HOURS INTELLIGENCE V21';loadExt();setInterval(loadExt,30000);
})();