'use strict';
(function(){
 const RELEASE='TAGX 1.6 · NATIVE EXTENDED-HOURS V20.1';
 const URL='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/extended-hours.json';
 const ext={rows:{},updatedAtUTC:null,session:null,dataConfidence:'UNAVAILABLE',candidateCount:0,universeCount:0,discoveryCount:0,scanPolicy:null};
 const style=document.createElement('style');style.textContent='.session16{margin-top:8px;padding:8px 10px;border-radius:10px;font-size:12px;font-weight:800;background:#f1f5f9;color:#334155}.session16.good{background:#ecfdf5;color:#047857}.session16.warn{background:#fff7ed;color:#b45309}.session16.bad{background:#fef2f2;color:#b91c1c}.ext16-stale{opacity:.55}.ah-native-badge{display:inline-block;margin-top:6px;padding:4px 7px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:11px;font-weight:900}';document.head.appendChild(style);
 function et(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false,weekday:'short'}).formatToParts(new Date());const g=k=>p.find(x=>x.type===k)?.value;return{day:g('weekday'),m:(+g('hour'))*60+(+g('minute'))}}
 function session(){const z=et();if(['Sat','Sun'].includes(z.day))return'CLOSED';if(z.m>=240&&z.m<570)return'pre-market';if(z.m>=570&&z.m<960)return'regular';if(z.m>=960&&z.m<1200)return'after-hours';return'CLOSED'}
 function age(){if(!ext.updatedAtUTC)return null;const n=(Date.now()-new Date(ext.updatedAtUTC).getTime())/60000;return Number.isFinite(n)?n:null}
 function live(x){const r=ext.rows?.[x.Ticker]||null;return r?{row:r,last:N(r.last),sessionCh:N(r.sessionChangePct),dayCh:N(r.changeVsPreviousClosePct),vel5:N(r.priceVelocity5mPct),vel15:N(r.priceVelocity15mPct),vel30:N(r.priceVelocity30mPct),volAccel:N(r.volumeAcceleration15m),extVol:N(r.extendedVolume),ts:r.timestampUTC}:null}
 function state(x){const s=session();if(s==='regular'||s==='CLOSED')return{s,active:false,blocked:false,penalty:0,boost:0,why:'',confidence:'RTH'};const a=age(),l=live(x),fresh=a!=null&&a<=12&&ext.session===s&&l&&l.ts&&((Date.now()-new Date(l.ts).getTime())/60000)<=15;if(!fresh)return{s,active:true,blocked:true,penalty:70,boost:0,why:'بيانات الساعات الممتدة مفقودة/قديمة — Fail Closed',confidence:'UNVERIFIED',l};let penalty=0,boost=0,blocked=false,why=[];const ch=l.sessionCh,vel=l.vel15;if(ch!=null&&ch<=-12){blocked=true;penalty=65;why.push('انهيار الجلسة الممتدة ≥12%')}else if(ch!=null&&ch<=-8){penalty+=38;why.push('ضعف ممتد ≥8%')}else if(ch!=null&&ch<=-5){penalty+=22;why.push('ضعف ممتد ≥5%')}if(vel!=null&&vel<=-5){blocked=true;penalty=Math.max(penalty,55);why.push('سرعة 15د هابطة ≥5%')}else if(vel!=null&&vel<=-3){penalty+=18;why.push('تدهور سرعة 15د')}if(ch!=null&&ch>=3&&vel!=null&&vel>0){boost+=6;why.push('استمرار ممتد إيجابي')}if(vel!=null&&vel>=3){boost+=5;why.push('تسارع سعري 15د')}if(l.volAccel!=null&&l.volAccel>=1.5&&vel!=null&&vel>0){boost+=4;why.push('تسارع حجم ممتد')}boost=Math.min(12,boost);return{s,active:true,blocked,penalty,boost,why:why.join(' · ')||'بيانات ممتدة مستقرة',confidence:ext.dataConfidence||'LIMITED',l}}
 function extView(x,q){return q.active&&q.l?{...x,Price:q.l.last,Change:(q.l.dayCh==null?x.Change:q.l.dayCh),Volume:q.l.extVol||x.Volume}:x}
 function mergeNativeCandidates(){
   if(ext.session!=='after-hours')return;
   const active=new Set();
   for(const [rawTicker,r] of Object.entries(ext.rows||{})){
     const ticker=String(rawTicker||r?.ticker||'').toUpperCase();if(!ticker)continue;
     const sch=N(r.sessionChangePct),native=N(r.nativeRankScore),qualified=r.discoveryQualified===true||(sch!=null&&Math.abs(sch)>=2)||(native!=null&&native>=55);
     if(!qualified)continue;active.add(ticker);
     const first=N(r.firstAHChangePct);const day=N(r.changeVsPreviousClosePct);const px=N(r.last);const ev=N(r.extendedVolume)||0;
     let x=rowMap.get(ticker);
     if(!x){
       x={Ticker:ticker,Company:'After-Hours native discovery',Price:px,Change:day==null?sch:day,Volume:ev,'Rel Volume':0,Float:null,_sources:['afterhours-native'],_ahNativeSynthetic:true,_firstFastObservedChange:first==null?sch:first,_firstFastObservedTimestampUTC:r.firstAHSeenUTC||r.timestampUTC};
       rows.push(x);rowMap.set(ticker,x);
     }else if(x._ahNativeSynthetic){
       x.Price=px;x.Change=day==null?sch:day;x.Volume=ev;x._firstFastObservedChange=first==null?x._firstFastObservedChange:first;x._firstFastObservedTimestampUTC=r.firstAHSeenUTC||x._firstFastObservedTimestampUTC||r.timestampUTC;
     }
   }
   rows=rows.filter(x=>!x._ahNativeSynthetic||active.has(x.Ticker));
   rowMap=new Map(rows.map(x=>[x.Ticker,x]));
 }
 const baseTrace=trace;trace=function(x){const q=state(x),v=extView(x,q),t=baseTrace(v);let score=Math.max(0,Math.min(100,Math.round(t.score-q.penalty+q.boost)));const native=N(q.l?.row?.nativeRankScore);if(x._ahNativeSynthetic&&native!=null)score=Math.max(score,Math.min(86,45+Math.round(native*.42)));if(q.active&&q.confidence==='UNVERIFIED')score=Math.min(score,49);const up=[...(t.up||[])],down=[...(t.down||[])];if(x._ahNativeSynthetic)up.push('AH-native universe');if(q.active&&q.l?.sessionCh!=null&&q.l.sessionCh>=2)up.push('AH move '+F(q.l.sessionCh));if(q.boost)up.push('Native extended-hours +'+q.boost);if(q.penalty)down.push(q.why);if(q.blocked)down.push('Extended-Hours Gate: BLOCKED');return{...t,score,up,down,extended:q}}
 const baseStage=stage;stage=function(x){const q=state(x);if(q.blocked)return'EXHAUSTION';return baseStage(extView(x,q))}
 const baseEligible=eligible;eligible=function(x){const q=state(x);if(q.active&&q.blocked)return false;return baseEligible(extView(x,q))}
 const baseReason=reason;reason=function(x){const q=state(x);if(q.active&&q.l){const lead=[];const r=q.l.row||{};if(x._ahNativeSynthetic)lead.push('اكتشاف مستقل بعد الإغلاق');if(r.firstAHChangePct!=null)lead.push('أول AH '+F(N(r.firstAHChangePct)));if(q.l.sessionCh!=null&&q.l.sessionCh>=2)lead.push('الآن '+F(q.l.sessionCh));if(q.l.vel15!=null&&q.l.vel15>0)lead.push('سرعة15د '+F(q.l.vel15));if(q.l.volAccel!=null&&q.l.volAccel>=1.5)lead.push('تسارع حجم '+q.l.volAccel.toFixed(2)+'x');const rest=baseReason(extView(x,q));return(lead.slice(0,4).join(' · ')+(lead.length&&rest?' · ':'')+rest)||'تحول ممتد تحت المراقبة'}return baseReason(x)}
 function decorate(){const s=session(),a=age();const status=document.querySelector('#status');if(status){let el=status.querySelector('[data-ext16]');if(!el){el=document.createElement('span');el.dataset.ext16='1';el.className='chip';status.appendChild(el)}const good=s==='regular'||s==='CLOSED'||(a!=null&&a<=12&&ext.session===s&&ext.dataConfidence!=='UNAVAILABLE');el.className='chip '+(good?'ok':'bad');const breadth=ext.candidateCount?(' · scan '+ext.candidateCount):'';const dc=ext.discoveryCount?(' · discoveries '+ext.discoveryCount):'';el.textContent=(s==='pre-market'?'قبل الافتتاح':s==='after-hours'?'بعد الإغلاق':s==='regular'?'الجلسة النظامية':'مغلق')+' · Extended '+(a==null?'غير متاح':Math.round(a)+'د')+breadth+dc}
 document.querySelectorAll('#topOpps .opp[data-ticker]').forEach(card=>{const x=rowMap.get(card.dataset.ticker);if(!x)return;const q=state(x),t=trace(x);if(q.active&&q.blocked){card.remove();return}if(x._ahNativeSynthetic&&!card.querySelector('.ah-native-badge')){const b=document.createElement('div');b.className='ah-native-badge';b.textContent='AH NATIVE';card.appendChild(b)}let d=card.querySelector('.session16');if(!d){d=document.createElement('div');d.className='session16';card.appendChild(d)}const c=q.boost?'good':q.penalty?'warn':'';d.className='session16 '+c;if(q.active&&q.l)d.textContent=(q.s==='pre-market'?'قبل الافتتاح':'بعد الإغلاق')+' · '+F(q.l.sessionCh)+' · سرعة15د '+F(q.l.vel15)+' · VolAccel '+(q.l.volAccel==null?'—':q.l.volAccel.toFixed(2)+'x')+' · TAGX '+t.score;else d.textContent='الجلسة النظامية · Extended gate غير مطلوب'});
 document.querySelectorAll('#radarRows tr[data-ticker]').forEach(tr=>{const x=rowMap.get(tr.dataset.ticker);if(x&&state(x).blocked)tr.classList.add('ext16-stale')})}
 const baseRender=render;render=function(){baseRender();decorate()}
 const baseOpen=openStock;openStock=function(ticker){baseOpen(ticker);const x=rowMap.get(ticker);if(!x)return;const q=state(x),body=document.querySelector('#drawerBody');if(!body)return;let sec=body.querySelector('[data-ext16-detail]');if(!sec){sec=document.createElement('div');sec.className='section';sec.dataset.ext16Detail='1';body.insertBefore(sec,body.querySelector('.section')||null)}const l=q.l,r=l?.row||{};sec.innerHTML='<h4>الساعات الممتدة</h4><div class="riskline"><b>الحالة:</b> '+esc(q.s)+' · <b>الثقة:</b> '+esc(q.confidence)+(x._ahNativeSynthetic?' · <b>AH Native</b>':'')+'<br><b>السعر الممتد:</b> '+(l?M(l.last):'—')+' · <b>تغير After-Hours:</b> '+(l?F(l.sessionCh):'—')+' · <b>من الإغلاق السابق:</b> '+(l?F(l.dayCh):'—')+'<br><b>أول رصد AH:</b> '+(r.firstAHChangePct!=null?F(N(r.firstAHChangePct)):'—')+' · <b>قمة AH:</b> '+(r.peakAHChangePct!=null?F(N(r.peakAHChangePct)):'—')+' · <b>Giveback:</b> '+(r.peakGivebackPts!=null?F(-N(r.peakGivebackPts)):'—')+'<br><b>سرعة 5/15/30 دقيقة:</b> '+(l?F(l.vel5):'—')+' / '+(l?F(l.vel15):'—')+' / '+(l?F(l.vel30):'—')+' · <b>تسارع الحجم:</b> '+(l&&l.volAccel!=null?l.volAccel.toFixed(2)+'x':'—')+'<br><b>حجم ممتد:</b> '+(l?C(l.extVol):'—')+' · <b>قرار البوابة:</b> '+(q.blocked?'🔴 مستبعد':'🟢 صالح للرصد')+'<br><span class="sub">After-Hours-native: يمكن إدخال سهم لم يكن ضمن movers النظاميين إذا بدأت حركته لأول مرة بعد 16:00 ET.</span></div>'}
 async function loadExt(){try{const r=await fetch(URL+'?v='+Date.now(),{cache:'no-store'});if(r.ok){const j=await r.json();ext.rows=j.rows||{};ext.updatedAtUTC=j.updatedAtUTC||null;ext.session=j.session||null;ext.dataConfidence=j.dataConfidence||'LIMITED';ext.candidateCount=j.candidateCount||0;ext.universeCount=j.universeCount||0;ext.discoveryCount=j.discoveryCount||0;ext.scanPolicy=j.scanPolicy||null;mergeNativeCandidates()}}catch{}try{render()}catch(e){console.error('TAGX extended render',e)}}
 window.TAGXExtendedHoursV16={release:RELEASE,state,session,ext,mergeNativeCandidates};document.title='TAGX 1.6 — Native Extended-Hours Intelligence';const ey=document.querySelector('.ey');if(ey)ey.textContent='TAGX 1.6 · NATIVE EXTENDED-HOURS INTELLIGENCE';loadExt();setInterval(loadExt,30000);
})();