'use strict';
(function(){
 const BASE='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/';
 const style=document.createElement('style');style.textContent='.pc19grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:15px 0}.pc19k{border:1px solid #e2e8f0;border-radius:15px;padding:14px}.pc19k small{display:block;color:#64748b}.pc19k b{font-size:25px}.pc19ah{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;margin-top:12px}.pc19card{border:1px solid #e2e8f0;border-radius:14px;padding:13px}.pc19up{color:#15803d;font-weight:900}.pc19dn{color:#b91c1c;font-weight:900}@media(max-width:700px){.pc19grid{grid-template-columns:1fr 1fr}}';document.head.appendChild(style);
 const nav=document.querySelector('.tabs'),main=document.querySelector('main');if(!nav||!main)return;
 const b=document.createElement('button');b.dataset.tab='postclose';b.textContent='بعد الجلسة';nav.appendChild(b);
 const sec=document.createElement('section');sec.id='postcloseView';sec.className='hide';sec.innerHTML='<h2>تقرير الجلسة والساعات الممتدة</h2><div class="sub">تقرير فوري بعد 16:00 ET من سجل TAGX الحالي. يبقى Provisional حتى المصالحة النهائية.</div><div id="pc19status" class="status"></div><div id="pc19kpis" class="pc19grid"></div><section class="panel"><h3>Top‑20: ماذا اكتشف TAGX؟</h3><div id="pc19table" class="tablewrap"></div></section><section class="panel"><h3>After‑Hours الآن</h3><div class="sub">السعر الممتد والتغير من إغلاق الجلسة النظامية. البيانات القديمة لا تعرض كحية.</div><div id="pc19ah" class="pc19ah"><div class="empty">جاري تحميل بيانات ما بعد الإغلاق…</div></div></section>';
 main.appendChild(sec);
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function n(v){v=Number(v);return Number.isFinite(v)?v:null}function f(v){return v==null?'—':(v>=0?'+':'')+v.toFixed(1)+'%'}
 async function j(name){try{const r=await fetch(BASE+name+'?v='+Date.now(),{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
 function age(x){const t=x?.updatedAtUTC||x?.updatedAt;return t?Math.round((Date.now()-new Date(t).getTime())/60000):9999}
 async function load(){const [a,e]=await Promise.all([j('tagx-actionability-v8-challenger.json'),j('extended-hours.json')]);const top=a?.currentTop20||[];const counts={e10:0,e20:0,late:0,miss:0,action:0};top.forEach(x=>{if(x.class==='PREDICTED_EARLY_LT10')counts.e10++;else if(x.class==='PREDICTED_EARLY_LT20')counts.e20++;else if(x.class==='DETECTED_LATE')counts.late++;else if(x.class==='MISSED')counts.miss++;if(x.actionableEarly)counts.action++});const den=top.length||20;document.querySelector('#pc19kpis').innerHTML=[['Early <10%',counts.e10+'/'+den],['Early <20%',(counts.e10+counts.e20)+'/'+den],['Detected Late',counts.late+'/'+den],['Missed',counts.miss+'/'+den],['Actionable',counts.action+'/'+den]].map(x=>'<div class="pc19k"><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('');
 document.querySelector('#pc19status').innerHTML='<span class="chip '+(a?.sessionDateET?'ok':'bad')+'">جلسة '+esc(a?.sessionDateET||'غير متاحة')+'</span><span class="chip warn">'+esc(a?.status||'PROVISIONAL')+'</span><span class="chip">تحديث التقرير '+(a?.updatedAtUTC?new Date(a.updatedAtUTC).toLocaleTimeString('ar-SA'):'—')+'</span>';
 document.querySelector('#pc19table').innerHTML='<table><thead><tr><th>#</th><th>السهم</th><th>الحركة</th><th>أول رصد</th><th>التصنيف</th><th>Actionability</th><th>Critic</th></tr></thead><tbody>'+top.map(x=>'<tr><td>'+esc(x.rank)+'</td><td><b>'+esc(x.ticker)+'</b></td><td>'+f(n(x.changePct))+'</td><td>'+f(n(x.proactiveFirstChangePct))+'</td><td>'+esc(x.class)+'</td><td>'+esc(x.actionabilityScore??'—')+'</td><td>'+esc(x.critic||'—')+'</td></tr>').join('')+'</tbody></table>';
 const ea=age(e),live=e?.session==='after-hours'&&ea<=12,rs=Object.values(e?.rows||{}).sort((x,y)=>(n(y.sessionChangePct)||-999)-(n(x.sessionChangePct)||-999));document.querySelector('#pc19ah').innerHTML=live&&rs.length?rs.slice(0,20).map(x=>'<div class="pc19card"><b>'+esc(x.ticker)+'</b><div class="'+((n(x.sessionChangePct)||0)>=0?'pc19up':'pc19dn')+'">'+f(n(x.sessionChangePct))+'</div><div class="sub">$'+(n(x.last)?.toFixed(n(x.last)<1?3:2)??'—')+' · 15m '+f(n(x.priceVelocity15mPct))+'</div></div>').join(''):'<div class="empty">بيانات After‑Hours غير حديثة الآن ('+(e?.updatedAtET||'لا توجد لقطة')+'). لن تعرض TAGX بيانات قديمة كأنها حية.</div>'}
 function select(){document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#radarView')?.classList.add('hide');document.querySelector('#performanceView')?.classList.add('hide');sec.classList.remove('hide');load()}
 b.addEventListener('click',select);document.querySelectorAll('.tabs button:not([data-tab="postclose"])').forEach(x=>x.addEventListener('click',()=>sec.classList.add('hide')));load();setInterval(load,30000);window.TAGXPostCloseV19={load};
})();