'use strict';
(function(){
 const RELEASE='TAGX 1.7';
 const FAV_KEY='tagx:favorites:v1', WATCH_KEY='tagx:watchlist:v1', SORT_KEY='tagx:sort:v1', FILTER_KEY='tagx:filter:v1';
 const readSet=k=>{try{return new Set(JSON.parse(localStorage.getItem(k)||'[]'))}catch{return new Set()}};
 const saveSet=(k,s)=>localStorage.setItem(k,JSON.stringify([...s]));
 let fav=readSet(FAV_KEY), watch=readSet(WATCH_KEY), sortMode=localStorage.getItem(SORT_KEY)||'score_desc', filterMode=localStorage.getItem(FILTER_KEY)||'all';
 const style=document.createElement('style');
 style.textContent=`
 .ux17bar{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin:14px 0 2px}.ux17bar select,.ux17seg button{border:1px solid #dce3eb;background:#fff;color:#334155;border-radius:11px;padding:9px 11px;font-weight:800}.ux17seg{display:flex;gap:6px;flex-wrap:wrap}.ux17seg button{cursor:pointer}.ux17seg button.active{background:#0f172a;color:#fff;border-color:#0f172a}.ux17count{font-size:12px;color:#64748b;font-weight:800;margin-inline-start:auto}
 .opp{position:relative;padding-top:46px!important}.ux17actions{position:absolute;top:11px;inset-inline-end:11px;display:flex;gap:6px;z-index:3}.ux17act{border:1px solid #dce3eb;background:#fff;border-radius:10px;width:34px;height:34px;display:grid;place-items:center;cursor:pointer;font-size:17px}.ux17act.on{background:#fff7ed;border-color:#fdba74}.ux17act.watch.on{background:#eff6ff;border-color:#93c5fd}.ux17stage{position:absolute;top:14px;inset-inline-start:14px;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:950}.ux17stage.discovery{background:#ecfdf5;color:#047857}.ux17stage.wake_up{background:#eff6ff;color:#1d4ed8}.ux17stage.pre_ignition{background:#fff7ed;color:#b45309}.ux17stage.ignition{background:#fef2f2;color:#b91c1c}.ux17stage.late,.ux17stage.exhaustion{background:#f1f5f9;color:#64748b}.opp.ux17fav{box-shadow:0 0 0 2px #f59e0b inset}.opp.ux17watch{background:linear-gradient(180deg,#fff,#f8fbff)}
 .ux17rowActions{display:flex;gap:4px}.ux17mini{border:0;background:transparent;cursor:pointer;font-size:17px;padding:3px}.ux17mini.on{filter:saturate(1.5)}tr.ux17fav td:first-child{font-weight:950;color:#b45309}tr.ux17watch{background:#f8fbff}.ux17hidden{display:none!important}.ux17empty{padding:18px;text-align:center;color:#64748b;border:1px dashed #cbd5e1;border-radius:12px;margin-top:10px}
 .ux17legend{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.ux17legend span{font-size:11px;padding:5px 8px;border-radius:999px;background:#f8fafc;color:#475569;font-weight:800}
 @media(max-width:600px){.ux17count{width:100%;margin-inline-start:0}.ux17bar select{width:100%}.ux17seg{width:100%}.ux17seg button{flex:1}.opp{padding-top:50px!important}}
 `;
 document.head.appendChild(style);
 const S=s=>String(s||'').toUpperCase();
 function firstTs(x){try{return new Date(firstInfo(x).ts||0).getTime()||0}catch{return 0}}
 function change(x){return N(x.Change)??-9999}
 function score(x){try{return trace(x).score??0}catch{return 0}}
 function risk(x){let r=0;const st=stage(x),t=trace(x);if(st==='LATE')r+=35;if(st==='EXHAUSTION')r+=60;if(st==='IGNITION')r+=15;r+=(t.down||[]).length*8;const fl=N(x.Float);if(fl!=null&&fl<5)r+=8;return Math.min(100,r)}
 function stageInfo(st){const m={DISCOVERY:['🌱','اكتشاف','discovery'],WAKE_UP:['👀','استيقاظ','wake_up'],PRE_IGNITION:['⚡','قبل الاشتعال','pre_ignition'],IGNITION:['🔥','اشتعال','ignition'],LATE:['⛔','متأخر','late'],EXHAUSTION:['🧯','إنهاك','exhaustion'],DATA:['⚠️','بيانات','late']};return m[st]||['•',st||'—','late']}
 function cmp(a,b){const xa=rowMap.get(a.dataset.ticker),xb=rowMap.get(b.dataset.ticker);if(!xa||!xb)return 0;switch(sortMode){case'latest':return firstTs(xb)-firstTs(xa);case'change_desc':return change(xb)-change(xa);case'change_asc':return change(xa)-change(xb);case'rvol_desc':return (N(xb['Rel Volume'])||0)-(N(xa['Rel Volume'])||0);case'risk_asc':return risk(xa)-risk(xb);case'origin_asc':return (N(firstInfo(xa).ch)??9999)-(N(firstInfo(xb).ch)??9999);default:return score(xb)-score(xa)}}
 function allowed(t){if(filterMode==='favorites')return fav.has(t);if(filterMode==='watch')return watch.has(t);if(filterMode==='early'){const x=rowMap.get(t),s=x?stage(x):'';return ['DISCOVERY','WAKE_UP','PRE_IGNITION','IGNITION'].includes(s)}return true}
 function toggle(kind,t){const set=kind==='fav'?fav:watch,key=kind==='fav'?FAV_KEY:WATCH_KEY;if(set.has(t))set.delete(t);else set.add(t);saveSet(key,set);applyUX();try{toast((kind==='fav'?'⭐ ':'👁 ')+t+(set.has(t)?' تمت إضافته':' تمت إزالته'))}catch{}}
 function button(kind,t){const b=document.createElement('button');b.type='button';b.className='ux17act '+(kind==='watch'?'watch ':'')+((kind==='fav'?fav:watch).has(t)?'on':'');b.title=kind==='fav'?'تفضيل السهم':'متابعة السهم';b.textContent=kind==='fav'?'☆':'👁';if(kind==='fav'&&fav.has(t))b.textContent='★';b.addEventListener('click',e=>{e.stopPropagation();toggle(kind,t)});return b}
 function ensureToolbar(){let bar=document.querySelector('.ux17bar');if(bar)return bar;const hero=document.querySelector('.hero');if(!hero)return null;bar=document.createElement('div');bar.className='ux17bar';bar.innerHTML=`<div class="ux17seg"><button data-f="all">الكل</button><button data-f="early">المبكرة</button><button data-f="favorites">⭐ المفضلة</button><button data-f="watch">👁 المتابعة</button></div><select id="ux17sort"><option value="score_desc">الأعلى تقييمًا</option><option value="latest">الأحدث رصدًا</option><option value="change_asc">الأقل ارتفاعًا</option><option value="change_desc">الأعلى ارتفاعًا</option><option value="rvol_desc">الأعلى RVOL</option><option value="risk_asc">الأقل مخاطرة</option><option value="origin_asc">الأبكر أصلًا</option></select><span class="ux17count" id="ux17count"></span>`;const top=document.querySelector('#topOpps');hero.insertBefore(bar,top);const legend=document.createElement('div');legend.className='ux17legend';legend.innerHTML='<span>🌱 اكتشاف</span><span>👀 استيقاظ</span><span>⚡ قبل الاشتعال</span><span>🔥 اشتعال</span><span>⛔ متأخر</span><span>🧯 إنهاك</span>';hero.insertBefore(legend,top);bar.querySelectorAll('[data-f]').forEach(b=>b.addEventListener('click',()=>{filterMode=b.dataset.f;localStorage.setItem(FILTER_KEY,filterMode);applyUX()}));const sel=bar.querySelector('#ux17sort');sel.value=sortMode;sel.addEventListener('change',()=>{sortMode=sel.value;localStorage.setItem(SORT_KEY,sortMode);applyUX()});return bar}
 function decorateCards(){const cards=[...document.querySelectorAll('#topOpps .opp[data-ticker]')];cards.forEach(card=>{const t=S(card.dataset.ticker),x=rowMap.get(t);if(!x)return;let a=card.querySelector('.ux17actions');if(!a){a=document.createElement('div');a.className='ux17actions';card.appendChild(a)}a.innerHTML='';a.append(button('fav',t),button('watch',t));let st=card.querySelector('.ux17stage');if(!st){st=document.createElement('div');card.appendChild(st)}const inf=stageInfo(stage(x));st.className='ux17stage '+inf[2];st.textContent=inf[0]+' '+inf[1];card.classList.toggle('ux17fav',fav.has(t));card.classList.toggle('ux17watch',watch.has(t));card.classList.toggle('ux17hidden',!allowed(t))});const shown=cards.filter(c=>!c.classList.contains('ux17hidden')).sort(cmp);const host=document.querySelector('#topOpps');shown.forEach(c=>host.appendChild(c));const hidden=cards.filter(c=>c.classList.contains('ux17hidden'));hidden.forEach(c=>host.appendChild(c));const count=document.querySelector('#ux17count');if(count)count.textContent=`ظاهر ${shown.length} · مفضلة ${fav.size} · متابعة ${watch.size}`;let empty=host?.querySelector('.ux17empty');if(!shown.length&&cards.length){if(!empty){empty=document.createElement('div');empty.className='ux17empty';host.appendChild(empty)}empty.textContent='لا توجد أسهم تطابق الفلتر الحالي.'}else empty?.remove()}
 function decorateRows(){const body=document.querySelector('#radarRows');if(!body)return;const rows=[...body.querySelectorAll('tr[data-ticker]')];let head=body.closest('table')?.querySelector('thead tr');if(head&&!head.querySelector('[data-ux17-actions]')){const th=document.createElement('th');th.dataset.ux17Actions='1';th.textContent='متابعة';head.appendChild(th)}rows.forEach(tr=>{const t=S(tr.dataset.ticker),x=rowMap.get(t);if(!x)return;let td=tr.querySelector('[data-ux17-actions]');if(!td){td=document.createElement('td');td.dataset.ux17Actions='1';tr.appendChild(td)}td.innerHTML='';const wrap=document.createElement('div');wrap.className='ux17rowActions';for(const kind of ['fav','watch']){const b=document.createElement('button');b.type='button';const on=(kind==='fav'?fav:watch).has(t);b.className='ux17mini '+(on?'on':'');b.textContent=kind==='fav'?(on?'★':'☆'):'👁';b.title=kind==='fav'?'تفضيل':'متابعة';b.onclick=e=>{e.stopPropagation();toggle(kind,t)};wrap.appendChild(b)}td.appendChild(wrap);tr.classList.toggle('ux17fav',fav.has(t));tr.classList.toggle('ux17watch',watch.has(t));tr.classList.toggle('ux17hidden',!allowed(t))});rows.filter(r=>!r.classList.contains('ux17hidden')).sort(cmp).forEach(r=>body.appendChild(r));rows.filter(r=>r.classList.contains('ux17hidden')).forEach(r=>body.appendChild(r))}
 function syncButtons(){document.querySelectorAll('.ux17seg [data-f]').forEach(b=>b.classList.toggle('active',b.dataset.f===filterMode));const s=document.querySelector('#ux17sort');if(s&&s.value!==sortMode)s.value=sortMode}
 function applyUX(){ensureToolbar();syncButtons();decorateCards();decorateRows()}
 const baseRender=render;render=function(){baseRender();applyUX()};
 const baseOpen=openStock;openStock=function(ticker){baseOpen(ticker);setTimeout(()=>{const body=document.querySelector('#drawerBody');if(!body)return;const t=S(ticker),x=rowMap.get(t);if(!x)return;let box=body.querySelector('[data-ux17-follow]');if(!box){box=document.createElement('div');box.className='section';box.dataset.ux17Follow='1';body.prepend(box)}const inf=stageInfo(stage(x));box.innerHTML=`<h4>التصنيف والمتابعة</h4><div class="riskline"><b>${inf[0]} ${inf[1]}</b> · TAGX ${score(x)} · Risk ${risk(x)}/100<br><button class="btn" data-fav>${fav.has(t)?'★ إزالة من المفضلة':'☆ إضافة للمفضلة'}</button> <button class="btn" data-watch>${watch.has(t)?'👁 إيقاف المتابعة':'👁 متابعة السهم'}</button></div>`;box.querySelector('[data-fav]').onclick=()=>toggle('fav',t);box.querySelector('[data-watch]').onclick=()=>toggle('watch',t)},0)};
 window.TAGXUIV17={release:RELEASE,getFavorites:()=>[...fav],getWatchlist:()=>[...watch],apply:applyUX};
 document.title='TAGX 1.7 — Smart Cards & Watchlists';const ey=document.querySelector('.ey');if(ey)ey.textContent='TAGX 1.7 · SMART CARDS & WATCHLISTS';const footer=document.querySelector('footer');if(footer)footer.innerHTML='<b>TAGX 1.7</b> — بطاقات مصنفة، مفضلة ومتابعة محفوظة محليًا، وفرز ديناميكي دون تغيير منهجية التقييم.';
 try{applyUX()}catch(e){console.error('TAGX UI v17',e)}
})();