(()=>{'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), money=n=>Number.isFinite(n)?'$'+n.toFixed(2):'—', num=id=>Number($(id).value), KEY='tagit-paper-v1';
let book={capital:200,trades:[]}, selected=null, calculated=null;
try{const raw=localStorage.getItem(KEY);if(raw){const b=JSON.parse(raw);if(!Number.isFinite(b.capital)||b.capital<=0||!Array.isArray(b.trades)||b.trades.some(t=>!['OPEN','CLOSED'].includes(t.status)||!Number.isFinite(t.cost)||!Number.isFinite(t.qty)||t.qty<=0||!Number.isFinite(t.entryFill)||!Number.isFinite(t.fee)||!Number.isFinite(t.slippagePct)||(t.status==='CLOSED'&&!Number.isFinite(t.pnl))))throw Error('Invalid journal');book=b;}}catch(e){$('storageStatus').textContent='Journal could not be loaded. Export any accessible records before clearing browser storage.';}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));book=next;$('storageStatus').textContent='Saved in this browser. Export a backup from Journal.';return true;}catch(e){$('storageStatus').textContent='Save failed. Browser storage is unavailable or full; this change was not recorded.';return false;}}
function balance(){const closed=book.trades.filter(t=>t.status==='CLOSED'),pnl=closed.reduce((a,t)=>a+t.pnl,0),equity=book.capital+pnl,cash=equity-book.trades.filter(t=>t.status==='OPEN').reduce((a,t)=>a+t.cost,0);return {closed,pnl,equity,cash};}
function view(name){document.querySelectorAll('.desk-view').forEach(e=>e.hidden=e.id!=='view-'+name);document.querySelectorAll('[data-view]').forEach(e=>{e.classList.toggle('active',e.dataset.view===name);e.setAttribute('aria-pressed',String(e.dataset.view===name));});if(name==='research')research();}
document.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>view(e.dataset.view));
window.addEventListener('tagit-selection',e=>selected=e.detail);
window.addEventListener('tagit-plan-request',()=>{if(!selected)return;view('planner');$('planSymbol').value=selected.symbol;$('planEntry').value=selected.price||'';$('planStop').value=selected.support15m>0&&selected.support15m<selected.price?selected.support15m:'';$('planTarget').value='';invalidate();$('planResult').textContent='Imported reference price; verify current price and define your own stop/target before calculating.';});
function invalidate(){calculated=null;$('savePaper').disabled=true;}
$('planForm').addEventListener('input',()=>{invalidate();$('planResult').textContent='Inputs changed. Recalculate the plan.';});
$('target2R').onclick=()=>{const e=num('planEntry'),s=num('planStop');if(e>s&&s>0)$('planTarget').value=(e+2*(e-s)).toFixed(6);invalidate();};
function calculate(){invalidate();if(!$('planForm').reportValidity())return null;const b=balance(),p={...b,entry:num('planEntry'),stop:num('planStop'),target:num('planTarget'),riskPct:num('planRisk'),fee:num('planFee'),slippagePct:num('planSlip'),fractional:$('planFractional').checked},r=TradeMath.plan(p);if(!r.ok){$('planResult').textContent=r.error;return null;}calculated={...p,...r,symbol:$('planSymbol').value.toUpperCase(),thesis:$('planThesis').value};$('planResult').innerHTML=`<div class="data-grid"><div>Shares<strong>${r.qty}</strong></div><div>Cash used<strong>${money(r.cost)}</strong></div><div>Loss at assumed stop<strong>${money(r.risk)}</strong></div><div>Gain at assumed target<strong>${money(r.reward)}</strong></div><div>Reward / risk after costs<strong>${r.rr.toFixed(2)}R</strong></div><div>Break-even win rate*<strong>${r.breakevenWinPct.toFixed(1)}%</strong></div></div><p class="note">*Arithmetic for these two outcomes only, not a predicted success rate. Risk reference: starting capital + realized P&amp;L; excludes open position marks. Stop losses are estimates, not maximum losses.</p>`;$('savePaper').disabled=false;return calculated;}
$('planForm').onsubmit=e=>{e.preventDefault();calculate();};
$('savePaper').onclick=()=>{const p=calculate();if(!p)return;const t={id:crypto.randomUUID(),openedAt:new Date().toISOString(),symbol:p.symbol,entry:p.entry,entryFill:p.entryFill,stop:p.stop,target:p.target,qty:p.qty,cost:p.cost,fee:p.fee,slippagePct:p.slippagePct,risk:p.risk,reward:p.reward,thesis:p.thesis,status:'OPEN'};if(persist({...book,trades:[...book.trades,t]})){invalidate();render();$('planResult').textContent='Paper entry recorded. Track and close it manually in Journal.';}};
$('paperCapital').onchange=()=>{const c=num('paperCapital');if(book.trades.length){$('storageStatus').textContent='Starting capital is locked once the first paper trade is recorded.';$('paperCapital').value=book.capital;return;}if(c>0&&Number.isFinite(c)&&persist({...book,capital:c})){invalidate();render();}else $('paperCapital').value=book.capital;};
function render(){const b=balance();$('paperCapital').value=book.capital;$('paperCapital').disabled=book.trades.length>0;$('capitalSummary').textContent=`Available paper cash: ${money(b.cash)} · realized capital: ${money(b.equity)}`;$('journalPnL').textContent=money(b.pnl);$('journalCount').textContent=b.closed.length;$('journalWin').textContent=b.closed.length?(100*b.closed.filter(t=>t.pnl>0).length/b.closed.length).toFixed(1)+'%':'—';$('journalCash').textContent=money(b.cash);let e=book.capital,peak=e,dd=0;b.closed.slice().sort((a,b)=>a.closedAt.localeCompare(b.closedAt)).forEach(t=>{e+=t.pnl;peak=Math.max(peak,e);dd=Math.max(dd,(peak-e)/peak*100);});$('journalDrawdown').textContent=dd.toFixed(1)+'%';$('journalRows').innerHTML=book.trades.length?book.trades.slice().reverse().map(t=>`<article class="journal-item"><div><strong>${esc(t.symbol)}</strong> <span class="pill">${esc(t.status)}</span> · ${t.qty} shares · entry ${money(t.entryFill)} · stop ${money(t.stop)} · target ${money(t.target)}<p class="note">${esc(t.openedAt)} · ${esc(t.thesis)}</p></div>${t.status==='CLOSED'?`<strong>${money(t.pnl)}</strong><small>Closed ${esc(t.closedAt)} at ${money(t.exit)}</small>`:`<form data-close="${esc(t.id)}"><label>Manual exit reference ($)<input name="exit" type="number" min="0.000001" step="any" required aria-label="Exit price for ${esc(t.symbol)}"></label><button class="ghost" type="submit">Close paper trade</button></form>`}</article>`).join(''):'<p class="note">No paper trades yet. Build a plan to begin your journal.</p>';}
$('journalRows').addEventListener('submit',e=>{e.preventDefault();const f=e.target,id=f.dataset.close,exit=Number(new FormData(f).get('exit')),t=book.trades.find(t=>t.id===id&&t.status==='OPEN');if(!t||!Number.isFinite(exit)||exit<=0)return;const next={...book,trades:book.trades.map(x=>x===t?{...t,status:'CLOSED',closedAt:new Date().toISOString(),exit,pnl:TradeMath.closedNet(t,exit)}:x)};if(persist(next)){invalidate();render();}});
$('exportJournal').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({...book,exportedAt:new Date().toISOString(),mode:'MANUAL_PAPER_ONLY'},null,2)],{type:'application/json'}));a.href=url;a.download='tagit-paper-journal.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
let busy=false,loaded=false;
async function research(force=false){if(busy||loaded&&!force)return;busy=true;const el=$('researchReport');el.textContent='Loading historical test evidence…';try{const r=await fetch('https://raw.githubusercontent.com/tufeeq/ai/main/tagit10/reports/historical-training.json?t='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(r.status);const d=await r.json(),t=d.test||{},f=n=>Number.isFinite(n)?n.toLocaleString('en-US'):'—';el.innerHTML=`<p class="warn"><strong>${esc(d.status)} · ${d.promoted?'Promoted':'Not promoted to live ranking'}</strong></p><div class="data-grid"><div>5-minute bars<strong>${f(d.barCount)}</strong></div><div>Symbols<strong>${f(d.symbolsWithBars)}</strong></div><div>Training examples<strong>${f(d.examples)}</strong></div><div>Test selections<strong>${f(t.selected)}</strong></div><div>Test target-hit precision<strong>${f(t.precisionPct)}%</strong></div><div>Mean net return / example<strong>${f(t.meanNetReturnPct)}%</strong></div></div><p>Test: ${esc((d.splits?.test||[]).join(' · '))}</p><p>Positive mean-return sessions: ${f(d.stability?.positiveMeanSessions)} / ${f(d.stability?.testSessions)}. Test recall: ${f(t.recallPct)}%. Brier score: ${f(t.brierScore)}.</p><p class="note">${esc(d.target)}. These are per-example results, not portfolio returns. A negative mean is evidence against using this model for trading.</p><ul>${(d.limitations||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p class="note">Generated ${esc(d.generatedAtUTC)} · 95% precision has not been demonstrated.</p>`;loaded=true;}catch(e){el.textContent='Historical report unavailable. Retry to load actual evidence; no estimated results are substituted.';}finally{busy=false;}}
$('researchRefresh').onclick=()=>research(true);render();
})();
