import test from 'node:test';import assert from 'node:assert/strict';
import {emptyState,seedState,apply,detect,metrics,forecast,parseCSV,csv,kinds,validateRecord,restoreBackup,can,capabilities,productivity} from '../core.mjs';
const owner={role:'owner',name:'Owner'},date='2026-09-13';const run=(s,c,a=owner)=>apply(s,c,a,date).state;
test('seed contains all seven domains and coherent invoice balances',()=>{const s=seedState(date);for(const [k,rs]of Object.entries(s.records)){assert(rs.length>0);rs.forEach(r=>validateRecord(k,r,s));}assert.equal(Object.keys(s.records).length,7);});
test('cycle is deduplicated and does not manufacture money',()=>{let s=seedState(date),n=s.decisions.length,m=metrics(s,date);for(let i=0;i<20;i++)s=run(s,{type:'cycle'});assert.equal(s.decisions.length,n);assert.deepEqual(metrics(s,date),m);});
test('complete decision to verified result with separate assignment and evidence',()=>{let s=seedState(date),d=s.decisions[0];s=run(s,{type:'decision.approve',id:d.id});assert.equal(s.tasks.length,0);s=run(s,{type:'decision.execute',id:d.id});assert.equal(s.tasks.length,1);assert.equal(metrics(s,date).verified,0);assert.throws(()=>run(s,{type:'decision.verify',id:d.id,evidence:'A detailed reference'}),/Complete/);s=run(s,{type:'task.save',task:{...s.tasks[0],status:'completed'}});s=run(s,{type:'decision.verify',id:d.id,category:'cash_received',amount:1200,evidence:'Payment reference BANK-123, received and checked.'});assert.equal(metrics(s,date).verified,1200);assert.throws(()=>run(s,{type:'decision.verify',id:d.id,evidence:'again'}));});
test('execute requires approval and duplicate execution cannot create a second task',()=>{let s=seedState(date),id=s.decisions[0].id;assert.throws(()=>run(s,{type:'decision.execute',id}),/Approve/);s=run(s,{type:'decision.approve',id});s=run(s,{type:'decision.execute',id});assert.throws(()=>run(s,{type:'decision.execute',id}));assert.equal(s.tasks.length,1);});
test('viewer cannot mutate; operator cannot approve; manager has exposure limit',()=>{const s=seedState(date),id=s.decisions.find(x=>x.exposure>50000).id;assert.throws(()=>run(s,{type:'cycle'},{role:'viewer'}),/Read-only/);assert.throws(()=>run(s,{type:'decision.approve',id},{role:'operator'}),/Permission/);assert.throws(()=>run(s,{type:'decision.approve',id},{role:'manager'}),/owner/);});
test('rejection requires reason and fresh signal before reopening',()=>{let s=seedState(date),id=s.decisions[0].id;assert.throws(()=>run(s,{type:'decision.reject',id,reason:''}));s=run(s,{type:'decision.reject',id,reason:'Contractual dispute being handled separately'});assert.equal(s.decisions[0].status,'rejected');s=run(s,{type:'decision.reopen',id});assert.equal(s.decisions[0].status,'pending');});
test('source changed after approval blocks execution and invalidates approval on cycle',()=>{let s=seedState(date),d=s.decisions.find(d=>d.kind==='invoices');s=run(s,{type:'decision.approve',id:d.id});const r=s.records.invoices.find(r=>r.id===d.sourceId);s=run(s,{type:'record.save',kind:'invoices',record:{...r,amount:r.amount+100}});assert.throws(()=>run(s,{type:'decision.execute',id:d.id}),/Source changed/);s=run(s,{type:'cycle'});assert.equal(s.decisions.find(x=>x.id===d.id).status,'pending');});
test('settled invoice supersedes obsolete pending decision',()=>{let s=seedState(date),d=s.decisions.find(d=>d.kind==='invoices'),r=s.records.invoices.find(r=>r.id===d.sourceId);s=run(s,{type:'invoice.payment',id:r.id,amount:r.amount-r.paid,reference:'BANK-SETTLED'});s=run(s,{type:'cycle'});assert.equal(s.decisions.find(x=>x.id===d.id).status,'superseded');});
test('invalid import is atomic and foreign customer references fail',()=>{const s=seedState(date),r=s.records.invoices[0];assert.throws(()=>run(s,{type:'import',kind:'invoices',rows:[r,{...r,name:'bad',customer:'another-tenant'}]}),/Customer/);assert.equal(s.records.invoices.length,24);});
test('import matches names and repeated import does not duplicate records',()=>{let s=seedState(date),rows=s.records.customers.slice(0,2);s=run(s,{type:'import',kind:'customers',rows});s=run(s,{type:'import',kind:'customers',rows});assert.equal(s.records.customers.length,8);});
test('validation rejects negative, non-finite, impossible dates, and inconsistent payment states',()=>{const s=seedState(date),r=s.records.invoices[0];for(const patch of [{amount:-1},{amount:NaN},{paid:1e20},{due:'2026-02-30'},{status:'open'}])assert.throws(()=>validateRecord('invoices',{...r,...patch},s));});
test('CSV handles embedded commas, escaped quotes, newlines, CRLF and BOM',()=>{const data='\uFEFFname,notes\r\n"A, B","two ""quotes""\nand newline"\r\n';assert.deepEqual(parseCSV(data),[{name:'A, B',notes:'two "quotes"\nand newline'}]);assert.throws(()=>parseCSV('a,b\n"unfinished,b'));assert.throws(()=>parseCSV('a,a\n1,2'));assert(csv([{name:'=HYPERLINK("evil")'}],['name']).includes("'=HYPERLINK"));});
test('scenario does not mutate state or count bookings as cash',()=>{const s=seedState(date),copy=structuredClone(s),f=forecast(s,{collection:0,winRate:100,spendChange:0});assert.equal(f.closing,s.company.cash-s.company.monthlyBurn);assert.deepEqual(s,copy);assert.throws(()=>forecast(s,{collection:101}));});
test('removing referenced customers is blocked',()=>{const s=seedState(date);assert.throws(()=>run(s,{type:'record.archive',kind:'customers',id:'c0'}),/linked/);});
test('empty company has no invented runway or signals',()=>{const s=emptyState();assert.equal(metrics(s).runway,null);assert.equal(detect(s).length,0);});

test('payment ledger updates invoice and cash exactly once',()=>{let s=seedState(date),r=s.records.invoices.find(x=>x.paid<x.amount),cash=s.company.cash,paid=r.paid;s=run(s,{type:'invoice.payment',id:r.id,amount:100,reference:'BANK-UNIQUE'});assert.equal(s.company.cash,cash+100);assert.equal(s.records.invoices.find(x=>x.id===r.id).paid,paid+100);assert.throws(()=>run(s,{type:'invoice.payment',id:r.id,amount:100,reference:'BANK-UNIQUE'}),/already/);});
test('deal conversion creates linked project and invoice without creating cash',()=>{let s=seedState(date),d=s.records.deals[0],p=s.records.projects.length,i=s.records.invoices.length,cash=s.company.cash;s=run(s,{type:'deal.convert',id:d.id,deposit:25,due:'2026-11-01'});assert.equal(s.records.projects.length,p+1);assert.equal(s.records.invoices.length,i+1);assert.equal(s.records.invoices.at(-1).amount,d.amount*.25);assert.equal(s.company.cash,cash);assert.equal(s.records.projects.at(-1).dealId,d.id);assert.throws(()=>run(s,{type:'deal.convert',id:d.id,deposit:25,due:'2026-11-01'}),/closed/);});

test('restore rejects executable identifiers and disables automatic cycles',()=>{const s=seedState(date);s.company.automation=true;const restored=restoreBackup({format:'operon-backup-v1',state:s});assert.equal(restored.company.automation,false);s.tasks.push({id:'bad" onclick="alert(1)',status:'todo'});assert.throws(()=>restoreBackup({format:'operon-backup-v1',state:s}),/identifier/);});

test('matrix changes are enforced and reserved admin authority cannot be delegated',()=>{let s=seedState(date);const permissions={manager:[],operator:['records.write']};s=run(s,{type:'policy.save',permissions});assert.equal(can(s,'manager','decisions.approve'),false);assert.throws(()=>run(s,{type:'decision.approve',id:s.decisions[0].id},{role:'manager'}),/Permission/);assert.throws(()=>run(s,{type:'policy.save',permissions},{role:'operator'}),/Permission/);assert.throws(()=>run(s,{type:'policy.save',permissions:{manager:['policy.manage'],operator:[]}}),/owner-only/);assert.equal(can(s,'owner','policy.manage'),true);});
test('approval and assignment is atomic if execution capability is missing',()=>{let s=seedState(date),id=s.decisions[0].id;s=run(s,{type:'policy.save',permissions:{manager:['decisions.approve'],operator:[]}});assert.throws(()=>run(s,{type:'decision.approve_assign',id},{role:'manager'}),/Execution/);assert.equal(s.decisions[0].status,'pending');s=run(s,{type:'decision.approve_assign',id});assert.equal(s.decisions[0].status,'executing');assert.equal(s.tasks.length,1);});
test('archive retains a recoverable copy and restore is authorized',()=>{let s=emptyState();s=run(s,{type:'record.save',kind:'people',record:{name:'QA person',owner:'Owner',team:'QA',capacity:40,allocated:20,status:'active',notes:''}});const id=s.records.people[0].id;s=run(s,{type:'record.archive',kind:'people',id});assert.equal(s.records.people.length,0);assert.equal(s.trash.length,1);assert.throws(()=>run(s,{type:'record.restore',id:s.trash[0].id},{role:'operator'}),/Permission/);s=run(s,{type:'record.restore',id:s.trash[0].id});assert.equal(s.records.people[0].id,id);assert.equal(s.trash.length,0);});
test('productivity metrics expose sample size and genuine overdue work',()=>{const s=emptyState();let p=productivity(s,new Date('2026-09-13T12:00:00Z'));assert.equal(p.medianCycleHours,null);assert.equal(p.cycleSample,0);s.tasks=[{id:'a',owner:'Unassigned',due:'2026-09-10',status:'blocked'}];p=productivity(s,new Date('2026-09-13T12:00:00Z'));assert.equal(p.overdue,1);assert.equal(p.unassigned,1);assert.equal(p.blocked,1);});
