// Wider observational cohort. These OR conditions never authorize an entry.
export const LEARNING_RULES=Object.freeze({version:'observation-wide-1',maxPriceAgeMs:300000,minAbsoluteMinuteMovePct:0.3,minAbsoluteThreeMinuteMovePct:0.3,minVolumeRatio:1.2,minMinuteDollars:2000});
export function learningPool(scan){const at=Date.parse(scan.server_time),rules=LEARNING_RULES;return {version:rules.version,rules,at:scan.server_time,feed:scan.feed,scope:'CURRENT_REFERENCE_NASDAQ_UNDER_100M',rows:(scan.rows||[]).map(row=>{
 const age=at-Date.parse(row.price_at),recent=Number.isFinite(age)&&age>=0&&age<=rules.maxPriceAgeMs,minuteAge=at-Date.parse(row.minute_at),minuteValid=Number.isFinite(minuteAge)&&minuteAge>=60000&&minuteAge<=rules.maxPriceAgeMs,reasons=[];
 if(recent&&minuteValid&&Number.isFinite(row.minute_change)&&Math.abs(row.minute_change)>=rules.minAbsoluteMinuteMovePct)reasons.push('MINUTE_MOVE');
 if(recent&&row.signal?.ready&&Math.abs(row.signal.return_3m)>=rules.minAbsoluteThreeMinuteMovePct)reasons.push('THREE_MINUTE_MOVE');
 if(recent&&row.signal?.ready&&row.signal.volume_ratio>=rules.minVolumeRatio)reasons.push('VOLUME_ACTIVITY');
 if(recent&&minuteValid&&row.minute_dollars>=rules.minMinuteDollars)reasons.push('MINUTE_TURNOVER');
 return {symbol:row.symbol,market_cap:row.market_cap,metadata_at:row.metadata_at,price:row.price,price_at:row.price_at,observed_at:scan.server_time,price_age_ms:Number.isFinite(age)?age:null,recent,preliminary:reasons.length>0,reasons,minute_at:row.minute_at,minute_change:minuteValid?row.minute_change:null,minute_dollars:row.minute_dollars,spread_pct:row.spread_pct,volume_ratio:row.signal?.volume_ratio??null,return_3m:row.signal?.ready?row.signal.return_3m:null,detector_ready:row.signal?.ready===true,strict_discovery:row.signal?.expansion===true,sharia_status:'UNKNOWN',entry_authorized:false};})};}
export function retainLearning(previous,pool){const ledger={...(previous||{})};if(!pool)return ledger;const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(pool.at));for(const row of pool.rows){const key=day+'|'+row.symbol;let item=ledger[key];if(!item&&row.preliminary)item=ledger[key]={symbol:row.symbol,session:day,first_observed_at:pool.at,first_price:row.price,first_price_at:row.price_at,first_reasons:[...row.reasons],version:pool.version,source:pool.feed};if(item&&Date.parse(pool.at)>=Date.parse(item.last_observed_at||item.first_observed_at)){item.last_observed_at=pool.at;item.last_price=row.price;item.last_price_at=row.price_at;item.current_preliminary=row.preliminary;}}return ledger;}
