import test from 'node:test';
import assert from 'node:assert/strict';
import {viewQuote,serviceOrigin,validPayload} from '../../web/price-state.mjs';
const clock=Date.parse('2026-09-16T14:00:00Z');
const at=ms=>new Date(clock-ms).toISOString();
function payload(){return {schema_version:1,status:'OK',feed:'iex',server_time:at(0),provider_received_at:at(50),metadata_at:at(1000),approved_for_live:false,rows:[{symbol:'SENS',feed:'iex',status:'RECENT_IEX',market_cap:4e8,metadata_at:at(1000),approved_for_live:false,quote:{bid:1,ask:1.002,bid_size:100,ask_size:100,timestamp:at(1000),age_ms:1000},trade:{price:1.001,timestamp:at(2000),age_ms:2000}}]};}
test('view quote ages while no new response arrives',()=>{const r=payload().rows[0];assert.equal(viewQuote(r,3001).status,'STALE');assert.equal(viewQuote(r,3001).tradeStatus,'STALE');});
test('delayed feed cannot be relabelled recent',()=>assert.equal(viewQuote({status:'DELAYED',feed:'delayed_sip',quote:{age_ms:0},trade:{age_ms:0}},0).tradeStatus,'DELAYED'));
test('API URL cannot contain a key, query, password or non-HTTPS origin',()=>{assert.equal(serviceOrigin('https://example.com'),'https://example.com');for(const url of ['http://example.com','https://key:secret@example.com','https://example.com?key=secret','https://example.com/api/quotes','javascript:alert(1)'])assert.throws(()=>serviceOrigin(url));});
test('missing, extra, duplicate and billion-dollar responses rejected',()=>{const p=payload(),row=p.rows[0];assert(validPayload(p,['SENS']));assert(!validPayload(p,['NUAI']));assert(!validPayload({...p,rows:[row,row]},['SENS','NUAI']));assert(!validPayload({...p,rows:[{...row,market_cap:1e9}]},['SENS']));assert(!validPayload({...p,approved_for_live:true},['SENS']));});
test('age labels cannot conceal an old or future timestamp',()=>{for(const ms of [50000,-1000]){const p=payload();p.rows[0].quote.timestamp=at(ms);assert(!validPayload(p,['SENS']));}});
test('missing clock, timezone, or stale response receipt is rejected',()=>{for(const key of ['server_time','provider_received_at','metadata_at']){const p=payload();delete p[key];assert(!validPayload(p,['SENS']));}const p=payload();p.server_time='2026-09-16T14:00:00';assert(!validPayload(p,['SENS']));const old=payload();old.provider_received_at=at(2000);assert(!validPayload(old,['SENS']));});
test('unknown status, misleading fresh status, invalid quote size and row metadata fail closed',()=>{for(const patch of [{status:'UNKNOWN'},{status:'RECENT_SIP'},{metadata_at:at(86400001)}]){const p=payload();Object.assign(p.rows[0],patch);assert(!validPayload(p,['SENS']));}for(const size of [Infinity,'100',0]){const p=payload();p.rows[0].quote.ask_size=size;assert(!validPayload(p,['SENS']));}});
test('partial results account for every requested symbol exactly once',()=>{const p={...payload(),status:'PARTIAL',rejected:['AAPL']};assert(validPayload(p,['SENS','AAPL']));assert(!validPayload(p,['SENS','AAPL','XYZ']));assert(!validPayload({...p,rejected:['SENS']},['SENS','AAPL']));assert(!validPayload({...p,status:'OK'},['SENS','AAPL']));});
test('stale observations remain viewable only with their correct label',()=>{const p=payload();p.rows[0].quote.timestamp=at(5000);p.rows[0].quote.age_ms=5000;p.rows[0].status='STALE';assert(validPayload(p,['SENS']));p.rows[0].status='RECENT_IEX';assert(!validPayload(p,['SENS']));});
test('null rows and absent quotes cannot be shown as recent',()=>{assert(!validPayload({...payload(),rows:[null]},['SENS']));const p=payload();p.rows[0].quote=null;assert(!validPayload(p,['SENS']));p.rows[0].status='INVALID_QUOTE';assert(validPayload(p,['SENS']));});
