import{enrich,marketRegime}from'./core.js';
const SIGNAL_FEED='../tag/data/tagit-signal-feed.json';
const BASE_FEED='../tag/data/finviz.json';
const $=s=>document.querySelector(s);
const fmt=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2});
const pct=n=>n===null||n===undefined||!Number.isFinite(+n)?'—':`${+n>=0?'+':''}${fmt(n)}%`;
const val=v=>v===null||v===undefined||!Number.isFinite(+v)?'—':fmt(v);
const plain=v=>{if(v===null||v===undefined||v==='')return null;const x=parseFloat(String(v).replace(/[$,%x,]/g,''));return Number.isFinite(x)?x:null};
const millions=v=>{if(v===null||v===undefined||v==='')return null;const s=String(v).trim().toUpperCase().replace(/,/g,''),x=parseFloat(s);if(!Number.isFinite(x))return null;if(s.endsWith('B'))return x*1000;if(s.endsWith('M'))return x;if(s.endsWith('K'))return x/1000;return x>1e5?x/1e6:x};
const active=s=>['pre-market','regular','after-hours'].includes(String(s||'').toLowerCase());
const phaseLabels={ANOMALY:'Anomaly',IGNITION:'Ignition',ACCELERATION:'Acceleration',BREAKOUT:'Breakout',EXPANSION:'Expansion',EXHAUSTION:'Exhaustion',FAILED:'Failed'};
let state={items:[],session:'loading',asOf:null,sourceHealthy:false,filter:'ALL',selected:null,market:{},mode:'loading',source:'TAGit'};
async function json(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()}
function baseMap(raw){const m=new Map();for(const r of raw.rows||raw.data||[]){const s=String(r.Ticker||r.Symbol||'').trim().toUpperCase();if(!s)continue;m.set(s,{price:plain(r.Price),changePct:plain(r.Change),rvol:plain(r['Relative Volume']??r['Rel Volume']),volume:plain(r.Volume),floatM:millions(r['Shares Float']??r.Float??r['Shs Float'])})}return m}
function marketFromSignal(s){return{spyChangePct:plain(s.market?.spy?.changePct),qqqChangePct:plain(s.market?.qqq?.changePct),iwmChangePct:plain(s.market?.iwm?.changePct),vixChangePct:null,breadthPct:null}}
function fromDerived(sig,base){const bm=baseMap(base);const items=(sig.items||[]).map(x=>{const q=bm.get(x.symbol)||{},rot=q.floatM&&q.volume?q.volume/(q.floatM*1e6):null;return{...x,price:q.price,changePct:q.changePct,rvol:q.rvol,floatRotation:rot,gate:{status:x.state,reason:x.executionVerified?'التحليل والتنفيذ موثقان':x.executionNote||'حالة تحليلية مشتقة'},summary:x.modelEvidence||`Precursor ${x.precursorScore}`,components:{risk:x.riskScore,quality:x.dataQualityScore},features:{floatRotation:rot}}});return{items,session:sig.session||base.session||'unknown',asOf:sig.updatedAt||base.updatedAt,sourceHealthy:Boolean(sig.sourceHealthy),market:marketFromSignal(sig),mode:'derived',source:sig.source||'TAGit derived signals'}}
function fallback(raw){const rows=raw.rows||raw.data||[],session=String(raw.session||'unknown').toLowerCase(),asOf=raw.updatedAt||raw.snapshotTimestampUTC;const symbols=rows.slice(0,180).map(r=>{const signals=r._signals||[],rvol=plain(r['Relative Volume']??r['Rel Volume']),slope=plain(r._persistenceSlopePctPts),floatM=millions(r['Shares Float']??r.Float),price=plain(r.Price),change=plain(r.Change)??0;return{symbol:String(r.Ticker||'').toUpperCase(),price,changePct:change,volume:plain(r.Volume)??0,rvol,floatM,spreadPct:null,volumeAcceleration:null,priceAccelerationPctPerMin:slope===null?null:slope/60,momentumPct:{},breakoutQuality:signals.some(x=>String(x).includes('topgainers'))?.55:null,vwapPosition:null,distanceToBreakoutPct:null,catalystStrength:null,catalystFreshnessMin:null,dilutionRisk:.28,haltRisk:change>55?.34:change>35?.18:.07,dataQuality:rvol!==null?.58:.48,evidence:['Fallback base feed','Rich derived feed unavailable; no missing field is fabricated.']}}).filter(x=>x.symbol&&x.price>0);const scored=enrich(symbols,{}).map(x=>({...x,state:x.gate.status,precursorScore:null,continuationScore:x.continuation.score,tradabilityScore:x.tradability.score,riskScore:x.components.risk,dataQualityScore:x.components.quality,executionVerified:false,executionNote:'Fallback: execution fields unverified'}));return{items:scored,session,asOf,sourceHealthy:false,market:{},mode:'fallback',source:'Finviz base fallback'}}
async function load(){try{const [sig,base]=await Promise.all([json(SIGNAL_FEED),json(BASE_FEED)]);apply(fromDerived(sig,base));}catch(e){console.warn('Derived feed unavailable, using base fallback',e);try{apply(fallback(await json(BASE_FEED)))}catch(e2){console.error(e2);apply({items:[],session:'unavailable',asOf:new Date().toISOString(),sourceHealthy:false,market:{},mode:'unavailable',source:'Unavailable'})}}}
function apply(x){Object.assign(state,x);state.selected=state.items[0]?.symbol||null;render()}
function statusClass(s){return ['WATCH','DISCOVER','OBSERVE','CAUTION','REJECT','BLOCKED','CLOSED'].includes(s)?s:'OBSERVE'}
function render(){const visible=state.filter==='ALL'?state.items:state.items.filter(x=>x.phase===state.filter);$('#rows').innerHTML=visible.map(x=>`<tr data-symbol="${x.symbol}"><td><span class="ticker">${x.symbol}</span></td><td><span class="stage ${x.phase}">${phaseLabels[x.phase]||x.phase||'—'}</span></td><td><span class="score">${val(x.score)}</span></td><td><b>${val(x.actionability)}</b></td><td><span class="gate ${statusClass(x.state)}">${x.state}</span></td><td>${x.price==null?'—':'$'+fmt(x.price)}</td><td class="${(x.changePct??0)>=0?'pos':'neg'}">${pct(x.changePct)}</td><td>${x.rvol==null?(x.featureFlags?.rvol||'—'):fmt(x.rvol)+'x'}</td><td>${x.floatRotation==null?(x.featureFlags?.float||'—'):fmt(x.floatRotation)+'x'}</td><td class="signal">${x.modelEvidence||x.summary||'—'}</td></tr>`).join('')||'<tr><td colspan="10">لا توجد إشارات متاحة.</td></tr>';
 const watch=state.items.filter(x=>x.state==='WATCH').length,discover=state.items.filter(x=>x.state==='DISCOVER').length;$('#metricCandidates').textContent=watch;const md=$('#metricDiscover');if(md)md.textContent=discover;$('#metricAcceleration').textContent=state.items.filter(x=>x.phase==='ACCELERATION').length;$('#metricRisk').textContent=state.items.filter(x=>['CAUTION','REJECT','BLOCKED'].includes(x.state)||(x.riskScore??0)>=60).length;const reg=marketRegime(state.market||{});$('#regimeText').textContent=reg.label;$('#regimeScore').textContent=reg.score;$('#sessionText').textContent=String(state.session||'unknown').toUpperCase();$('#asOfText').textContent=state.asOf?new Date(state.asOf).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';$('#modePill').className=`pill ${state.sourceHealthy&&active(state.session)?'live':'demo'}`;$('#modeText').textContent=state.mode==='derived'?(state.sourceHealthy?'DERIVED ELITE SIGNALS • FRESH':state.session==='closed'?'LAST DERIVED SNAPSHOT':'DERIVED SIGNALS • BLOCKED'):state.mode==='fallback'?'BASE FALLBACK':'DATA UNAVAILABLE';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter));document.querySelectorAll('tr[data-symbol]').forEach(r=>r.onclick=()=>{state.selected=r.dataset.symbol;renderDetail()});renderDetail()}
function renderDetail(){const x=state.items.find(i=>i.symbol===state.selected);if(!x){$('#detail').className='detail empty';$('#detail').textContent='لا توجد بطاقة متاحة.';return}const flags=x.featureFlags||{},flagHtml=Object.entries(flags).map(([k,v])=>`<div class="evidence-item"><b>${k}</b> • ${v}</div>`).join('');const execution=x.executionVerified?'EXECUTION VERIFIED':'EXECUTION UNVERIFIED';$('#detail').className='detail';$('#detail').innerHTML=`<div class="decision-top"><div><h2>${x.symbol}</h2><span class="stage ${x.phase}">${phaseLabels[x.phase]||x.phase||'—'}</span></div><div class="bigscore"><b>${val(x.actionability)}</b><span>Actionability</span></div></div><div class="price-line"><span class="price">${x.price==null?'—':'$'+fmt(x.price)}</span><span class="${(x.changePct??0)>=0?'pos':'neg'}">${pct(x.changePct)}</span></div><div class="gatebox ${statusClass(x.state)}"><b>${x.state}</b><span>${x.gate?.reason||''}</span></div><div class="mini-stats"><div><span>Precursor</span><b>${val(x.precursorScore)}</b></div><div><span>Continuation</span><b>${val(x.continuationScore)}</b></div><div><span>Tradability</span><b>${val(x.tradabilityScore)}</b></div><div><span>Risk</span><b>${val(x.riskScore)}</b></div></div><div class="section-title">Model evidence</div><div class="evidence"><div class="evidence-item">${x.modelEvidence||x.summary||'—'}</div>${flagHtml}</div><div class="kv"><div class="card"><b>حالة التنفيذ</b><span>${execution}. ${x.executionNote||''}</span></div><div class="card"><b>Data quality</b><span>${val(x.dataQualityScore)}/100 • ${x.sourceEvidence?.provider||state.source}</span></div></div>`}
$('#filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;render()}};$('#refreshBtn').onclick=load;$('#demoBtn').textContent='مصدر السوق';$('#demoBtn').onclick=load;$('#connectBtn').onclick=()=>{};$('#feedUrl').placeholder='Derived signal feed is managed automatically';$('#feedUrl').disabled=true;$('#connectBtn').disabled=true;load();setInterval(load,60000);
