import{marketRegime}from'./core.js';
const SIGNAL_FEED='../tag/data/tagit-view.json';
const $=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2});
const pct=n=>n===null||n===undefined||!Number.isFinite(+n)?'—':`${+n>=0?'+':''}${fmt(n)}%`,val=v=>v===null||v===undefined||!Number.isFinite(+v)?'—':fmt(v);
const active=s=>['pre-market','regular','after-hours'].includes(String(s||'').toLowerCase());
const phaseLabels={ANOMALY:'Anomaly',IGNITION:'Ignition',ACCELERATION:'Acceleration',BREAKOUT:'Breakout',EXPANSION:'Expansion',EXHAUSTION:'Exhaustion',FAILED:'Failed'};
let state={items:[],session:'loading',asOf:null,sourceHealthy:false,filter:'ALL',selected:null,market:{},mode:'loading',source:'TAGit'};
async function json(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()}
function marketFromSignal(s){return{spyChangePct:s.market?.spy?.changePct??null,qqqChangePct:s.market?.qqq?.changePct??null,iwmChangePct:s.market?.iwm?.changePct??null,vixChangePct:null,breadthPct:null}}
function fromDerived(sig){return{items:sig.items||[],session:sig.session||'unknown',asOf:sig.updatedAt,sourceHealthy:Boolean(sig.sourceHealthy),market:marketFromSignal(sig),mode:'derived',source:sig.source||'TAGit derived signals'}}
async function load(){try{apply(fromDerived(await json(SIGNAL_FEED)))}catch(e){console.error(e);apply({items:[],session:'unavailable',asOf:new Date().toISOString(),sourceHealthy:false,market:{},mode:'unavailable',source:'Unavailable'})}}
function apply(x){Object.assign(state,x);state.selected=state.items[0]?.symbol||null;document.body.dataset.session=String(state.session||'unknown').toLowerCase();document.body.dataset.feedState=state.sourceHealthy&&active(state.session)?'fresh':'stale';render()}
function statusClass(s){return['WATCH','DISCOVER','OBSERVE','CAUTION','REJECT','BLOCKED','CLOSED'].includes(s)?s:'OBSERVE'}
function render(){const visible=state.filter==='ALL'?state.items:state.items.filter(x=>x.phase===state.filter);$('#rows').innerHTML=visible.map(x=>`<tr data-symbol="${x.symbol}"><td><span class="ticker">${x.symbol}</span></td><td><span class="stage ${x.phase}">${phaseLabels[x.phase]||x.phase||'—'}</span></td><td><span class="score">${val(x.score)}</span></td><td><b>${val(x.actionability)}</b></td><td><span class="gate ${statusClass(x.state)}">${x.state}</span></td><td>${x.price==null?'—':'$'+fmt(x.price)}</td><td class="${(x.changePct??0)>=0?'pos':'neg'}">${pct(x.changePct)}</td><td>${x.rvol==null?(x.featureFlags?.rvol||'—'):fmt(x.rvol)+'x'}</td><td>${x.floatRotation==null?(x.featureFlags?.float||'—'):fmt(x.floatRotation)+'x'}</td><td class="signal">${x.modelEvidence||'—'}</td></tr>`).join('')||'<tr><td colspan="10">لا توجد إشارات متاحة.</td></tr>';
 const watch=state.items.filter(x=>x.state==='WATCH').length,discover=state.items.filter(x=>x.state==='DISCOVER').length;$('#metricCandidates').textContent=watch;$('#metricDiscover').textContent=discover;$('#metricAcceleration').textContent=state.items.filter(x=>x.phase==='ACCELERATION').length;$('#metricRisk').textContent=state.items.filter(x=>['CAUTION','REJECT','BLOCKED'].includes(x.state)||(x.riskScore??0)>=60).length;const reg=marketRegime(state.market||{});$('#regimeText').textContent=reg.label;$('#regimeScore').textContent=reg.score;$('#sessionText').textContent=String(state.session||'unknown').toUpperCase();$('#asOfText').textContent=state.asOf?new Date(state.asOf).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';$('#modePill').className=`pill ${state.sourceHealthy&&active(state.session)?'live':'demo'}`;$('#modeText').textContent=state.mode==='derived'?(state.sourceHealthy?'PERSONAL DERIVED FEED • FRESH':state.session==='closed'?'LAST DERIVED SNAPSHOT':'DERIVED SIGNALS • BLOCKED'):'DATA UNAVAILABLE';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter));document.querySelectorAll('tr[data-symbol]').forEach(r=>r.onclick=()=>{state.selected=r.dataset.symbol;renderDetail()});renderDetail()}
function renderDetail(){const x=state.items.find(i=>i.symbol===state.selected);if(!x){$('#detail').className='detail empty';$('#detail').textContent='لا توجد بطاقة متاحة.';return}const flags=x.featureFlags||{},flagHtml=Object.entries(flags).map(([k,v])=>`<div class="evidence-item"><b>${k}</b> • ${v}</div>`).join('');const c=x.catalystShadow||{},cat=c.type&&c.type!=='NONE'?`${c.type} • ${c.polarity||'UNKNOWN'} • materiality ${val((c.materiality??0)*100)}/100`:'No classified catalyst';const execution=x.executionVerified?'EXECUTION VERIFIED':'EXECUTION UNVERIFIED';$('#detail').className='detail';$('#detail').innerHTML=`<div class="decision-top"><div><h2>${x.symbol}</h2><span class="stage ${x.phase}">${phaseLabels[x.phase]||x.phase||'—'}</span></div><div class="bigscore"><b>${val(x.actionability)}</b><span>Actionability</span></div></div><div class="price-line"><span class="price">${x.price==null?'—':'$'+fmt(x.price)}</span><span class="${(x.changePct??0)>=0?'pos':'neg'}">${pct(x.changePct)}</span></div><div class="gatebox ${statusClass(x.state)}"><b>${x.state}</b><span>${x.executionNote||''}</span></div><div class="mini-stats"><div><span>Precursor</span><b>${val(x.precursorScore)}</b></div><div><span>Continuation</span><b>${val(x.continuationScore)}</b></div><div><span>Tradability</span><b>${val(x.tradabilityScore)}</b></div><div><span>Risk</span><b>${val(x.riskScore)}</b></div></div><div class="section-title">Catalyst shadow</div><div class="evidence"><div class="evidence-item">${cat}</div></div><div class="section-title">Model evidence</div><div class="evidence"><div class="evidence-item">${x.modelEvidence||'—'}</div>${flagHtml}</div><div class="kv"><div class="card"><b>حالة التنفيذ</b><span>${execution}. ${x.executionNote||''}</span></div><div class="card"><b>Data quality</b><span>${val(x.dataQualityScore)}/100 • ${x.sourceEvidence?.provider||state.source}</span></div></div>`}
$('#filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;render()}};$('#refreshBtn').onclick=load;$('#demoBtn').textContent='مصدر السوق';$('#demoBtn').onclick=load;$('#connectBtn').onclick=()=>{};$('#feedUrl').placeholder='Personal derived feed is managed automatically';$('#feedUrl').disabled=true;$('#connectBtn').disabled=true;load();setInterval(load,60000);
