import{marketRegime}from'./core.js';
const SIGNAL_FEED='../tag/data/tagit-view.json';
const $=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2});
const pct=n=>n===null||n===undefined||!Number.isFinite(+n)?'—':`${+n>=0?'+':''}${fmt(n)}%`,val=v=>v===null||v===undefined||!Number.isFinite(+v)?'—':fmt(v);
const active=s=>['pre-market','regular','after-hours'].includes(String(s||'').toLowerCase());
const phaseLabels={ANOMALY:'Anomaly',IGNITION:'Ignition',ACCELERATION:'Acceleration',BREAKOUT:'Breakout',EXPANSION:'Expansion',EXHAUSTION:'Exhaustion',FAILED:'Failed'};
let state={items:[],session:'loading',asOf:null,sourceHealthy:false,filter:'ALL',selected:null,market:{},mode:'loading',source:'TAGit',v41Status:'DEGRADED',v41Counts:{},researchVersion:'TAGit v4.9',researchStatus:'UNKNOWN',champion:'TAGit-v0.6',governanceDecision:'UNKNOWN'};
async function json(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()}
function marketFromSignal(s){return{spyChangePct:s.market?.spy?.changePct??null,qqqChangePct:s.market?.qqq?.changePct??null,iwmChangePct:s.market?.iwm?.changePct??null,vixChangePct:null,breadthPct:null}}
function fromDerived(sig){return{items:sig.items||[],session:sig.session||'unknown',asOf:sig.updatedAt,sourceHealthy:Boolean(sig.sourceHealthy),market:marketFromSignal(sig),mode:'derived',source:sig.source||'TAGit derived signals',v41Status:sig.v41Status||'DEGRADED',v41Counts:sig.v41Counts||{},researchVersion:sig.researchVersion||'TAGit v4.9',researchStatus:sig.researchStatus||'UNKNOWN',champion:sig.champion||'TAGit-v0.6',governanceDecision:sig.governanceDecision||'UNKNOWN'}}
async function load(){try{apply(fromDerived(await json(SIGNAL_FEED)))}catch(e){console.error(e);apply({items:[],session:'unavailable',asOf:new Date().toISOString(),sourceHealthy:false,market:{},mode:'unavailable',source:'Unavailable',v41Status:'DEGRADED',v41Counts:{},researchVersion:'TAGit v4.9',researchStatus:'UNAVAILABLE',champion:'TAGit-v0.6',governanceDecision:'UNKNOWN'})}}
function apply(x){Object.assign(state,x);state.selected=state.items.find(i=>i.v41Shadow?.v41State==='V41_ALERT')?.symbol||state.items[0]?.symbol||null;document.body.dataset.session=String(state.session||'unknown').toLowerCase();document.body.dataset.feedState=state.sourceHealthy&&active(state.session)?'fresh':'stale';render()}
function statusClass(s){return['WATCH','DISCOVER','OBSERVE','CAUTION','REJECT','BLOCKED','CLOSED'].includes(s)?s:'OBSERVE'}
function v41State(x){return x.v41Shadow?.v41State||'LEGACY'}
function conviction(x){return x.v41Shadow?.eventConviction??x.actionability??null}
function reason(x){return x.v41Shadow?.reason||x.modelEvidence||'—'}
function catalystLabel(x){const c=x.v41Shadow?.catalystContext||x.catalystShadow||{};const t=c.catalystType||c.type;return t&&t!=='NONE'?t:'—'}
function render(){
 const visible=state.filter==='ALL'?state.items:state.items.filter(x=>x.phase===state.filter);
 $('#rows').innerHTML=visible.map(x=>{const z=x.v41Shadow||{},vs=v41State(x),gate=vs==='V41_ALERT'?'WATCH':vs==='V41_DISCOVER'?'DISCOVER':x.state;return `<tr data-symbol="${x.symbol}"><td><span class="ticker">${x.symbol}</span></td><td><span class="gate ${statusClass(gate)}">${vs}</span></td><td><b>#${z.rank??'—'}</b></td><td><span class="score">${val(z.rankScorePct??x.score)}</span></td><td><b>${val(conviction(x))}</b></td><td>${val(z.persistenceScore)}</td><td>${val(z.continuationScore)}</td><td>${catalystLabel(x)}</td><td>${x.price==null?'—':'$'+fmt(x.price)}</td><td class="${(x.changePct??0)>=0?'pos':'neg'}">${pct(x.changePct)}</td><td class="signal">${reason(x)}</td></tr>`}).join('')||'<tr><td colspan="11">لا توجد إشارات متاحة.</td></tr>';
 const alerts=state.items.filter(x=>v41State(x)==='V41_ALERT').length,discover=state.items.filter(x=>v41State(x)==='V41_DISCOVER').length;
 $('#metricCandidates').textContent=alerts;$('#metricDiscover').textContent=discover;$('#metricAcceleration').textContent=state.items.filter(x=>x.v41Shadow?.progressionSeen).length;$('#metricRisk').textContent=state.items.filter(x=>(x.v41Shadow?.riskContext||[]).length).length;
 const reg=marketRegime(state.market||{});$('#regimeText').textContent=reg.label;$('#regimeScore').textContent=reg.score;$('#sessionText').textContent=String(state.session||'unknown').toUpperCase();$('#asOfText').textContent=state.asOf?new Date(state.asOf).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
 const research=$('#researchText'),champion=$('#championText');if(research)research.textContent=`${String(state.researchVersion||'TAGit v4.9').replace('TAGit ','')} • ${state.researchStatus||'UNKNOWN'}`;if(champion)champion.textContent=String(state.champion||'TAGit-v0.6').replace('TAGit-','');
 $('#modePill').className=`pill ${state.sourceHealthy&&active(state.session)?'live':'demo'}`;$('#modeText').textContent=state.session==='closed'?'MARKET CLOSED • UI 4.1 READY':state.v41Status==='PASS'?'UI 4.1 SHADOW • FRESH':'UI 4.1 SHADOW • DEGRADED';
 document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter));document.querySelectorAll('tr[data-symbol]').forEach(r=>r.onclick=()=>{state.selected=r.dataset.symbol;renderDetail()});renderDetail();
}
function renderDetail(){
 const x=state.items.find(i=>i.symbol===state.selected);if(!x){$('#detail').className='detail empty';$('#detail').textContent='لا توجد بطاقة متاحة.';return}
 const z=x.v41Shadow||{},c=z.catalystContext||x.catalystShadow||{},risks=z.riskContext||[];const cat=(c.catalystType||c.type)&&((c.catalystType||c.type)!=='NONE')?`${c.catalystType||c.type} • quality ${val(z.catalystQuality)}/100`:'No classified material catalyst';
 const execution=x.executionVerified?'EXECUTION VERIFIED':'EXECUTION UNVERIFIED';
 $('#detail').className='detail';$('#detail').innerHTML=`<div class="decision-top"><div><h2>${x.symbol}</h2><span class="gate ${statusClass(z.v41State==='V41_ALERT'?'WATCH':z.v41State==='V41_DISCOVER'?'DISCOVER':'OBSERVE')}">${z.v41State||x.state||'—'}</span></div><div class="bigscore"><b>${val(conviction(x))}</b><span>Event Conviction</span></div></div><div class="price-line"><span class="price">${x.price==null?'—':'$'+fmt(x.price)}</span><span class="${(x.changePct??0)>=0?'pos':'neg'}">${pct(x.changePct)}</span></div><div class="gatebox ${statusClass(z.v41State==='V41_ALERT'?'WATCH':'OBSERVE')}"><b>${z.v41State||'LEGACY'}</b><span>${reason(x)}</span></div><div class="mini-stats"><div><span>Rank</span><b>#${z.rank??'—'}</b></div><div><span>Rank score</span><b>${val(z.rankScorePct)}</b></div><div><span>Persistence</span><b>${val(z.persistenceScore)}</b></div><div><span>Continuation</span><b>${val(z.continuationScore)}</b></div></div><div class="section-title">Catalyst context</div><div class="evidence"><div class="evidence-item">${cat}</div></div><div class="section-title">Persistence & trajectory</div><div class="evidence"><div class="evidence-item">Selected streak: ${z.selectedStreak??0} • Progression: ${z.progressionSeen?'YES':'NO'} • 5m ${pct(z.momentum5mPct)} • 10m ${pct(z.momentum10mPct)}</div></div><div class="section-title">Risk context</div><div class="evidence"><div class="evidence-item">${risks.length?risks.join(' • '):'No tagged structural risk in the derived view'}</div></div><div class="kv"><div class="card"><b>حالة التنفيذ</b><span>${execution}. v4.1 is a shadow discovery layer, not a trade instruction.</span></div><div class="card"><b>Model governance</b><span>${state.governanceDecision||'UNKNOWN'} • Champion ${state.champion||'TAGit-v0.6'} • Research ${state.researchVersion||'TAGit v4.9'} ${state.researchStatus||''}.</span></div><div class="card"><b>Score meaning</b><span>${z.scoreMeaning||'Relative research score; not calibrated success probability.'}</span></div></div>`;
}
$('#filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;render()}};$('#refreshBtn').onclick=load;$('#demoBtn').textContent='تحديث السوق';$('#demoBtn').onclick=load;$('#connectBtn').onclick=()=>{};$('#feedUrl').placeholder='Personal derived feed is managed automatically';$('#feedUrl').disabled=true;$('#connectBtn').disabled=true;load();setInterval(load,60000);