import{enrich,marketRegime}from'./core.js';

const RICH_FEED='../tag/data/finviz-rich.json';
const BASE_FEED='../tag/data/finviz.json';
const $=s=>document.querySelector(s);
const fmt=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2});
const pct=n=>`${Number(n)>=0?'+':''}${fmt(n)}%`;
const mf=(v,s='')=>(v===null||v===undefined||!Number.isFinite(Number(v)))?'—':`${fmt(v)}${s}`;
const plain=v=>{if(v===null||v===undefined||v==='')return null;const x=parseFloat(String(v).replace(/[$,%x,]/g,''));return Number.isFinite(x)?x:null};
const millions=v=>{if(v===null||v===undefined||v==='')return null;const s=String(v).trim().toUpperCase().replace(/,/g,'');const x=parseFloat(s);if(!Number.isFinite(x))return null;if(s.endsWith('B'))return x*1000;if(s.endsWith('M'))return x;if(s.endsWith('K'))return x/1000;return x>1e5?x/1e6:x};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const labels={ANOMALY:'Anomaly',IGNITION:'Ignition',ACCELERATION:'Acceleration',BREAKOUT:'Breakout',EXPANSION:'Expansion',EXHAUSTION:'Exhaustion',FAILED:'Failed'};
const activeSession=s=>['pre-market','regular','after-hours'].includes(String(s||'').toLowerCase());
let state={feed:{asOf:new Date().toISOString(),session:'loading',market:{},symbols:[]},items:[],filter:'ALL',selected:null,feedState:'loading',url:RICH_FEED};

function sourceGate(payload,session,ageMin){
  if(payload.source==='Finviz Elite Rich'&&payload.richHealthStatus!=='PASS')return{status:'REJECT',reason:'Rich feed data contract degraded'};
  const extended=['pre-market','after-hours'].includes(session),integrity=String(payload.extendedHoursFieldIntegrity||'');
  if(activeSession(session)&&ageMin>20)return{status:'REJECT',reason:`بيانات المصدر متأخرة ${Math.round(ageMin)} دقيقة أثناء الجلسة`};
  if(String(payload.cadenceStatus)==='GAP_ERROR'||String(payload.bucketContinuityStatus)==='BUCKET_GAP_ERROR')return{status:'REJECT',reason:'فجوة في تسلسل snapshots'};
  if(extended&&integrity!=='CROSS_SNAPSHOT_FIELDS_MOVING')return{status:'REJECT',reason:'حقول الجلسة الممتدة غير مؤكدة الحركة'};
  if(session==='closed')return{status:'OBSERVE',reason:'السوق مغلق؛ آخر لقطة وليست إشارة دخول آنية'};
  return null;
}
function marketFromPayload(p){const m=p.marketBenchmarks||{},spy=m.SPY||{},qqq=m.QQQ||{},iwm=m.IWM||{};return{spyChangePct:plain(spy.changePct),qqqChangePct:plain(qqq.changePct),iwmChangePct:plain(iwm.changePct),vixChangePct:null,breadthPct:null};}
function normalizeFinviz(p){
  const rows=Array.isArray(p.rows)?p.rows:(Array.isArray(p.data)?p.data:[]),asOf=p.updatedAt||p.asOf||p.snapshotTimestampUTC||new Date().toISOString();
  const ts=new Date(asOf).getTime(),ageMin=Number.isFinite(ts)?Math.max(0,(Date.now()-ts)/60000):9999,session=String(p.session||'unknown').toLowerCase(),override=sourceGate(p,session,ageMin),isRich=p.source==='Finviz Elite Rich';
  const symbols=rows.slice(0,550).map(r=>{
    const t=r._tagit||{},signals=Array.isArray(r._signals)?r._signals:[],ch=plain(t.dayChangePct??r.Change)??0,volume=plain(t.volume??r.Volume)??0,price=plain(t.price??r.Price)??0;
    const rvol=plain(t.relativeVolume??r['Relative Volume']??r['Rel Volume']),floatM=t.floatShares!=null?Number(t.floatShares)/1e6:millions(r['Shares Float']??r['Float']??r['Shs Float']);
    const momentum=t.momentumPct||{},consistency=plain(t.momentumConsistency),shortRate=plain(t.shortMomentumRatePctPerMin),priceAccel=plain(t.priceAccelerationPctPerMin),dollarVolume=plain(t.dollarVolume),avgDollarVolume=plain(t.averageDollarVolume),trades=plain(t.trades),atrPct=plain(t.atrPct),gapPct=plain(t.gapPct),shortFloatPct=plain(t.shortFloatPct),sma20Pct=plain(t.sma20Pct),sma50Pct=plain(t.sma50Pct),perfWeekPct=plain(t.perfWeekPct),lateExtensionRiskRaw=plain(t.lateExtensionRiskRaw),floatRotation=plain(t.floatRotation),persistenceSlope=plain(r._persistenceSlopePctPts),persistencePoints=Array.isArray(r._persistencePoints)?r._persistencePoints.length:null;
    const cats=Array.isArray(t.catalystSignals)?t.catalystSignals:[];let catalystStrength=null,catalystFreshnessMin=null;if(cats.some(x=>String(x).includes('earnings'))){catalystStrength=.72;catalystFreshnessMin=60;}else if(cats.some(x=>String(x).includes('majornews'))){catalystStrength=.60;catalystFreshnessMin=90;}
    const shortPositive=[momentum['1'],momentum['2'],momentum['3'],momentum['5'],momentum['10']].filter(v=>v!==null&&v!==undefined).filter(v=>Number(v)>0).length;
    const breakoutQuality=isRich?clamp((consistency??0)*.42+Math.min(Math.max(Number(momentum['10']||0),0),8)/20+Math.min(Math.max(rvol||0,0),12)/40+(signals.some(x=>String(x).includes('topgainers'))?.12:0),0,.92):null;
    let quality=isRich?.88:.48;if(rvol===null)quality-=.10;if(dollarVolume===null)quality-=.08;if(momentum['1']==null||momentum['5']==null)quality-=.18;if(floatM===null)quality-=.03;if(override?.status==='REJECT')quality=Math.min(quality,.54);
    const evidence=[`${p.source||'Finviz Elite'} • ${signals.map(x=>String(x).replace('ta_','')).join(' + ')||'scan'}`,`Snapshot ${Math.round(ageMin)}m • ${session}`,rvol!==null?`RVOL ${rvol.toFixed(2)}x`:'RVOL —',isRich?`Momentum + windows ${shortPositive}/5 • 5m ${mf(momentum['5'],'%')} • 10m ${mf(momentum['10'],'%')}`:'Rich momentum unavailable',floatM!==null?`Float ${floatM.toFixed(2)}M`:'Float —',dollarVolume!==null?`Dollar volume $${fmt(dollarVolume)}`:'Dollar volume —'];
    return{symbol:String(r.Ticker||r.Symbol||'').trim().toUpperCase(),price,changePct:ch,volume,rvol,floatM,floatRotation,spreadPct:null,breakoutQuality,vwapPosition:null,distanceToBreakoutPct:null,priceAcceleration:priceAccel,priceAccelerationPctPerMin:priceAccel,momentumPct:momentum,momentumConsistency:consistency,shortMomentumRatePctPerMin:shortRate,dollarVolume,averageDollarVolume:avgDollarVolume,trades,atrPct,gapPct,shortFloatPct,sma20Pct,sma50Pct,perfWeekPct,lateExtensionRiskRaw,persistenceSlope,persistencePoints,catalystStrength,catalystFreshnessMin,dilutionRisk:t.recentDilutionFiling?.80:.28,haltRisk:ch>55?.34:ch>35?.18:.07,recentDilutionFiling:Boolean(t.recentDilutionFiling),dataQuality:clamp(quality,0,1),gateOverride:override,evidence,confirm:'استمرار إيجابي في 1m/5m/10m مع RVOL وسيولة فعلية وعدم ارتفاع مخاطر الامتداد',invalidate:'انعكاس الزخم القصير، ضعف السيولة، فجوة بيانات، أو تحول الحركة إلى Expansion/Exhaustion'};
  }).filter(x=>x.symbol&&x.price>0);
  let feedState='snapshot';if(activeSession(session)&&!override)feedState='fresh';else if(activeSession(session)&&override?.status==='REJECT')feedState='blocked';else if(session==='closed')feedState='closed';
  return{asOf,session,source:p.source||'Finviz Elite',ageMin,feedState,integrity:{richHealthStatus:p.richHealthStatus,cadenceStatus:p.cadenceStatus,bucketContinuityStatus:p.bucketContinuityStatus,extendedHoursFieldIntegrity:p.extendedHoursFieldIntegrity,independentSourceCount:p.independentSourceCount,dataIntegrityState:p.dataIntegrityState},market:marketFromPayload(p),symbols};
}
function process(feed,{feedState='fresh',url=RICH_FEED}={}){state.feed=feed;state.items=enrich(feed.symbols||[],feed.market||{});state.feedState=feedState;state.url=url;state.selected=state.items[0]?.symbol||null;document.body.dataset.feedState=feedState;document.body.dataset.session=String(feed.session||'unknown').toLowerCase();render();}
function render(){const items=state.filter==='ALL'?state.items:state.items.filter(x=>x.phase===state.filter);$('#rows').innerHTML=items.map(x=>`<tr data-symbol="${x.symbol}"><td><span class="ticker">${x.symbol}</span></td><td><span class="stage ${x.phase}">${labels[x.phase]}</span></td><td><span class="score">${x.score}</span></td><td><b>${x.actionability}</b></td><td><span class="gate ${x.gate.status}">${x.gate.status}</span></td><td>$${fmt(x.price)}</td><td class="${x.changePct>=0?'pos':'neg'}">${pct(x.changePct)}</td><td>${mf(x.rvol,'x')}</td><td>${mf(x.features.floatRotation,'x')}</td><td class="signal">${x.summary}</td></tr>`).join('')||'<tr><td colspan="10">لا توجد نتائج قابلة للعرض من المصدر الحالي.</td></tr>';$('#metricCandidates').textContent=state.items.filter(x=>x.gate.status==='WATCH').length;$('#metricIgnition').textContent=state.items.filter(x=>x.phase==='IGNITION').length;$('#metricAcceleration').textContent=state.items.filter(x=>x.phase==='ACCELERATION').length;$('#metricRisk').textContent=state.items.filter(x=>['EXHAUSTION','FAILED'].includes(x.phase)||x.components.risk>=60||x.gate.status==='REJECT').length;const r=marketRegime(state.feed.market||{});$('#regimeText').textContent=r.label;$('#regimeScore').textContent=r.score;$('#sessionText').textContent=(state.feed.session||'unknown').toUpperCase();$('#asOfText').textContent=state.feed.asOf?new Date(state.feed.asOf).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';const mode={fresh:'FINVIZ ELITE • RICH',closed:'LAST MARKET SNAPSHOT',blocked:'SOURCE QUALITY BLOCK',snapshot:'MARKET SNAPSHOT',unavailable:'DATA UNAVAILABLE'}[state.feedState]||'MARKET SNAPSHOT';$('#modePill').className=`pill ${state.feedState==='fresh'?'live':'demo'}`;$('#modeText').textContent=mode;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter));document.querySelectorAll('tr[data-symbol]').forEach(r=>r.onclick=()=>{state.selected=r.dataset.symbol;renderDetail()});renderDetail();}
function renderDetail(){const x=state.items.find(i=>i.symbol===state.selected);if(!x){$('#detail').className='detail empty';$('#detail').textContent='لا توجد بطاقة متاحة.';return}const c=x.components,f=x.features,e=(x.evidence||[]).map(v=>`<div class="evidence-item">${v}</div>`).join('');const m=[['Acceleration',c.acceleration],['Participation',c.participation],['Structure',c.structure],['Liquidity',c.liquidity],['Data quality',c.quality],['Risk',c.risk]].map(([k,v])=>`<div><div class="meter-label"><span>${k}</span><b>${v}</b></div><div class="bar"><div class="fill" style="width:${v}%"></div></div></div>`).join('');$('#detail').className='detail';$('#detail').innerHTML=`<div class="decision-top"><div><h2>${x.symbol}</h2><span class="stage ${x.phase}">${labels[x.phase]}</span></div><div class="bigscore"><b>${x.actionability}</b><span>Actionability</span></div></div><div class="price-line"><span class="price">$${fmt(x.price)}</span><span class="${x.changePct>=0?'pos':'neg'}">${pct(x.changePct)}</span></div><div class="gatebox ${x.gate.status}"><b>${x.gate.status}</b><span>${x.gate.reason}</span></div><div class="mini-stats"><div><span>Continuation</span><b>${x.continuation.score}</b></div><div><span>Tradability</span><b>${x.tradability.score}</b></div><div><span>RVOL</span><b>${mf(x.rvol,'x')}</b></div><div><span>Dollar volume</span><b>${f.dollarVolume==null?'—':'$'+fmt(f.dollarVolume)}</b></div></div><div class="analog-head"><b>Forward probability</b><span class="source modelled">MODELLED ESTIMATE</span></div><div class="prob-grid"><div><b>${x.analogs.p5_30m}%</b><span>+5% / 30m</span></div><div><b>${x.analogs.p10_1h}%</b><span>+10% / 1h</span></div><div><b>${x.analogs.p20_day}%</b><span>+20% / day</span></div></div><div class="section-title">Evidence</div><div class="evidence">${e}</div><div class="kv"><div class="card"><b>يؤكد الفرضية</b><span>${x.confirm}</span></div><div class="card"><b>يبطل الفرضية</b><span>${x.invalidate}</span></div></div><div class="meters">${m}</div>`;}
async function fetchJson(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function loadMarket(){try{const raw=await fetchJson(RICH_FEED);if(raw.richHealthStatus!=='PASS')throw new Error('Rich feed degraded');const feed=normalizeFinviz(raw);if(!feed.symbols.length)throw new Error('Empty rich feed');process(feed,{feedState:feed.feedState,url:RICH_FEED});return;}catch(e){console.warn('TAGit rich feed fallback',e);try{const raw=await fetchJson(BASE_FEED),feed=normalizeFinviz(raw);if(!feed.symbols.length)throw new Error('Empty base feed');process(feed,{feedState:feed.feedState,url:BASE_FEED});return;}catch(e2){console.error('TAGit market feed failed',e2);process({asOf:new Date().toISOString(),session:'unavailable',market:{},symbols:[]},{feedState:'unavailable',url:BASE_FEED});}}}
async function loadCustom(url){if(!url)return;try{const d=await fetchJson(url);if(!Array.isArray(d.symbols))throw new Error('Invalid TAGit feed format');process(d,{feedState:'fresh',url});localStorage.setItem('tagitFeedUrl',url);}catch(e){alert(`تعذر ربط المصدر: ${e.message}`)}}
$('#filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){state.filter=b.dataset.filter;render()}};$('#connectBtn').onclick=()=>loadCustom($('#feedUrl').value.trim());$('#demoBtn').textContent='مصدر السوق';$('#demoBtn').onclick=loadMarket;$('#refreshBtn').onclick=()=>state.url===RICH_FEED||state.url===BASE_FEED?loadMarket():loadCustom(state.url);$('#feedUrl').placeholder='اختياري: TAGit-compatible JSON endpoint';const saved=localStorage.getItem('tagitFeedUrl');if(saved)$('#feedUrl').value=saved;loadMarket();setInterval(loadMarket,60000);
