import{execFileSync}from'node:child_process';
import fs from'node:fs';
import{enrich}from'./core.js';

const PATH='tag/data/discovery-fast.json';
const num=v=>{if(v===null||v===undefined||v==='')return null;let s=String(v).replace(/[$,%x,]/gi,'').replace(/,/g,'').trim().toUpperCase(),m=1;if(s.endsWith('K')){m=1e3;s=s.slice(0,-1)}else if(s.endsWith('M')){m=1e6;s=s.slice(0,-1)}else if(s.endsWith('B')){m=1e9;s=s.slice(0,-1)}const n=Number(s);return Number.isFinite(n)?n*m:null};
const avg=v=>{if(v===null||v===undefined||v==='')return null;const s=String(v).trim().toUpperCase(),n=num(v);return n===null?null:/[KMB]$/.test(s)?n:n*1000};
const finite=v=>v!==null&&v!==undefined&&Number.isFinite(+v);
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
const logScore=(v,cap)=>finite(v)&&v>0?clamp(Math.log1p(v)/Math.log1p(cap)*100):0;
const revisions=execFileSync('git',['log','--format=%H','--',PATH],{encoding:'utf8',maxBuffer:20e6}).trim().split(/\s+/).filter(Boolean).reverse();
const snapshots=[];const seen=new Set();let parseFailures=0;
for(const sha of revisions){try{const p=JSON.parse(execFileSync('git',['show',`${sha}:${PATH}`],{encoding:'utf8',maxBuffer:20e6})),iso=p.snapshotTimestampUTC||p.updatedAt;if(!iso||seen.has(iso))continue;seen.add(iso);snapshots.push({sha,ts:new Date(iso).getTime(),iso,session:p.session||'unknown',rows:p.rows||p.data||[]});}catch{parseFailures++}}
snapshots.sort((a,b)=>a.ts-b.ts);
const byKey=new Map(),bySnap=new Map();
for(const snap of snapshots){const sid=snap.iso;bySnap.set(sid,[]);for(const r of snap.rows){const ticker=String(r.Ticker||r.Symbol||'').trim().toUpperCase(),price=num(r.Price);if(!ticker||!price||price<=0)continue;const day=new Date(snap.ts).toISOString().slice(0,10),key=`${ticker}|${day}`,o={ticker,key,day,ts:snap.ts,iso:snap.iso,session:snap.session,price,volume:num(r.Volume)??0,change:num(r.Change)??0,rvol:num(r['Relative Volume']??r['Rel Volume']),avgVolume:avg(r['Average Volume']),perfWeek:num(r['Performance (Week)']),gap:num(r.Gap),sma20:num(r['20-Day Simple Moving Average']),floatShares:num(r['Shares Float']),row:r};if(!byKey.has(key))byKey.set(key,[]);byKey.get(key).push(o);bySnap.get(sid).push(o)}}
for(const a of byKey.values())a.sort((x,y)=>x.ts-y.ts);
const ret=(a,b)=>((a/b)-1)*100;
function prior(arr,i,target,min=.3,max=2.3){let z=null,e=1e9;for(let j=i-1;j>=0;j--){const d=(arr[i].ts-arr[j].ts)/60000;if(d>target*max)break;if(d<target*min)continue;if(Math.abs(d-target)<e){z=arr[j];e=Math.abs(d-target)}}return z}
function forward(arr,i,maxMin){const c=arr[i],x=[];for(let j=i+1;j<arr.length;j++){const d=(arr[j].ts-c.ts)/60000;if(d>maxMin)break;x.push(ret(arr[j].price,c.price))}return x}
const obs=[];
for(const [key,a] of byKey){for(let i=0;i<a.length;i++){const o=a[i],p5=prior(a,i,5),p10=prior(a,i,10),p30=prior(a,i,30),p60=prior(a,i,60),prev=i?a[i-1]:null;const m5=p5?ret(o.price,p5.price):null,m10=p10?ret(o.price,p10.price):null,m30=p30?ret(o.price,p30.price):null,m60=p60?ret(o.price,p60.price):null;let shortRate=null,vv=null,dt=null;if(prev){dt=(o.ts-prev.ts)/60000;if(dt>0&&dt<=30){shortRate=ret(o.price,prev.price)/dt;if(o.avgVolume){const delta=o.volume-prev.volume,expected=o.avgVolume/390*dt;if(delta>=0&&expected>0)vv=delta/expected}}}const dollar=o.price*o.volume,volumeVsAvg=o.avgVolume?o.volume/o.avgVolume:null;const f30=forward(a,i,30),f60=forward(a,i,60),fday=forward(a,i,720);const target=finite(f60.length?Math.max(...f60):null)&&Math.max(...f60)>=10;const turn=(finite(shortRate)?clamp(50+shortRate*180):50);const shape=finite(m5)&&finite(m30)?clamp(50+(m5-m30/6)*12):50;const earlyFit=o.change<10&&o.change>=-20?100:o.change<20?35:0;const liquidity=clamp(logScore(dollar,5e6));const precursorScore=Math.round(clamp(logScore(o.rvol,12)*.28+logScore(vv,8)*.30+turn*.15+shape*.12+earlyFit*.10+liquidity*.05));const symbol={symbol:o.ticker,price:o.price,changePct:o.change,volume:o.volume,rvol:o.rvol,floatM:o.floatShares?o.floatShares/1e6:null,floatRotation:o.floatShares?o.volume/o.floatShares:null,spreadPct:null,momentumPct:{'1':null,'5':m5,'10':m10,'30':m30,'60':m60},momentumConsistency:[m5,m10,m30].filter(finite).length?[m5,m10,m30].filter(finite).filter(x=>x>0).length/[m5,m10,m30].filter(finite).length:null,shortMomentumRatePctPerMin:shortRate,priceAccelerationPctPerMin:shortRate,dollarVolume:dollar,averageDollarVolume:o.avgVolume?o.price*o.avgVolume:null,trades:null,atrPct:null,gapPct:o.gap,shortFloatPct:null,sma20Pct:o.sma20,perfWeekPct:o.perfWeek,lateExtensionRiskRaw:Math.max(0,o.change-22)*.45,persistenceSlope:shortRate,persistencePoints:Math.min(i+1,4),catalystStrength:null,catalystFreshnessMin:null,dilutionRisk:null,haltRisk:o.change>55?.34:o.change>35?.18:.07,recentDilutionFiling:false,dataQuality:(finite(o.rvol)&&finite(m5)&&finite(dollar))?.78:.62,breakoutQuality:null,vwapPosition:null,distanceToBreakoutPct:null};const scored=enrich([symbol],{})[0];obs.push({...o,i,m5,m10,m30,m60,shortRate,volumeVelocity:vv,volumeVsAvg,dollarVolume:dollar,precursorScore,coreGate:scored.gate.status,continuation:scored.continuation.score,tradability:scored.tradability.score,actionability:scored.actionability,phase:scored.phase,mfe30:f30.length?Math.max(...f30):null,mae30:f30.length?Math.min(...f30):null,mfe60:f60.length?Math.max(...f60):null,mae60:f60.length?Math.min(...f60):null,mfeDay:fday.length?Math.max(...fday):null,maeDay:fday.length?Math.min(...fday):null,target});}}
const eligible=obs.filter(x=>finite(x.mfe60));
// Cross-sectional DISCOVER lanes: rank precursor pressure inside each historical snapshot, then cap alerts.
const configs=[];for(const topK of [5,10,15,20,30])for(const minScore of [48,55,62,68])configs.push({topK,minScore});
function discoverSet(cfg){const out=[];for(const snap of snapshots){const xs=eligible.filter(x=>x.iso===snap.iso&&x.change<10&&x.change>=-20&&x.price>=.15&&x.precursorScore>=cfg.minScore).sort((a,b)=>b.precursorScore-a.precursorScore).slice(0,cfg.topK);out.push(...xs)}return out}
const round=v=>finite(v)?Math.round(v*100)/100:null,rate=(a,p)=>a.length?a.filter(p).length/a.length*100:null,median=a=>{const x=a.filter(finite).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
function eventFirst(a){const seen=new Set(),out=[];for(const x of [...a].sort((p,q)=>p.ts-q.ts))if(!seen.has(x.key)){seen.add(x.key);out.push(x)}return out}
function metrics(a){return{count:a.length,uniqueEvents:eventFirst(a).length,precision10_60mPct:round(rate(a,x=>x.mfe60>=10)),hit5_30mPct:round(rate(a,x=>(x.mfe30??-999)>=5)),hit20_dayPct:round(rate(a,x=>(x.mfeDay??-999)>=20)),medianMFE60Pct:round(median(a.map(x=>x.mfe60))),medianMAE60Pct:round(median(a.map(x=>x.mae60)))}}
const opportunities=new Set(eligible.filter(x=>x.change<10&&x.change>=-20&&x.mfe60>=10).map(x=>x.key));
const configResults=configs.map(cfg=>{const d=discoverSet(cfg),captured=new Set(d.filter(x=>x.mfe60>=10).map(x=>x.key));return{...cfg,...metrics(d),opportunityTickerDays:opportunities.size,capturedTickerDays:captured.size,recallTickerDayPct:round(opportunities.size?captured.size/opportunities.size*100:null)}}).sort((a,b)=>(b.recallTickerDayPct*0.55+b.precision10_60mPct*0.45)-(a.recallTickerDayPct*0.55+a.precision10_60mPct*0.45));
const chosen=configResults.find(x=>x.topK===15&&x.minScore===55)||configResults[0],discover=discoverSet(chosen);const discoverKeysByTime=new Map();for(const x of discover){if(!discoverKeysByTime.has(x.key))discoverKeysByTime.set(x.key,[]);discoverKeysByTime.get(x.key).push(x)}
// Promotion requires an earlier DISCOVER, then an actual turn/persistence confirmation. No future label enters this rule.
const promoted=[];for(const x of eligible){const ds=discoverKeysByTime.get(x.key)||[];const priorD=ds.filter(d=>d.ts<x.ts&&(x.ts-d.ts)/60000<=120).sort((a,b)=>b.ts-a.ts)[0];if(!priorD)continue;const confirm=((x.m5??-99)>=.5||(x.shortRate??-99)>=.05)&&((x.rvol??0)>=1.5)&&x.change<22&&x.tradability>=60;const persist=(x.volumeVelocity??0)>=.6||(x.m10??-99)>=1;if(confirm&&persist)promoted.push({...x,priorDiscoverTs:priorD.iso,minutesFromDiscover:round((x.ts-priorD.ts)/60000)})}
const firstPromoted=eventFirst(promoted),tp=promoted.filter(x=>x.mfe60>=10),positives=eligible.filter(x=>x.mfe60>=10);const capturedDiscoverKeys=new Set(discover.filter(x=>x.mfe60>=10).map(x=>x.key)),capturedPromotedKeys=new Set(promoted.filter(x=>x.mfe60>=10).map(x=>x.key));
const byDay={};for(const x of eligible){byDay[x.day]??={eligible:0,positives:0,discover:0,discoverTP:0,promoted:0,promotedTP:0};byDay[x.day].eligible++;if(x.mfe60>=10)byDay[x.day].positives++}for(const x of discover){byDay[x.day].discover++;if(x.mfe60>=10)byDay[x.day].discoverTP++}for(const x of promoted){byDay[x.day].promoted++;if(x.mfe60>=10)byDay[x.day].promotedTP++}
for(const d of Object.values(byDay)){d.discoverPrecisionPct=round(d.discover?d.discoverTP/d.discover*100:null);d.promotionPrecisionPct=round(d.promoted?d.promotedTP/d.promoted*100:null)}
const report={schemaVersion:1,method:'TAGIT_V06_PRECURSOR_DISCOVER_THEN_PROMOTE_WALK_FORWARD',generatedAtUTC:new Date().toISOString(),antiLeakageRules:['Historical snapshots loaded from Git revisions.','Precursor features use current/prior observations only.','DISCOVER is ranked cross-sectionally within the current snapshot only.','WATCH promotion requires an earlier DISCOVER and later causal confirmation.','Forward MFE is used only after decisions are frozen.'],coverage:{gitRevisions:revisions.length,snapshots:snapshots.length,parseFailures,eligibleObservations:eligible.length,opportunityTickerDays:opportunities.size},precursorFormula:{components:{rvol:'.28 log-scaled',volumeVelocity:'.30 log-scaled',shortTurn:'.15',shapeInflection:'.12',earlyWindow:'.10',dollarLiquidity:'.05'},volumeVelocity:'incremental shares / expected shares for elapsed minutes using Finviz Average Volume / 390'},configResults,chosenDiscoveryConfig:{topK:chosen.topK,minScore:chosen.minScore},discover:{...metrics(discover),capturedTickerDays:capturedDiscoverKeys.size,recallTickerDayPct:round(opportunities.size?capturedDiscoverKeys.size/opportunities.size*100:null)},promotion:{...metrics(promoted),firstEventMetrics:metrics(firstPromoted),truePositives:tp.length,recallObservationPct:round(positives.length?tp.length/positives.length*100:null),capturedTickerDays:capturedPromotedKeys.size,recallTickerDayPct:round(opportunities.size?capturedPromotedKeys.size/opportunities.size*100:null)},byDay,examples:{discoverWinners:[...discover].filter(x=>x.mfe60>=10).sort((a,b)=>b.mfe60-a.mfe60).slice(0,15).map(x=>({ticker:x.ticker,iso:x.iso,price:x.price,change:x.change,precursorScore:x.precursorScore,rvol:x.rvol,volumeVelocity:round(x.volumeVelocity),m5:round(x.m5),mfe60:round(x.mfe60)})),promotedWinners:[...promoted].filter(x=>x.mfe60>=10).sort((a,b)=>b.mfe60-a.mfe60).slice(0,12).map(x=>({ticker:x.ticker,iso:x.iso,price:x.price,change:x.change,precursorScore:x.precursorScore,rvol:x.rvol,volumeVelocity:round(x.volumeVelocity),m5:round(x.m5),minutesFromDiscover:x.minutesFromDiscover,mfe60:round(x.mfe60)}))},limitations:['Finviz snapshots are sampled rather than one-minute bars.','Historical rich fields such as bid/ask, catalyst direction and SEC risk are unavailable for every revision and are not fabricated.','Discovery configuration comparison is descriptive; production promotion should be judged on stability by day as well as aggregate lift.','No slippage or transaction costs.']};
fs.writeFileSync('tag/data/tagit-v06-walkforward.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({coverage:report.coverage,chosen:report.chosenDiscoveryConfig,discover:report.discover,promotion:report.promotion,byDay:report.byDay},null,2));
