import{execFileSync}from'node:child_process';
import fs from'node:fs';
import{enrich}from'./core.js';

const PATH='tag/data/discovery-fast.json';
const parseNum=v=>{if(v===null||v===undefined||v==='')return null;const s=String(v).replace(/[$,%x,]/gi,'').replace(/,/g,'').trim().toUpperCase();let m=1,t=s;if(t.endsWith('K')){m=1e3;t=t.slice(0,-1)}else if(t.endsWith('M')){m=1e6;t=t.slice(0,-1)}else if(t.endsWith('B')){m=1e9;t=t.slice(0,-1)}const n=Number(t);return Number.isFinite(n)?n*m:null};
const pct=v=>parseNum(v);
const avgShares=v=>{if(v===null||v===undefined||v==='')return null;const s=String(v).trim().toUpperCase();const n=parseNum(v);if(n===null)return null;return/[KMB]$/.test(s)?n:n*1000};
const revisions=execFileSync('git',['log','--format=%H','--',PATH],{encoding:'utf8',maxBuffer:20*1024*1024}).trim().split(/\s+/).filter(Boolean).reverse();
const snapshots=[];const seen=new Set();let parseFailures=0;
for(const sha of revisions){try{const txt=execFileSync('git',['show',`${sha}:${PATH}`],{encoding:'utf8',maxBuffer:20*1024*1024});const p=JSON.parse(txt);const ts=p.snapshotTimestampUTC||p.updatedAt;if(!ts||seen.has(ts))continue;seen.add(ts);snapshots.push({sha,ts:new Date(ts).getTime(),iso:ts,session:p.session||'unknown',rows:p.rows||p.data||[]});}catch{parseFailures++;}}
snapshots.sort((a,b)=>a.ts-b.ts);
const byKey=new Map(),obs=[];
for(const snap of snapshots){for(const r of snap.rows){const ticker=String(r.Ticker||r.Symbol||'').trim().toUpperCase(),price=parseNum(r.Price),volume=parseNum(r.Volume),change=pct(r.Change),rvol=pct(r['Relative Volume']??r['Rel Volume']);if(!ticker||!price||price<=0)continue;const day=new Date(snap.ts).toISOString().slice(0,10),key=`${ticker}|${day}`;const o={ticker,key,ts:snap.ts,iso:snap.iso,session:snap.session,price,volume:volume??0,change:change??0,rvol,avgVolume:avgShares(r['Average Volume']),perfWeek:pct(r['Performance (Week)']),gap:pct(r.Gap),sma20:pct(r['20-Day Simple Moving Average']),floatShares:parseNum(r['Shares Float']),row:r};if(!byKey.has(key))byKey.set(key,[]);byKey.get(key).push(o);obs.push(o);}}
for(const arr of byKey.values())arr.sort((a,b)=>a.ts-b.ts);
function priorReturn(arr,i,target,minFactor=.35,maxFactor=2.0){const cur=arr[i];let best=null,bestErr=Infinity;for(let j=i-1;j>=0;j--){const dt=(cur.ts-arr[j].ts)/60000;if(dt>target*maxFactor)break;if(dt<target*minFactor)continue;const e=Math.abs(dt-target);if(e<bestErr){best=arr[j];bestErr=e;}}return best?((cur.price/best.price)-1)*100:null;}
function forward(arr,i,maxMin){const cur=arr[i],xs=[];for(let j=i+1;j<arr.length;j++){const dt=(arr[j].ts-cur.ts)/60000;if(dt>maxMin)break;xs.push(((arr[j].price/cur.price)-1)*100);}return xs;}
function finite(v){return v!==null&&v!==undefined&&Number.isFinite(+v)}
const decisions=[];
for(const [key,arr] of byKey){for(let i=0;i<arr.length;i++){const o=arr[i],m5=priorReturn(arr,i,5,.30,2.4),m10=priorReturn(arr,i,10,.35,2.2),m30=priorReturn(arr,i,30,.4,1.9),m60=priorReturn(arr,i,60,.45,1.8);let shortRate=null;if(i>0){const dt=(o.ts-arr[i-1].ts)/60000;if(dt>0&&dt<=25)shortRate=((o.price/arr[i-1].price)-1)*100/dt;}const mm=[m5,m10,m30].filter(finite),cons=mm.length?mm.filter(x=>x>0).length/mm.length:null,dollar=o.price*o.volume,avgDollar=o.avgVolume?o.price*o.avgVolume:null,floatM=o.floatShares?o.floatShares/1e6:null,floatRot=o.floatShares?o.volume/o.floatShares:null;let ext=Math.max(0,o.change-22)*.45;if(finite(o.gap))ext+=Math.max(0,o.gap-18)*.35;if(finite(o.sma20))ext+=Math.max(0,o.sma20-35)*.20;if(finite(o.perfWeek))ext+=Math.max(0,o.perfWeek-45)*.12;const historyCount=Math.min(i+1,4),persistenceSlope=shortRate;const symbol={symbol:o.ticker,price:o.price,changePct:o.change,volume:o.volume,rvol:o.rvol,floatM,floatRotation:floatRot,spreadPct:null,momentumPct:{'1':null,'5':m5,'10':m10,'30':m30,'60':m60},momentumConsistency:cons,shortMomentumRatePctPerMin:shortRate,priceAccelerationPctPerMin:shortRate,dollarVolume:dollar,averageDollarVolume:avgDollar,trades:null,atrPct:null,gapPct:o.gap,shortFloatPct:null,sma20Pct:o.sma20,perfWeekPct:o.perfWeek,lateExtensionRiskRaw:ext,persistenceSlope,persistencePoints:historyCount,catalystStrength:null,catalystFreshnessMin:null,dilutionRisk:null,haltRisk:o.change>55?.34:o.change>35?.18:.07,recentDilutionFiling:false,dataQuality:(finite(o.rvol)&&finite(m5)&&finite(dollar))?.78:.62,breakoutQuality:cons===null?null:Math.min(.9,cons*.55+Math.min(Math.max(m10??0,0),8)/20+Math.min(Math.max(o.rvol??0,0),12)/45),vwapPosition:null,distanceToBreakoutPct:null};const scored=enrich([symbol],{})[0];const f30=forward(arr,i,30),f60=forward(arr,i,60),fday=forward(arr,i,720);decisions.push({...o,gate:scored.gate.status,phase:scored.phase,score:scored.score,actionability:scored.actionability,continuation:scored.continuation.score,tradability:scored.tradability.score,m5,m10,m30,m60,cons,shortRate,mfe30:f30.length?Math.max(...f30):null,mae30:f30.length?Math.min(...f30):null,mfe60:f60.length?Math.max(...f60):null,mae60:f60.length?Math.min(...f60):null,mfeDay:fday.length?Math.max(...fday):null,maeDay:fday.length?Math.min(...fday):null});}}
const eligible=decisions.filter(x=>finite(x.mfe60));const watch=eligible.filter(x=>x.gate==='WATCH');const firstWatch=[];const fwSeen=new Set();for(const x of watch.sort((a,b)=>a.ts-b.ts)){if(!fwSeen.has(x.key)){fwSeen.add(x.key);firstWatch.push(x)}}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null,median=a=>{const x=a.filter(finite).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2},rate=(a,p)=>a.length?a.filter(p).length/a.length*100:null,round=v=>finite(v)?Math.round(v*100)/100:null;
function metrics(a){return{count:a.length,hit5_30mPct:round(rate(a,x=>(x.mfe30??-999)>=5)),hit10_60mPct:round(rate(a,x=>(x.mfe60??-999)>=10)),hit20_dayPct:round(rate(a,x=>(x.mfeDay??-999)>=20)),medianMFE30Pct:round(median(a.map(x=>x.mfe30))),medianMAE30Pct:round(median(a.map(x=>x.mae30))),medianMFE60Pct:round(median(a.map(x=>x.mfe60))),medianMAE60Pct:round(median(a.map(x=>x.mae60))),medianMFEDayPct:round(median(a.map(x=>x.mfeDay))),medianMAEDayPct:round(median(a.map(x=>x.maeDay)))};}
const positives=eligible.filter(x=>(x.mfe60??-999)>=10),tp=watch.filter(x=>(x.mfe60??-999)>=10);const precision=watch.length?tp.length/watch.length*100:null,recall=positives.length?tp.length/positives.length*100:null,f1=precision&&recall?2*precision*recall/(precision+recall):0;
const oppKeys=new Set();for(const x of eligible)if(x.change<10&&(x.mfe60??-999)>=10)oppKeys.add(x.key);const capKeys=new Set(watch.filter(x=>x.change<10&&(x.mfe60??-999)>=10).map(x=>x.key));
const report={schemaVersion:1,method:'TAGIT_V05_EXACT_CORE_GIT_HISTORY_WALK_FORWARD',generatedAtUTC:new Date().toISOString(),antiLeakageRules:['Historical snapshots loaded from their Git revisions.','All momentum features use only current/prior observations for the same ticker/day.','Forward prices are read only after the TAGit gate is frozen.','The exact production tagit/core.js is imported by this runner.'],coverage:{gitRevisions:revisions.length,parsedUniqueSnapshots:snapshots.length,parseFailures,causalObservations:decisions.length,eligibleObservationsWithForwardData:eligible.length,uniqueTickerDays:byKey.size,watchObservations:watch.length,firstWatchEvents:firstWatch.length},tagit05:{observationLevel:metrics(watch),eventLevelFirstWatch:metrics(firstWatch),classification10pct60m:{candidates:watch.length,positivesInUniverse:positives.length,truePositives:tp.length,precisionPct:round(precision),recallPct:round(recall),f1Pct:round(f1)},earlyOpportunityRecall:{opportunityTickerDays:oppKeys.size,capturedTickerDays:capKeys.size,recallPct:oppKeys.size?round(capKeys.size/oppKeys.size*100):null}},segments:{priceUnder025:metrics(watch.filter(x=>x.price<.25)),price025to1:metrics(watch.filter(x=>x.price>=.25&&x.price<1)),price1plus:metrics(watch.filter(x=>x.price>=1)),earlyUnder10:metrics(watch.filter(x=>x.change<10)),continuation80plus:metrics(watch.filter(x=>x.continuation>=80)),tradability80plus:metrics(watch.filter(x=>x.tradability>=80))},examples:{best:[...watch].filter(x=>finite(x.mfe60)).sort((a,b)=>b.mfe60-a.mfe60).slice(0,12).map(x=>({ticker:x.ticker,iso:x.iso,price:x.price,change:x.change,phase:x.phase,continuation:x.continuation,tradability:x.tradability,m5:round(x.m5),m10:round(x.m10),mfe60:round(x.mfe60),mae60:round(x.mae60)})),worst:[...watch].filter(x=>finite(x.mfe60)).sort((a,b)=>a.mfe60-b.mfe60).slice(0,12).map(x=>({ticker:x.ticker,iso:x.iso,price:x.price,change:x.change,phase:x.phase,continuation:x.continuation,tradability:x.tradability,m5:round(x.m5),m10:round(x.m10),mfe60:round(x.mfe60),mae60:round(x.mae60)}))},limitations:['Historical snapshots are sampled rather than one-minute bars.','1-minute Finviz performance did not exist in the historical archive, so it remains null; 5/10/30/60 minute returns are reconstructed causally from prior snapshots.','Historical spread, catalyst, SEC dilution and full rich Finviz fields are not available for every revision and remain missing rather than fabricated.','No transaction costs or slippage.']};
fs.writeFileSync('tag/data/tagit-v05-walkforward.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({coverage:report.coverage,classification:report.tagit05.classification10pct60m,events:report.tagit05.eventLevelFirstWatch,early:report.tagit05.earlyOpportunityRecall},null,2));
