import{execFileSync}from'node:child_process';
import fs from'node:fs';
const PATH='tag/data/discovery-fast.json';
const num=v=>{if(v===null||v===undefined||v==='')return null;let s=String(v).replace(/[$,%x,]/gi,'').replace(/,/g,'').trim().toUpperCase(),m=1;if(s.endsWith('K')){m=1e3;s=s.slice(0,-1)}else if(s.endsWith('M')){m=1e6;s=s.slice(0,-1)}else if(s.endsWith('B')){m=1e9;s=s.slice(0,-1)}const n=Number(s);return Number.isFinite(n)?n*m:null};
const avg=v=>{if(v===null||v===undefined||v==='')return null;const s=String(v).trim().toUpperCase(),n=num(v);return n===null?null:/[KMB]$/.test(s)?n:n*1000};
const finite=v=>v!==null&&v!==undefined&&Number.isFinite(+v),clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x)),ret=(a,b)=>((a/b)-1)*100;
const revs=execFileSync('git',['log','--format=%H','--',PATH],{encoding:'utf8',maxBuffer:20e6}).trim().split(/\s+/).filter(Boolean).reverse(),sn=[];const seen=new Set();let parseFailures=0;
for(const sha of revs){try{const p=JSON.parse(execFileSync('git',['show',`${sha}:${PATH}`],{encoding:'utf8',maxBuffer:20e6})),iso=p.snapshotTimestampUTC||p.updatedAt;if(!iso||seen.has(iso))continue;seen.add(iso);sn.push({ts:new Date(iso).getTime(),iso,session:p.session||'unknown',rows:p.rows||p.data||[]})}catch{parseFailures++}}
sn.sort((a,b)=>a.ts-b.ts);const by=new Map();
for(const s of sn)for(const r of s.rows){const t=String(r.Ticker||r.Symbol||'').trim().toUpperCase(),p=num(r.Price);if(!t||!p||p<=0)continue;const day=new Date(s.ts).toISOString().slice(0,10),k=t+'|'+day,o={k,t,day,ts:s.ts,iso:s.iso,session:s.session,price:p,change:num(r.Change)??0,volume:num(r.Volume)??0,avgVolume:avg(r['Average Volume']),rvol:num(r['Relative Volume']),perfWeek:num(r['Performance (Week)']),floatShares:num(r['Shares Float'])};if(!by.has(k))by.set(k,[]);by.get(k).push(o)}
for(const a of by.values())a.sort((x,y)=>x.ts-y.ts);
function prior(arr,i,target,min=.3,max=2.4){let z=null,e=1e9;for(let j=i-1;j>=0;j--){const d=(arr[i].ts-arr[j].ts)/60000;if(d>target*max)break;if(d<target*min)continue;if(Math.abs(d-target)<e){z=arr[j];e=Math.abs(d-target)}}return z}
function fwd(arr,i,min){const c=arr[i],x=[];for(let j=i+1;j<arr.length;j++){const d=(arr[j].ts-c.ts)/60000;if(d>min)break;x.push(ret(arr[j].price,c.price))}return x}
const obs=[];
for(const [k,a] of by)for(let i=0;i<a.length;i++){const o=a[i],p5=prior(a,i,5),p10=prior(a,i,10),p30=prior(a,i,30),prev=i?a[i-1]:null,m5=p5?ret(o.price,p5.price):null,m10=p10?ret(o.price,p10.price):null,m30=p30?ret(o.price,p30.price):null;let shortRate=null,vv=null,prevShort=null,prevVV=null,rvolDelta=null;if(prev){const dt=(o.ts-prev.ts)/60000;if(dt>0&&dt<=30){shortRate=ret(o.price,prev.price)/dt;if(o.avgVolume){const dv=o.volume-prev.volume,expected=o.avgVolume/390*dt;if(dv>=0&&expected>0)vv=dv/expected}}if(i>=2){const pp=a[i-2],dtp=(prev.ts-pp.ts)/60000;if(dtp>0&&dtp<=30){prevShort=ret(prev.price,pp.price)/dtp;if(prev.avgVolume){const dv=prev.volume-pp.volume,exp=prev.avgVolume/390*dtp;if(dv>=0&&exp>0)prevVV=dv/exp}}}if(finite(o.rvol)&&finite(prev.rvol))rvolDelta=o.rvol-prev.rvol}
const turnAccel=finite(shortRate)&&finite(prevShort)?shortRate-prevShort:null,volumeAccel=finite(vv)&&finite(prevVV)?vv-prevVV:null,dollar=o.price*o.volume,quiet=finite(m30)?Math.max(0,1-Math.abs(m30)/8):.5,early=o.change>=-20&&o.change<10,tradable=o.price>=.15&&(dollar>=25000||o.volume>=100000);const a30=fwd(a,i,30),a60=fwd(a,i,60),aday=fwd(a,i,720);obs.push({...o,m5,m10,m30,shortRate,vv,prevVV,prevShort,rvolDelta,turnAccel,volumeAccel,dollar,quiet,early,tradable,mfe30:a30.length?Math.max(...a30):null,mae30:a30.length?Math.min(...a30):null,mfe60:a60.length?Math.max(...a60):null,mae60:a60.length?Math.min(...a60):null,mfeDay:aday.length?Math.max(...aday):null,maeDay:aday.length?Math.min(...aday):null})}
const eligible=obs.filter(x=>finite(x.mfe60));
const grouped=new Map();for(const x of eligible){if(!grouped.has(x.iso))grouped.set(x.iso,[]);grouped.get(x.iso).push(x)}
function percentile(values,v){const a=values.filter(finite).sort((x,y)=>x-y);if(!a.length||!finite(v))return 50;let lo=0,hi=a.length;while(lo<hi){const m=(lo+hi)>>1;if(a[m]<=v)lo=m+1;else hi=m}return lo/a.length*100}
for(const xs of grouped.values()){
 const pool=xs.filter(x=>x.early&&x.tradable);
 const lrv=pool.map(x=>finite(x.rvol)?Math.log1p(Math.max(0,x.rvol)):null),lvv=pool.map(x=>finite(x.vv)?Math.log1p(Math.max(0,x.vv)):null),vacc=pool.map(x=>x.volumeAccel),tacc=pool.map(x=>x.turnAccel),sr=pool.map(x=>x.shortRate);
 for(const x of pool){const prv=percentile(lrv,finite(x.rvol)?Math.log1p(Math.max(0,x.rvol)):null),pvv=percentile(lvv,finite(x.vv)?Math.log1p(Math.max(0,x.vv)):null),pva=percentile(vacc,x.volumeAccel),pta=percentile(tacc,x.turnAccel),psr=percentile(sr,x.shortRate),base=x.quiet*100,extension=Math.max(0,x.change-6)*3+Math.max(0,(x.perfWeek??0)-30)*.35; x.transitionScore=Math.round(clamp(prv*.20+pvv*.27+pva*.17+pta*.18+psr*.08+base*.10-extension));}
}
const opportunities=new Set(eligible.filter(x=>x.early&&x.mfe60>=10).map(x=>x.k));
const configs=[];for(const topK of [5,8,10,12,15,20])for(const minScore of [50,55,60,65,70])configs.push({topK,minScore});
function discover(cfg){const out=[];for(const xs of grouped.values()){const z=xs.filter(x=>x.early&&x.tradable&&finite(x.transitionScore)&&x.transitionScore>=cfg.minScore).sort((a,b)=>b.transitionScore-a.transitionScore).slice(0,cfg.topK);out.push(...z)}return out}
const round=v=>finite(v)?Math.round(v*100)/100:null,rate=(a,p)=>a.length?a.filter(p).length/a.length*100:null,median=a=>{const z=a.filter(finite).sort((x,y)=>x-y);if(!z.length)return null;const m=Math.floor(z.length/2);return z.length%2?z[m]:(z[m-1]+z[m])/2};
function first(a){const s=new Set(),o=[];for(const x of [...a].sort((p,q)=>p.ts-q.ts))if(!s.has(x.k)){s.add(x.k);o.push(x)}return o}
function met(a){return{count:a.length,uniqueEvents:first(a).length,precision10_60mPct:round(rate(a,x=>x.mfe60>=10)),hit5_30mPct:round(rate(a,x=>(x.mfe30??-999)>=5)),hit20_dayPct:round(rate(a,x=>(x.mfeDay??-999)>=20)),medianMFE60Pct:round(median(a.map(x=>x.mfe60))),medianMAE60Pct:round(median(a.map(x=>x.mae60)))}}
const res=configs.map(c=>{const d=discover(c),cap=new Set(d.filter(x=>x.mfe60>=10).map(x=>x.k));return{...c,...met(d),capturedTickerDays:cap.size,recallTickerDayPct:round(opportunities.size?cap.size/opportunities.size*100:null)}});
// Select a balanced fixed production candidate without using outcome to choose dynamically at runtime; report all alternatives.
const chosen={topK:10,minScore:60},D=discover(chosen),dmap=new Map();for(const d of D){if(!dmap.has(d.k))dmap.set(d.k,[]);dmap.get(d.k).push(d)}
const P=[];for(const x of eligible){const ds=(dmap.get(x.k)||[]).filter(d=>d.ts<x.ts&&(x.ts-d.ts)/60000<=90).sort((a,b)=>b.ts-a.ts);if(!ds.length)continue;const d=ds[0];const maintained=(x.transitionScore??0)>=50||(x.vv??0)>=.7;const priceTurn=(x.shortRate??-99)>=.02||(x.m5??-99)>=.35;const improving=(x.turnAccel??0)>0||(x.volumeAccel??0)>0||(x.rvolDelta??0)>0;const notExtended=x.change<18;const liquidity=x.price>=.15&&x.dollar>=50000;if(maintained&&priceTurn&&improving&&notExtended&&liquidity)P.push({...x,discoverIso:d.iso,minutesFromDiscover:round((x.ts-d.ts)/60000)})}
const capD=new Set(D.filter(x=>x.mfe60>=10).map(x=>x.k)),capP=new Set(P.filter(x=>x.mfe60>=10).map(x=>x.k));
const byDay={};for(const x of eligible){byDay[x.day]??={eligible:0,positives:0,discover:0,discoverTP:0,promoted:0,promotedTP:0};byDay[x.day].eligible++;if(x.mfe60>=10)byDay[x.day].positives++}for(const x of D){byDay[x.day].discover++;if(x.mfe60>=10)byDay[x.day].discoverTP++}for(const x of P){byDay[x.day].promoted++;if(x.mfe60>=10)byDay[x.day].promotedTP++}for(const z of Object.values(byDay)){z.discoverPrecisionPct=round(z.discover?z.discoverTP/z.discover*100:null);z.promotionPrecisionPct=round(z.promoted?z.promotedTP/z.promoted*100:null)}
// Strict later-date holdout summary: Sep dates are not used to construct thresholds above.
const hold=x=>x.day>='2026-09-01',holdD=D.filter(hold),holdP=P.filter(hold),holdOpp=new Set(eligible.filter(x=>hold(x)&&x.early&&x.mfe60>=10).map(x=>x.k));
const out={schemaVersion:1,method:'TAGIT_V07_CROSS_SECTIONAL_TRANSITION_WALK_FORWARD',generatedAtUTC:new Date().toISOString(),antiLeakageRules:['Historical Git snapshots only.','Features use current/prior observations only.','Ranks are calculated only within the current snapshot.','DISCOVER precedes promotion; future returns are labels only.','September is separately reported as a later-date holdout.'],coverage:{snapshots:sn.length,parseFailures,eligibleObservations:eligible.length,opportunityTickerDays:opportunities.size},score:{rvolPercentile:.20,volumeVelocityPercentile:.27,volumeAccelerationPercentile:.17,turnAccelerationPercentile:.18,shortRatePercentile:.08,quietBase:.10},configResults:res,chosenDiscoveryConfig:chosen,discover:{...met(D),capturedTickerDays:capD.size,recallTickerDayPct:round(opportunities.size?capD.size/opportunities.size*100:null)},promotion:{...met(P),firstEvent:met(first(P)),capturedTickerDays:capP.size,recallTickerDayPct:round(opportunities.size?capP.size/opportunities.size*100:null)},laterDateHoldout:{opportunityTickerDays:holdOpp.size,discover:{...met(holdD),capturedTickerDays:new Set(holdD.filter(x=>x.mfe60>=10).map(x=>x.k)).size},promotion:{...met(holdP),capturedTickerDays:new Set(holdP.filter(x=>x.mfe60>=10).map(x=>x.k)).size}},byDay,examples:{discoverWinners:D.filter(x=>x.mfe60>=10).sort((a,b)=>b.mfe60-a.mfe60).slice(0,15).map(x=>({ticker:x.t,iso:x.iso,change:x.change,score:x.transitionScore,rvol:round(x.rvol),vv:round(x.vv),turnAccel:round(x.turnAccel),mfe60:round(x.mfe60)})),promotionWinners:P.filter(x=>x.mfe60>=10).sort((a,b)=>b.mfe60-a.mfe60).slice(0,12).map(x=>({ticker:x.t,iso:x.iso,change:x.change,score:x.transitionScore,rvol:round(x.rvol),vv:round(x.vv),turnAccel:round(x.turnAccel),minutesFromDiscover:x.minutesFromDiscover,mfe60:round(x.mfe60)}))},limitations:['Historical snapshots are sampled, not one-minute bars.','Rich Finviz 1/2/3-minute, trades, news and SEC fields do not exist for every historical revision and are not fabricated.','Rare positives on later dates make holdout estimates noisy.','No transaction costs/slippage.']};fs.writeFileSync('tag/data/tagit-v07-walkforward.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({coverage:out.coverage,discover:out.discover,promotion:out.promotion,holdout:out.laterDateHoldout,byDay:out.byDay},null,2));