const LIVE_URL='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/live-quotes.json';
const AI_URL='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/ai-stock-analysis.json';
const VALIDATION_URL='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/tagit-v531-free-pit-training.json';
const POLL_MS=5000,FRESH_MS=4*60*1000,STALE_MS=10*60*1000,RETAIN_MS=30*60*1000,MEM='tagit_v6_memory';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const n=v=>v==null||v===''||!Number.isFinite(+v)?null:+v;
const fmt=(v,d=2)=>n(v)==null?'—':n(v).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=v=>n(v)==null?'—':`${n(v)>=0?'+':''}${fmt(v)}%`;
const esc=s=>String(s??'—').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const age=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Date.now()-t:Infinity};
const active=s=>['pre-market','regular','after-hours'].includes(String(s||'').toLowerCase());
const vol=v=>{const x=n(v);if(x==null)return'—';if(x>=1e9)return`${fmt(x/1e9,2)}B`;if(x>=1e6)return`${fmt(x/1e6,2)}M`;if(x>=1e3)return`${fmt(x/1e3,1)}K`;return fmt(x,0)};
let app={live:null,ai:null,filter:'ALL',selected:null,countdown:5,lastSnapshot:null,memory:{},fetchError:null};
try{app.memory=JSON.parse(localStorage.getItem(MEM)||'{}')}catch{}
function save(){try{localStorage.setItem(MEM,JSON.stringify(app.memory))}catch{}}
async function getJson(u){const r=await fetch(`${u}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function updateMemory(live){
 const snap=live?.updatedAtUTC||live?.updatedAtET;if(!snap)return;const now=Date.now();
 for(const [k,v] of Object.entries(app.memory))if(now-(v.seenAt||0)>RETAIN_MS)delete app.memory[k];
 if(snap===app.lastSnapshot)return;app.lastSnapshot=snap;
 const rows=[...(live.emergingCandidates||[]),...(live.accumulationCandidates||[])];
 for(const x of rows){const k=String(x.ticker||'').toUpperCase();if(!k)continue;const m=app.memory[k]||{hits:0,prev:null,last:null,seenAt:0,row:null};m.prev=m.last;m.last={price:n(x.price),score:n(x.earlyRegimeShiftScore),v5:n(x.priceVelocity5mPct),v15:n(x.priceVelocity15mPct),snap};m.row={...(m.row||{}),...x};m.hits++;m.seenAt=now;app.memory[k]=m}
 save();
}
function classify(x){
 const m=app.memory[x.ticker]||{},v5=n(x.priceVelocity5mPct),v15=n(x.priceVelocity15mPct),score=n(x.earlyRegimeShiftScore),a5=x.volumeAccelerationComparable5m===true?n(x.volumeAcceleration5m):null,turn=n(x.turnover5mPctFloat),ch=n(x.changePct),price=n(x.price),acc=x.liquidityAccumulation===true||n(x.accumulationScore)>=55;let reasons=[];
 const independent=(v15!=null&&v15>=1.2)||(a5!=null&&a5>=1.8)||(turn!=null&&turn>=1)||acc;
 const core=v5!=null&&v5>=0.8&&score!=null&&score>=65&&independent;
 const deterioration=m.prev&&m.last&&((m.prev.price&&m.last.price<m.prev.price*.97)||(m.prev.score!=null&&m.last.score!=null&&m.last.score<m.prev.score-12));
 const overheated=ch!=null&&ch>=18,micro=price!=null&&price<1;
 let state='VERIFY';if(core&&(m.hits||0)>=2&&!deterioration&&!overheated)state='CONFIRMED';if(deterioration||(v5!=null&&v5<-.5))state='COOLING';if(overheated)state='EXTENDED';
 let risk=0;if(micro)risk+=25;if(overheated)risk+=25;if(a5==null&&turn==null&&!acc)risk+=15;if(n(x.quoteAgeMin)>2)risk+=10;if(deterioration)risk+=30;
 const persistence=Math.max(0,Math.min(100,Math.round(((m.hits||0)>=2?35:10)+(v15||0)*5+(a5?Math.min(20,a5*3):0)+(turn?Math.min(20,turn*2):0)+(acc?Math.min(20,(n(x.accumulationScore)||0)*.2):0)-(deterioration?35:0))));
 const quality=Math.max(0,Math.min(100,Math.round((score||0)*.5+(n(x.ignitionScore)||0)*.18+persistence*.22+(acc?(n(x.accumulationScore)||0)*.1:0)-risk*.35)));
 if(acc)reasons.push(`تجميع ${fmt(x.accumulationScore,0)}`);if(v5!=null)reasons.push(`5m ${pct(v5)}`);if(v15!=null)reasons.push(`15m ${pct(v15)}`);if(a5!=null)reasons.push(`Vol ${fmt(a5,1)}x`);if(turn!=null)reasons.push(`Turn ${fmt(turn,1)}%`);if(n(x.range15mPct)!=null)reasons.push(`Range15 ${pct(x.range15mPct)}`);
 return{state,risk,persistence,quality,hits:m.hits||0,accumulation:acc,reasons:reasons.join(' · ')};
}
function freshness(live){const a=age(live?.updatedAtUTC||live?.updatedAtET);if(!live||!active(live.marketClockSession))return{state:'OFFLINE',ok:false,age:a};if(a<=FRESH_MS)return{state:'LIVE',ok:true,age:a};if(a<=STALE_MS)return{state:'DELAYED',ok:false,age:a};return{state:'STALE',ok:false,age:a}}
function currentRows(){
 const now=Date.now(),map=new Map(),put=(x,retained=false)=>{if(!x?.ticker)return;const t=String(x.ticker).toUpperCase(),old=map.get(t)||{};map.set(t,{...old,...x,ticker:t,retained:old.retained&&retained?true:retained})};
 for(const x of app.live?.accumulationCandidates||[])put(x,false);
 for(const x of app.live?.emergingCandidates||[])put(x,false);
 for(const [ticker,m] of Object.entries(app.memory)){if(!m?.row||now-(m.seenAt||0)>RETAIN_MS||map.has(ticker))continue;put({...m.row,ticker,retainedAgeMs:now-(m.seenAt||0)},true)}
 return [...map.values()];
}
function enriched(){return currentRows().map(x=>({...x,...classify(x)})).sort((a,b)=>{const sw=s=>s==='CONFIRMED'?4:s==='VERIFY'?3:s==='COOLING'?2:1;return sw(b.state)-sw(a.state)||(b.accumulation-a.accumulation)||(b.quality-a.quality)})}
function visible(){let xs=enriched();if(app.filter==='ACCUMULATION')xs=xs.filter(x=>x.accumulation);else if(app.filter!=='ALL')xs=xs.filter(x=>x.state===app.filter);return xs}
function statusText(f){if(f.state==='LIVE')return'LIVE · AUTO REFRESH 5s';if(f.state==='DELAYED')return'DELAYED · BACKEND REFRESHING';if(f.state==='STALE')return'DATA STALE · LAST VALID OPPORTUNITIES';return'MARKET CLOSED / OFFLINE'}
function cardHTML(x,f,rank){
 const cls=x.state.toLowerCase(),ranked=x.state==='CONFIRMED'&&f.ok&&!x.retained,held=x.retained?'<span class="state verify">LAST VALID</span>':'',acc=x.accumulation?'<span class="state accumulation">تجميع سيولة</span>':'';
 const sessionVol=x.state==='CONFIRMED'?`<span class="session-vol">Vol الجلسة <b>${vol(x.sessionVolume)}</b></span>`:'';
 return `<article class="opp ${cls}" data-symbol="${esc(x.ticker)}"><div class="opp-top"><div><span class="ticker">${esc(x.ticker)}</span><span class="state ${cls}">${x.state}</span>${acc}${held}</div><span class="rank">${ranked?'#'+rank:'—'}</span></div><div class="price-row"><b>$${fmt(x.price,4)}</b><span class="${n(x.changePct)>=0?'pos':'neg'}">${pct(x.changePct)}</span></div>${sessionVol}<div class="bars"><label>Quality <i>${x.quality}</i><span><em style="width:${x.quality}%"></em></span></label><label>Persistence <i>${x.persistence}</i><span><em style="width:${x.persistence}%"></em></span></label></div><div class="chips"><span>5m ${pct(x.priceVelocity5mPct)}</span><span>15m ${pct(x.priceVelocity15mPct)}</span><span>Risk ${x.risk}</span><span>${x.hits} snapshots</span>${x.accumulation?`<span>Acc ${fmt(x.accumulationScore,0)}</span>`:''}</div><small>${esc(x.reasons)}${x.retained?' · محفوظ من آخر لقطة صالحة':''}</small><div class="opp-actions"><button type="button" class="analyze" data-analyze="${esc(x.ticker)}">✦ حلل</button></div></article>`;
}
function render(){
 const live=app.live,f=freshness(live),all=enriched(),confirmed=all.filter(x=>x.state==='CONFIRMED'),verify=all.filter(x=>x.state==='VERIFY'),cool=all.filter(x=>x.state==='COOLING'||x.state==='EXTENDED');
 $('#status').textContent=statusText(f);$('#status').dataset.state=f.state;$('#session').textContent=String(live?.marketClockSession||'unknown').toUpperCase();$('#asof').textContent=live?.updatedAtET?new Date(live.updatedAtET).toLocaleTimeString('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',second:'2-digit'})+' ET':'—';$('#age').textContent=Number.isFinite(f.age)?`${(f.age/60000).toFixed(1)}m`:'—';$('#coverage').textContent=`${live?.freshCount||0}/${live?.requested||0}`;$('#confidence').textContent=live?.dataConfidence||'—';$('#confirmedCount').textContent=confirmed.length;$('#verifyCount').textContent=verify.length;$('#coolCount').textContent=cool.length;$('#next').textContent=`${app.countdown}s`;
 const list=$('#opportunities'),xs=visible();
 if(!xs.length)list.innerHTML=`<div class="empty"><b>لا توجد فرص نشطة الآن</b><span>${app.fetchError?'تعذر جلب آخر snapshot، وسيعاد المحاولة كل 5 ثوانٍ.':'الرادار يعمل ولم تظهر فرصة مجتازة حتى الآن.'}</span></div>`;
 else{let rank=0;list.innerHTML=xs.map(x=>{if(x.state==='CONFIRMED'&&f.ok&&!x.retained)rank++;return cardHTML(x,f,rank)}).join('')}
 $$('.opp').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-analyze]'))return;app.selected=el.dataset.symbol;renderDetail()});
 $$('[data-analyze]').forEach(b=>b.onclick=e=>{e.stopPropagation();openAI(b.dataset.analyze)});
 renderDetail();$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===app.filter));
}
function renderDetail(){const host=$('#detail'),x=enriched().find(z=>z.ticker===app.selected)||enriched()[0];if(!x){host.innerHTML='<div class="empty"><b>لا توجد فرصة محددة</b><span>اختر فرصة من الرادار عند ظهورها.</span></div>';return}app.selected=x.ticker;host.innerHTML=`<div class="detail-head"><div><span class="ticker big">${esc(x.ticker)}</span><span class="state ${x.state.toLowerCase()}">${x.state}</span>${x.accumulation?'<span class="state accumulation">تجميع سيولة</span>':''}${x.retained?'<span class="state verify">LAST VALID</span>':''}</div><b>${x.state==='CONFIRMED'?x.quality:'—'}</b></div><div class="detail-price">$${fmt(x.price,4)} <span class="${n(x.changePct)>=0?'pos':'neg'}">${pct(x.changePct)}</span></div><div class="detail-grid"><div><span>Quality</span><b>${x.quality}</b></div><div><span>Persistence</span><b>${x.persistence}</b></div><div><span>Risk</span><b>${x.risk}</b></div><div><span>Snapshots</span><b>${x.hits}</b></div><div><span>Vol الجلسة</span><b>${vol(x.sessionVolume)}</b></div><div><span>Accumulation</span><b>${fmt(x.accumulationScore,0)}</b></div><div><span>5m</span><b>${pct(x.priceVelocity5mPct)}</b></div><div><span>15m</span><b>${pct(x.priceVelocity15mPct)}</b></div></div><p>${esc(x.reasons)}</p><button class="analyze wide" data-detail-analyze="${esc(x.ticker)}">✦ حلل السهم والأخبار بالذكاء الاصطناعي</button><div class="notice">${x.retained?'هذه فرصة محفوظة من آخر لقطة صالحة لضمان استمرارية العرض، ولا يعاد ترتيبها حتى تصل لقطة حديثة.':x.state==='CONFIRMED'?'اجتاز التأكيد متعدد اللقطات، لكنه يظل مرشحًا بحثيًا وليس ضمانًا للربح.':'لا يوجد ترتيب تنفيذي قبل اكتمال التأكيد والاستمرارية.'}</div>`;const b=$('[data-detail-analyze]');if(b)b.onclick=()=>openAI(b.dataset.detailAnalyze)}
function ensureModal(){if($('#aiModal'))return;const m=document.createElement('div');m.id='aiModal';m.className='ai-modal';m.innerHTML='<div class="ai-sheet"><button class="ai-close" aria-label="close">×</button><div id="aiBody"></div></div>';document.body.appendChild(m);m.querySelector('.ai-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}}
function localFallback(x){const pos=[];if(x?.accumulation)pos.push('هناك نمط دخول سيولة مع تماسك سعري يستحق المتابعة');if((n(x?.volumeAcceleration5m)||0)>=1.8)pos.push('تسارع الحجم قصير الأجل مرتفع');if((n(x?.ignitionScore)||0)>=75)pos.push('درجة الاشتعال الفني مرتفعة');return pos.join('، ')||'لا توجد أفضلية قوية كافية من البيانات اللحظية وحدها.'}
async function openAI(ticker){ensureModal();const modal=$('#aiModal'),body=$('#aiBody');modal.classList.add('open');const x=enriched().find(z=>z.ticker===ticker);body.innerHTML=`<div class="ai-head"><div><span class="eyebrow">AI STOCK ANALYSIS</span><h3>${esc(ticker)}</h3></div><span class="ai-loading">جارٍ تحميل آخر تحليل…</span></div>`;try{app.ai=await getJson(AI_URL)}catch{}
 const a=app.ai?.analyses?.[ticker],mode=a?.mode==='GITHUB_MODELS_AI'?'AI · GitHub Models':'تحليل أولي';const news=(a?.news||[]).slice(0,5);
 body.innerHTML=`<div class="ai-head"><div><span class="eyebrow">AI STOCK ANALYSIS</span><h3>${esc(ticker)}</h3></div><span class="ai-mode">${mode}</span></div><div class="ai-stats"><span>السعر <b>$${fmt(x?.price,4)}</b></span><span>التغير <b>${pct(x?.changePct)}</b></span><span>حجم الجلسة <b>${vol(x?.sessionVolume)}</b></span><span>تجميع <b>${fmt(x?.accumulationScore,0)}</b></span></div><section><h4>القراءة</h4><p>${esc(a?.summary||localFallback(x))}</p></section><section><h4>الفرصة قصيرة الأجل</h4><p>${esc(a?.opportunity||'تتطلب تأكيدًا إضافيًا من السعر والحجم قبل اعتبار الحركة مستدامة.')}</p></section><section><h4>فرص النمو الأساسية</h4><p>${esc(a?.growthView||'لم يكتمل تحليل النمو الأساسي بعد؛ لا يمكن استنتاج نمو الشركة من الزخم اللحظي وحده.')}</p></section><section><h4>المخاطر</h4><p>${esc((a?.risks||[]).join(' · ')||'راجع مخاطر السيولة، التخفيف، الأخبار، والانعكاس السريع في الأسهم الصغيرة.')}</p></section><section><h4>آخر الأخبار</h4>${news.length?`<div class="ai-news">${news.map(z=>`<a href="${esc(z.link||'#')}" target="_blank" rel="noopener"><b>${esc(z.title)}</b><span>${esc(z.publisher||'')}</span></a>`).join('')}</div>`:'<p>لا توجد أخبار حديثة متاحة في آخر دورة التحليل.</p>'}</section><div class="notice">هذا تحليل بحثي مساعد، وليس ضمانًا للحركة أو توصية استثمارية شخصية.</div>`;
}
function ensureStyles(){if($('#tagit-v63-style'))return;const s=document.createElement('style');s.id='tagit-v63-style';s.textContent=`.state.accumulation{border-color:#9f7aea;color:#c4b5fd;background:rgba(159,122,234,.1)}.session-vol{display:flex;justify-content:space-between;gap:10px;margin:10px 0;padding:8px 10px;border:1px solid rgba(75,214,255,.18);border-radius:10px;font-size:12px}.session-vol b{font-size:14px}.opp-actions{display:flex;justify-content:flex-end;margin-top:10px}.analyze{border:1px solid rgba(92,231,255,.35);background:rgba(25,183,220,.1);color:#78ecff;border-radius:10px;padding:8px 14px;font-weight:800;cursor:pointer}.analyze.wide{width:100%;margin:12px 0}.ai-modal{position:fixed;inset:0;background:rgba(0,8,16,.76);backdrop-filter:blur(8px);display:none;align-items:flex-end;justify-content:center;z-index:9999}.ai-modal.open{display:flex}.ai-sheet{position:relative;width:min(720px,100%);max-height:88vh;overflow:auto;background:#0a1c2b;border:1px solid rgba(80,220,255,.25);border-radius:24px 24px 0 0;padding:24px;box-shadow:0 -20px 80px rgba(0,0,0,.45)}.ai-close{position:absolute;left:16px;top:12px;width:36px;height:36px;border-radius:50%;border:1px solid rgba(255,255,255,.18);background:transparent;color:#fff;font-size:26px}.ai-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.ai-head h3{font-size:30px;margin:4px 0}.ai-mode,.ai-loading{font-size:11px;border:1px solid rgba(80,220,255,.25);border-radius:999px;padding:6px 9px;color:#76eaff}.ai-stats{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.ai-stats span{background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:10px;display:flex;justify-content:space-between}.ai-sheet section{border-top:1px solid rgba(255,255,255,.08);padding:14px 0}.ai-sheet h4{margin:0 0 7px;color:#7be9ff}.ai-sheet p{margin:0;line-height:1.8;color:#d4dfeb}.ai-news{display:grid;gap:8px}.ai-news a{text-decoration:none;color:#fff;border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:10px;display:grid;gap:4px}.ai-news a span{font-size:11px;color:#8fa4b7}@media(min-width:760px){.ai-modal{align-items:center}.ai-sheet{border-radius:24px}}`;document.head.appendChild(s)}
async function refresh(){app.countdown=5;try{const base=await getJson(LIVE_URL);app.live=base;app.fetchError=null;updateMemory(base);render()}catch(e){app.fetchError=String(e);console.warn('TAGit feed refresh',e);render()}}
async function validation(){try{const r=await getJson(VALIDATION_URL),h=r.researchHoldout||{};$('#research').innerHTML=`<span>v5.31 research</span><b>${fmt(h.precision20Pct)}%</b><small>${h.tp20||0}/${h.count||0} · Wilson90 ${fmt(h.wilsonLower90Pct)}% · Top3 ${fmt(h.top3DailyPrecisionPct)}%</small>`}catch{}}
$$('[data-filter]').forEach(b=>b.onclick=()=>{app.filter=b.dataset.filter;render()});$('#refresh').onclick=refresh;ensureStyles();
setInterval(()=>{app.countdown=Math.max(0,app.countdown-1);$('#next').textContent=`${app.countdown}s`;if(app.countdown===0)refresh()},1000);
setInterval(()=>{if(app.live)render()},5000);
refresh();validation();