const LIVE_URL='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/live-quotes.json';
const VALIDATION_URL='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/tagit-v531-free-pit-training.json';
const POLL_MS=10000, FRESH_MS=4*60*1000, STALE_MS=8*60*1000, MEM='tagit_v6_memory';
const DIRECT_MAX=28, DIRECT_TIMEOUT_MS=4500, DIRECT_RETRY_MS=15000;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const n=v=>v==null||v===''||!Number.isFinite(+v)?null:+v;
const fmt=(v,d=2)=>n(v)==null?'—':n(v).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=v=>n(v)==null?'—':`${n(v)>=0?'+':''}${fmt(v)}%`;
const esc=s=>String(s??'—').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const age=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Date.now()-t:Infinity};
const active=s=>['pre-market','regular','after-hours'].includes(String(s||'').toLowerCase());
let app={live:null,filter:'ALL',selected:null,countdown:10,lastSnapshot:null,memory:{},direct:false,directError:null,directLastAt:0};
try{app.memory=JSON.parse(localStorage.getItem(MEM)||'{}')}catch{}
function save(){try{localStorage.setItem(MEM,JSON.stringify(app.memory))}catch{}}
async function getJson(u){const r=await fetch(`${u}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function updateMemory(live){const snap=live.updatedAtUTC||live.updatedAtET;if(!snap||snap===app.lastSnapshot)return;app.lastSnapshot=snap;const now=Date.now();for(const [k,v] of Object.entries(app.memory))if(now-(v.seenAt||0)>60*60*1000)delete app.memory[k];
 for(const x of live.emergingCandidates||[]){const k=x.ticker;if(!k)continue;const m=app.memory[k]||{hits:0,prev:null,last:null,seenAt:0};m.prev=m.last;m.last={price:n(x.price),score:n(x.earlyRegimeShiftScore),v5:n(x.priceVelocity5mPct),v15:n(x.priceVelocity15mPct),snap};m.hits++;m.seenAt=now;app.memory[k]=m}save()}
function classify(x){const m=app.memory[x.ticker]||{},v5=n(x.priceVelocity5mPct),v15=n(x.priceVelocity15mPct),score=n(x.earlyRegimeShiftScore),a5=x.volumeAccelerationComparable5m===true?n(x.volumeAcceleration5m):null,turn=n(x.turnover5mPctFloat),ch=n(x.changePct),price=n(x.price);let reasons=[];
 const independent=(v15!=null&&v15>=1.2)||(a5!=null&&a5>=1.8)||(turn!=null&&turn>=1);
 const core=v5!=null&&v5>=0.8&&score!=null&&score>=65&&independent;
 const deterioration=m.prev&&m.last&&((m.prev.price&&m.last.price<m.prev.price*.97)||(m.prev.score!=null&&m.last.score!=null&&m.last.score<m.prev.score-12));
 const overheated=ch!=null&&ch>=18; const micro=price!=null&&price<1;
 let state='VERIFY';if(core&&m.hits>=2&&!deterioration&&!overheated)state='CONFIRMED';if(deterioration||v5!=null&&v5<0)state='COOLING';if(overheated)state='EXTENDED';
 let risk=0;if(micro)risk+=25;if(overheated)risk+=25;if(a5==null&&turn==null)risk+=15;if(n(x.quoteAgeMin)>2)risk+=10;if(deterioration)risk+=30;if(x.directLive===true)risk+=5;
 const persistence=Math.max(0,Math.min(100,Math.round((m.hits>=2?35:10)+(v15||0)*5+(a5?Math.min(20,a5*3):0)+(turn?Math.min(20,turn*2):0)-(deterioration?35:0))));
 const quality=Math.max(0,Math.min(100,Math.round((score||0)*.55+(n(x.ignitionScore)||0)*.2+persistence*.25-risk*.35)));
 if(v5!=null)reasons.push(`5m ${pct(v5)}`);if(v15!=null)reasons.push(`15m ${pct(v15)}`);if(a5!=null)reasons.push(`Vol ${fmt(a5,1)}x`);if(turn!=null)reasons.push(`Turn ${fmt(turn,1)}%`);if(x.directLive===true)reasons.push('Direct live');return{state,risk,persistence,quality,hits:m.hits||0,reasons:reasons.join(' · ')}}
function freshness(live){const a=age(live?.updatedAtUTC||live?.updatedAtET);if(!live||!active(live.marketClockSession))return{state:'OFFLINE',ok:false,age:a};if(a<=FRESH_MS)return{state:app.direct?'DIRECT':'LIVE',ok:true,age:a};if(a<=STALE_MS)return{state:'DELAYED',ok:false,age:a};return{state:'STALE',ok:false,age:a}}
function enriched(){const live=app.live;if(!live)return[];return (live.emergingCandidates||[]).map(x=>({...x,...classify(x)})).sort((a,b)=>{const sw=s=>s==='CONFIRMED'?3:s==='VERIFY'?2:s==='COOLING'?1:0;return sw(b.state)-sw(a.state)||b.quality-a.quality})}
function visible(){let xs=enriched();if(app.filter!=='ALL')xs=xs.filter(x=>x.state===app.filter);return xs}
function statusText(f){return f.state==='DIRECT'?'DIRECT LIVE · SHORTLIST':f.state==='LIVE'?'LIVE · AUTO REFRESH':f.state==='DELAYED'?'DELAYED · DIRECT RECOVERY':f.state==='STALE'?'DATA STALE · DIRECT RECOVERY':'MARKET CLOSED / OFFLINE'}
function render(){const live=app.live,f=freshness(live),all=enriched(),confirmed=f.ok?all.filter(x=>x.state==='CONFIRMED'):[],verify=f.ok?all.filter(x=>x.state==='VERIFY'):[],cool=all.filter(x=>x.state==='COOLING'||x.state==='EXTENDED');
 $('#status').textContent=statusText(f);$('#status').dataset.state=f.state;$('#session').textContent=String(live?.marketClockSession||'unknown').toUpperCase();$('#asof').textContent=live?.updatedAtET?new Date(live.updatedAtET).toLocaleTimeString('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',second:'2-digit'})+' ET':'—';$('#age').textContent=Number.isFinite(f.age)?`${(f.age/60000).toFixed(1)}m`:'—';$('#coverage').textContent=`${live?.freshCount||0}/${live?.requested||0}`;$('#confidence').textContent=app.direct?'DIRECT':(live?.dataConfidence||'—');$('#confirmedCount').textContent=confirmed.length;$('#verifyCount').textContent=verify.length;$('#coolCount').textContent=cool.length;$('#next').textContent=`${app.countdown}s`;
 const list=$('#opportunities');let xs=visible();if(!f.ok)xs=[];if(!xs.length){list.innerHTML=`<div class="empty"><b>${f.ok?'لا توجد فرص مجتازة الآن':'جارٍ استعادة البيانات الحية'}</b><span>${f.ok?'الرادار يعمل، لكن لا يوجد مرشح يستحق الترتيب حاليًا.':app.directError?'تعذر المسار المباشر مؤقتًا؛ سيعاد المحاولة تلقائيًا.':'يتم الآن محاولة جلب مباشر للأسعار بدل انتظار ملف GitHub.'}</span></div>`}else{let rank=0;list.innerHTML=xs.map(x=>{const ranked=x.state==='CONFIRMED';if(ranked)rank++;const cls=x.state.toLowerCase();return `<button class="opp ${cls}" data-symbol="${esc(x.ticker)}"><div class="opp-top"><div><span class="ticker">${esc(x.ticker)}</span><span class="state ${cls}">${x.state}</span></div><span class="rank">${ranked?'#'+rank:'—'}</span></div><div class="price-row"><b>$${fmt(x.price,4)}</b><span class="${n(x.changePct)>=0?'pos':'neg'}">${pct(x.changePct)}</span></div><div class="bars"><label>Quality <i>${x.quality}</i><span><em style="width:${x.quality}%"></em></span></label><label>Persistence <i>${x.persistence}</i><span><em style="width:${x.persistence}%"></em></span></label></div><div class="chips"><span>5m ${pct(x.priceVelocity5mPct)}</span><span>15m ${pct(x.priceVelocity15mPct)}</span><span>Risk ${x.risk}</span><span>${x.hits} snapshots</span></div><small>${esc(x.reasons)}</small></button>`}).join('')}
 $$('.opp').forEach(el=>el.onclick=()=>{app.selected=el.dataset.symbol;renderDetail()});renderDetail();$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===app.filter))}
function renderDetail(){const host=$('#detail'),x=enriched().find(z=>z.ticker===app.selected)||enriched()[0];if(!x){host.innerHTML='<div class="empty"><b>لا توجد فرصة محددة</b><span>اختر فرصة من الرادار عند ظهورها.</span></div>';return}app.selected=x.ticker;host.innerHTML=`<div class="detail-head"><div><span class="ticker big">${esc(x.ticker)}</span><span class="state ${x.state.toLowerCase()}">${x.state}</span></div><b>${x.state==='CONFIRMED'?x.quality:'—'}</b></div><div class="detail-price">$${fmt(x.price,4)} <span class="${n(x.changePct)>=0?'pos':'neg'}">${pct(x.changePct)}</span></div><div class="detail-grid"><div><span>Quality</span><b>${x.quality}</b></div><div><span>Persistence</span><b>${x.persistence}</b></div><div><span>Risk</span><b>${x.risk}</b></div><div><span>Snapshots</span><b>${x.hits}</b></div><div><span>5m</span><b>${pct(x.priceVelocity5mPct)}</b></div><div><span>15m</span><b>${pct(x.priceVelocity15mPct)}</b></div></div><p>${esc(x.reasons)}</p><div class="notice">${x.state==='CONFIRMED'?'اجتاز التأكيد متعدد اللقطات، لكنه يظل مرشحًا بحثيًا وليس ضمانًا للربح.':'لا يوجد ترتيب تنفيذي قبل اكتمال التأكيد والاستمرارية.'}</div>`}
function candidateSymbols(live){const out=[],seen=new Set();const push=t=>{t=String(t||'').trim().toUpperCase();if(t&&!seen.has(t)&&out.length<DIRECT_MAX){seen.add(t);out.push(t)}};(live?.emergingCandidates||[]).forEach(x=>push(x.ticker));Object.values(live?.quotes||{}).sort((a,b)=>(n(b.earlyRegimeShiftScore)||0)-(n(a.earlyRegimeShiftScore)||0)||(n(b.ignitionScore)||0)-(n(a.ignitionScore)||0)).forEach(x=>push(x.ticker));return out}
function sessionForDate(d){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d);const wd=p.find(x=>x.type==='weekday')?.value;const hh=+(p.find(x=>x.type==='hour')?.value||0),mm=+(p.find(x=>x.type==='minute')?.value||0),m=hh*60+mm;if(['Sat','Sun'].includes(wd))return'closed';if(m>=240&&m<570)return'pre-market';if(m>=570&&m<960)return'regular';if(m>=960&&m<=1200)return'after-hours';return'closed'}
async function directQuote(ticker,base){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),DIRECT_TIMEOUT_MS);try{const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(ticker)}?interval=1m&range=1d&includePrePost=true&events=div%2Csplits&_=${Date.now()}`;const r=await fetch(u,{cache:'no-store',signal:ctl.signal,headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`YF ${r.status}`);const j=await r.json(),z=j?.chart?.result?.[0];if(!z)throw new Error('empty');const ts=z.timestamp||[],cl=z.indicators?.quote?.[0]?.close||[],vo=z.indicators?.quote?.[0]?.volume||[];const pts=[];for(let i=0;i<ts.length;i++)if(cl[i]!=null)pts.push({t:ts[i]*1000,p:+cl[i],v:+(vo[i]||0)});if(!pts.length)throw new Error('no points');const latest=pts.at(-1),ago=min=>{const c=latest.t-min*60000;let q=pts[0];for(const p of pts){if(p.t<=c)q=p;else break}return q?.p};const pp=z.meta?.previousClose??z.meta?.chartPreviousClose;const p5=ago(5),p15=ago(15);const pc=(p,b)=>b?((p-b)/b*100):null;const v5=pc(latest.p,p5),v15=pc(latest.p,p15),ch=pc(latest.p,pp);const ageMin=Math.max(0,(Date.now()-latest.t)/60000);const score=Math.max(0,Math.min(100,Math.round(45+(v5||0)*5+(v15||0)*1.5+((ch||0)>=2&&ch<18?10:0)-((ch||0)>=20?25:0))));return {...base,ticker,price:latest.p,changePct:ch,priceVelocity5mPct:v5,priceVelocity15mPct:v15,quoteAgeMin:ageMin,earlyRegimeShiftScore:score,ignitionScore:Math.max(score,n(base?.ignitionScore)||0),timestampET:new Date(latest.t).toISOString(),directLive:true}}finally{clearTimeout(tm)}}
async function directRecovery(base){if(!base||Date.now()-app.directLastAt<DIRECT_RETRY_MS)return false;app.directLastAt=Date.now();const symbols=candidateSymbols(base);if(!symbols.length)return false;const byTicker={};for(const x of base.emergingCandidates||[])byTicker[x.ticker]=x;for(const [k,v] of Object.entries(base.quotes||{}))byTicker[k]=v;const settled=await Promise.allSettled(symbols.map(t=>directQuote(t,byTicker[t]||{ticker:t})));const rows=settled.filter(x=>x.status==='fulfilled').map(x=>x.value).filter(x=>n(x.quoteAgeMin)!=null&&n(x.quoteAgeMin)<=3);if(rows.length<3)throw new Error(`direct live insufficient ${rows.length}/${symbols.length}`);const emerging=rows.filter(x=>n(x.changePct)!=null&&n(x.changePct)>=1.5&&n(x.changePct)<20&&n(x.priceVelocity5mPct)!=null&&n(x.priceVelocity5mPct)>=0.5).sort((a,b)=>(n(b.earlyRegimeShiftScore)||0)-(n(a.earlyRegimeShiftScore)||0));const now=new Date(),session=sessionForDate(now);app.live={...base,updatedAtUTC:now.toISOString(),updatedAtET:now.toISOString(),marketClockSession:session==='closed'?base.marketClockSession:session,source:'Yahoo Finance browser direct shortlist overlay',freshCount:rows.length,requested:symbols.length,dataConfidence:'DIRECT',emergingCount:emerging.length,emergingCandidates:emerging};app.direct=true;app.directError=null;updateMemory(app.live);render();return true}
async function refresh(){app.countdown=10;let base=null;try{base=await getJson(LIVE_URL);app.live=base;app.direct=false;app.directError=null;updateMemory(base);render();const f=freshness(base);if(!f.ok)try{await directRecovery(base)}catch(e){app.directError=String(e);console.warn('direct recovery',e);render()}}catch(e){console.warn(e);app.directError=String(e);if(base)app.live=base;render()}}
async function validation(){try{const r=await getJson(VALIDATION_URL),h=r.researchHoldout||{};$('#research').innerHTML=`<span>v5.31 research</span><b>${fmt(h.precision20Pct)}%</b><small>${h.tp20||0}/${h.count||0} · Wilson90 ${fmt(h.wilsonLower90Pct)}% · Top3 ${fmt(h.top3DailyPrecisionPct)}%</small>`}catch{}}
$$('[data-filter]').forEach(b=>b.onclick=()=>{app.filter=b.dataset.filter;render()});$('#refresh').onclick=async()=>{app.directLastAt=0;await refresh()};
setInterval(()=>{app.countdown=Math.max(0,app.countdown-1);$('#next').textContent=`${app.countdown}s`;if(app.countdown===0)refresh()},1000);
refresh();validation();