const LIVE='https://raw.githubusercontent.com/tufeeq/ai/main/tag/data/live-quotes.json';
const MEMORY_KEY='tagit_live_rescue_memory_v2';
const MAX_FEED_AGE_MS=3*60*1000;
const MAX_CANDIDATE_AGE_MS=3*60*1000;
const MEMORY_TTL_MS=45*60*1000;
const REQUIRED_SNAPSHOTS=2;
const esc=s=>String(s??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const n=v=>v==null||v===''||!Number.isFinite(Number(v))?null:Number(v);
const fmt=(v,d=2)=>n(v)==null?'—':n(v).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=v=>n(v)==null?'—':`${n(v)>=0?'+':''}${fmt(v)}%`;
const ageMs=v=>{const t=Date.parse(v||'');return Number.isFinite(t)?Date.now()-t:Infinity};
async function getLive(){const r=await fetch(`${LIVE}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`live ${r.status}`);return r.json()}
function loadMem(){try{return JSON.parse(sessionStorage.getItem(MEMORY_KEY)||'{}')}catch{return {}}}
function saveMem(m){try{sessionStorage.setItem(MEMORY_KEY,JSON.stringify(m))}catch{}}
function updateMemory(snapshot,items){const m=loadMem(),now=Date.now();for(const [s,e] of Object.entries(m)){if(now-(e.lastSeen||0)>MEMORY_TTL_MS)delete m[s]}
 for(const x of items){const s=String(x.ticker||'').toUpperCase();if(!s)continue;const e=m[s]||{snapshots:0,lastSnapshot:null,previous:null,current:null,lastSeen:0};if(e.lastSnapshot!==snapshot){e.previous=e.current;e.current={score:n(x.earlyRegimeShiftScore),price:n(x.price),v5:n(x.priceVelocity5mPct),v15:n(x.priceVelocity15mPct)};e.snapshots+=1;e.lastSnapshot=snapshot;e.lastSeen=now;m[s]=e}}
 saveMem(m);return m}
function confirmed(x,e){if(!e||e.snapshots<REQUIRED_SNAPSHOTS)return false;const v5=n(x.priceVelocity5mPct),v15=n(x.priceVelocity15mPct),a5=n(x.volumeAcceleration5m),turn=n(x.turnover5mPctFloat),span=n(x.activeSpanMin),price=n(x.price);if(v5==null||v5<0.8||span==null||span<8)return false;const comparable=x.volumeAccelerationComparable5m===true;const independent=(v15!=null&&v15>=1.2)||(comparable&&a5!=null&&a5>=1.8)||(turn!=null&&turn>=1.0);if(!independent)return false;if(price!=null&&price<1&&turn==null&&!comparable)return false;if(e.previous){const ps=n(e.previous.score),cs=n(x.earlyRegimeShiftScore),pp=n(e.previous.price);if(ps!=null&&cs!=null&&cs<ps-12)return false;if(pp&&price&&price<pp*0.97)return false}return true}
function phase(x){const v=n(x.priceVelocity5mPct)||0,a=x.volumeAccelerationComparable5m===true?(n(x.volumeAcceleration5m)||0):0,s=n(x.earlyRegimeShiftScore)||0;if(v>=3&&a>=2)return'BREAKOUT';if(v>=1.2||a>=2)return'ACCELERATION';if(s>=75)return'IGNITION';return'EXPANSION'}
function reason(x,e,ok){const bits=[];bits.push(ok?`Confirmed ${e?.snapshots||0} snapshots`:`VERIFY ${e?.snapshots||0}/${REQUIRED_SNAPSHOTS}`);if(x.activeSpanMin!=null)bits.push(`Observed ${fmt(x.activeSpanMin,0)}m`);if(x.priceVelocity5mPct!=null)bits.push(`5m ${pct(x.priceVelocity5mPct)}`);if(x.priceVelocity15mPct!=null)bits.push(`15m ${pct(x.priceVelocity15mPct)}`);if(x.volumeAccelerationComparable5m===true&&x.volumeAcceleration5m!=null)bits.push(`Comparable vol ${fmt(x.volumeAcceleration5m)}x`);if(x.turnover5mPctFloat!=null)bits.push(`Float turnover ${fmt(x.turnover5mPctFloat)}%`);bits.push(`PIT ${fmt(x.earlyRegimeShiftScore,0)}`);return bits.join(' • ')}
function failClosed(live,msg){const rows=document.querySelector('#rows');if(rows)rows.innerHTML='';const mt=document.querySelector('#modeText');if(mt)mt.textContent=msg;const hc=document.querySelector('#metricCandidates');if(hc)hc.textContent='0';const md=document.querySelector('#metricDiscover');if(md)md.textContent='0';const d=document.querySelector('#detail');if(d){d.className='detail';d.innerHTML='<div class="gatebox"><b>NO ACTION</b><span>Live evidence is stale or insufficient. Numeric ranking is disabled until fresh multi-snapshot confirmation returns.</span></div>'}}
function rescueRender(live){const rows=document.querySelector('#rows');if(!rows)return;const feedAge=ageMs(live.updatedAtUTC||live.updatedAtET);if(feedAge>MAX_FEED_AGE_MS){failClosed(live,'DATA STALE · NO ACTION');return}const session=String(live.marketClockSession||'').toLowerCase();if(!['pre-market','regular','after-hours'].includes(session)||(+live.freshCount||0)<25){failClosed(live,'LIVE DATA INSUFFICIENT · NO ACTION');return}
 const raw=(live.emergingCandidates||[]).filter(x=>x&&x.ticker&&ageMs(x.timestampET)<=MAX_CANDIDATE_AGE_MS);const mem=updateMemory(String(live.updatedAtUTC||live.updatedAtET||''),raw);const enriched=raw.map(x=>({x,e:mem[String(x.ticker||'').toUpperCase()]}));const good=enriched.filter(z=>confirmed(z.x,z.e)).sort((a,b)=>(n(b.x.earlyRegimeShiftScore)||0)-(n(a.x.earlyRegimeShiftScore)||0));const verify=enriched.filter(z=>!confirmed(z.x,z.e)).sort((a,b)=>(n(b.x.earlyRegimeShiftScore)||0)-(n(a.x.earlyRegimeShiftScore)||0));const show=[...good,...verify].slice(0,20);if(!show.length){failClosed(live,'NO FRESH CANDIDATES · NO ACTION');return}
 rows.innerHTML=show.map(({x,e},i)=>{const ok=confirmed(x,e);const rank=ok?`#${good.findIndex(z=>z.x.ticker===x.ticker)+1}`:'—';const state=ok?'CONFIRMED':'VERIFY';return `<tr data-live-rescue="1"><td><span class="ticker">${esc(x.ticker)}</span></td><td><span class="gate ${state}">${state}</span></td><td><b>${rank}</b></td><td><span class="score">${fmt(x.earlyRegimeShiftScore,0)}</span></td><td><b>${ok?fmt(x.ignitionScore,0):'—'}</b></td><td>${e?.snapshots||0}</td><td>${ok?fmt(x.earlyRegimeShiftScore,0):'—'}</td><td>LIVE</td><td>${x.price==null?'—':'$'+fmt(x.price)}</td><td class="${(n(x.changePct)||0)>=0?'pos':'neg'}">${pct(x.changePct)}</td><td class="signal">${esc(reason(x,e,ok))}</td></tr>`}).join('');
 const hc=document.querySelector('#metricCandidates');if(hc)hc.textContent=good.length;const md=document.querySelector('#metricDiscover');if(md)md.textContent=verify.length;const mp=document.querySelector('#metricAcceleration');if(mp)mp.textContent=good.filter(z=>['ACCELERATION','BREAKOUT','EXPANSION'].includes(phase(z.x))).length;const ms=document.querySelector('#sessionText');if(ms)ms.textContent=String(live.marketClockSession||'unknown').toUpperCase();const mt=document.querySelector('#modeText');if(mt)mt.textContent=good.length?'LIVE RADAR · CONFIRMED':'LIVE RADAR · VERIFYING';const as=document.querySelector('#asOfText');if(as&&live.updatedAtET)as.textContent=new Date(live.updatedAtET).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})+' ET';const detail=document.querySelector('#detail');if(detail){detail.className='detail';detail.innerHTML=`<div class="gatebox ${good.length?'CONFIRMED':'VERIFY'}"><b>${good.length?'MULTI-SNAPSHOT CONFIRMED':'VERIFICATION IN PROGRESS'}</b><span>${good.length} confirmed, ${verify.length} verifying. A single 5-minute burst can no longer receive a numeric #1 rank. Execution remains unverified.</span></div>`}}
async function tick(){try{rescueRender(await getLive())}catch(e){console.warn('TAGit live rescue unavailable',e);failClosed(null,'LIVE FEED ERROR · NO ACTION')}}
setTimeout(tick,700);setInterval(tick,10000);
