const LIVE='../tag/data/live-quotes.json';
const esc=s=>String(s??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=(n,d=2)=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=n=>n==null||!Number.isFinite(+n)?'—':`${+n>=0?'+':''}${fmt(+n)}%`;
async function getLive(){const r=await fetch(`${LIVE}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`live ${r.status}`);return r.json()}
function phase(x){const v=+x.priceVelocity5mPct||0,a=+x.volumeAcceleration5m||0,s=+x.earlyRegimeShiftScore||0;if(v>=3&&a>=2)return'BREAKOUT';if(v>=1.2||a>=2)return'ACCELERATION';if(s>=75)return'IGNITION';return'EXPANSION'}
function reason(x){const bits=[];if(x.priceVelocity5mPct!=null)bits.push(`5m ${pct(x.priceVelocity5mPct)}`);if(x.volumeAcceleration5m!=null)bits.push(`Vol accel ${fmt(x.volumeAcceleration5m)}x`);if(x.turnover5mPctFloat!=null)bits.push(`Float turnover ${fmt(x.turnover5mPctFloat)}%`);bits.push(`Live PIT score ${fmt(x.earlyRegimeShiftScore,0)}`);return bits.join(' • ')}
function rescueRender(live){const rows=document.querySelector('#rows');if(!rows)return;const staleText=(document.querySelector('#modeText')?.textContent||'').toUpperCase();const currentRows=[...rows.querySelectorAll('tr[data-symbol]')];const shouldRescue=!currentRows.length||staleText.includes('DEGRADED')||staleText.includes('NO VERIFIED');if(!shouldRescue)return;
 const items=(live.emergingCandidates||[]).filter(x=>x&&x.ticker).slice(0,20);if(!items.length)return;
 rows.innerHTML=items.map((x,i)=>`<tr data-live-rescue="1"><td><span class="ticker">${esc(x.ticker)}</span></td><td><span class="gate DISCOVER">DISCOVER</span></td><td><b>#${i+1}</b></td><td><span class="score">${fmt(x.earlyRegimeShiftScore,0)}</span></td><td><b>${fmt(x.ignitionScore,0)}</b></td><td>—</td><td>${fmt(x.earlyRegimeShiftScore,0)}</td><td>LIVE</td><td>${x.price==null?'—':'$'+fmt(x.price)}</td><td class="${(+x.changePct||0)>=0?'pos':'neg'}">${pct(x.changePct)}</td><td class="signal">${esc(reason(x))}</td></tr>`).join('');
 const md=document.querySelector('#metricDiscover');if(md)md.textContent=items.length;const mp=document.querySelector('#metricAcceleration');if(mp)mp.textContent=items.filter(x=>['ACCELERATION','BREAKOUT','EXPANSION'].includes(phase(x))).length;const ms=document.querySelector('#sessionText');if(ms)ms.textContent=String(live.marketClockSession||'unknown').toUpperCase();const mt=document.querySelector('#modeText');if(mt)mt.textContent='LIVE RADAR · RESCUE FEED';const as=document.querySelector('#asOfText');if(as&&live.updatedAtET)as.textContent=new Date(live.updatedAtET).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})+' ET';
 const detail=document.querySelector('#detail');if(detail){detail.className='detail';detail.innerHTML=`<div class="gatebox DISCOVER"><b>LIVE RADAR RESCUE</b><span>${items.length} emerging candidates from current 1-minute point-in-time quote feed. These are discovery candidates, not execution-verified recommendations.</span></div>`;}
}
async function tick(){try{const live=await getLive();if(['pre-market','regular','after-hours'].includes(String(live.marketClockSession||'').toLowerCase())&&(+live.freshCount||0)>=25)rescueRender(live)}catch(e){console.warn('TAGit live rescue unavailable',e)}}
setTimeout(tick,1200);setInterval(tick,15000);
