const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const price=n=>number(n,n<1?4:2),percent=n=>Number.isFinite(n)?`${n>0?'+':''}${number(n)}%`:'—';
const time=t=>t?new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t)):'—';
const states={DETECTED:'نشاط غير اعتيادي',ACTIVE:'اندفاع نشط',PULLBACK:'تراجع تحت المراقبة',RECOVERY_PENDING:'استعادة قيد التأكيد',RECOVERY_CONFIRMED:'استعادة مؤكدة تجريبيًا',FAILED:'ضعف أو فشل',RENEWED:'تجدد الفرصة'};
const phases={OPENING:'بداية التداول',MORNING:'الصباح',MIDDAY:'منتصف الجلسة',FINAL:'الفترة الأخيرة',PREMARKET:'قبل الافتتاح',AFTERHOURS:'بعد الإغلاق'};
const reasons={POINT_IN_TIME_METADATA_MISSING:'الأهلية التاريخية غير موثقة',SHARIA_UNVERIFIED:'التوافق الشرعي غير موثّق',FRESH_EXECUTION_QUOTE_MISSING:'العرض والطلب غير متاحين عند القرار',DATA_QUALITY:'جودة البيانات غير كافية للدخول',RECOVERY_NOT_CONFIRMED:'انتظار استعادة مؤكدة',ENTRY_EXTENDED:'امتداد سعري مرتفع',SESSION_END_APPROACHING:'اقتراب نهاية الجلسة',STALE_METADATA:'بيانات الأهلية متأخرة',MARKET_CAP_UNKNOWN:'القيمة السوقية غير معروفة',MARKET_CAP_OUT_OF_SCOPE:'القيمة السوقية خارج النطاق',WIDE_SPREAD:'سبريد مرتفع',MISSING_SOURCE:'مصدر الأهلية غير موثق'};
const families={FIRST_EXECUTABLE:'أول فرصة تنفيذ',WAIT_RECOVERY:'انتظار الاستعادة',FAILURE_REENTRY:'الخروج عند الفشل وإعادة الدخول'};
const API=location.hostname==='tufeeq.github.io'?'https://tagit-next-quotes.onrender.com':'';
let archive=[],rows=[],summary=null,mode='REPLAY',tab='watch',selected=null,timelineIndex=null,liveTimer=null,busy=false;
function badge(state){return `<span class="badge ${state==='FAILED'?'red':state==='PULLBACK'||state==='RECOVERY_PENDING'?'amber':state==='DETECTED'?'neutral':''}">${esc(states[state]||state)}</span>`;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500);}
async function get(url){const r=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json();}
function filtered(){return rows.filter(o=>(!$('#session').value||o.session===$('#session').value)&&(!$('#search').value||o.symbol.includes($('#search').value.trim().toUpperCase()))&&(!$('#stage').value||o.state===$('#stage').value)&&(!$('#verified-only').checked||o.sharia?.status==='COMPLIANT'));}
function dates(){const chosen=$('#session').value;const days=[...new Set(rows.map(x=>x.session))].sort().reverse();$('#session').innerHTML='<option value="">جميع الجلسات</option>'+days.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');$('#session').value=days.includes(chosen)?chosen:(days[0]||'');}
function render(){const list=filtered(),recovered=list.filter(o=>o.timeline?.some(e=>e.to==='RECOVERY_CONFIRMED')).length,ready=list.filter(o=>o.entryReady),complete=list.filter(o=>o.outcome?.complete).length;
 $('#stats').innerHTML=[['فرص محفوظة',list.length,'الإشارة الأولى لا تُحذف','◈'],['استعادة مؤكدة تجريبيًا',recovered,'سبق رصدها خلال الجلسة','↗'],['شروط دخول مكتملة',ready.length,'يشمل الأهلية والشرعية والتنفيذ','◎'],['مسارات مكتملة',mode==='REPLAY'?`${complete} / ${list.length}`:'—',mode==='REPLAY'?'بقية الجلسة بعد الاكتشاف':'لم تنتهِ المراقبة بعد','◷']].map(([label,value,note,icon],i)=>`<div class="stat"><span>${label}</span><span class="marker">${icon}</span><strong class="${i===1?'green':''} num">${value}</strong><small>${note}</small></div>`).join('');
 $('#watch-count').textContent=list.length;$('#ready-count').textContent=ready.length;
 $('#opportunity-rows').innerHTML=list.length?list.map(o=>`<tr class="${o.id===selected?'selected-row':''}"><td><div class="symbol">${esc(o.symbol)}</div><small>${esc(o.feed?.toUpperCase())} · ${esc(o.session)}</small></td><td><span class="number num">$${price(o.current_price)}</span><small>${time(o.price_at)} NY · شمعة دقيقة</small></td><td><span class="num">$${price(o.first_price)}</span><small>${time(o.first_at)} NY</small></td><td>${badge(o.state)}<small>${phases[o.sessionPhase]||'—'} · موجة ${o.wave}</small></td><td><span class="num">${number(o.ageMinutes,0)}</span> دقيقة<small>${o.recoveryAttempts} محاولة استعادة</small></td><td><span class="badge ${o.quality?.missingMinutes?'amber':'neutral'}">${o.quality?.missingMinutes?'فجوات في المسار':'مكتملة ضمن النافذة'}</span><small>${o.quality?.missingMinutes??'—'} دقيقة مفقودة · تأخر ${number((o.quality?.latencyMs??0)/1000,0)} ث</small></td><td><span class="badge ${o.sharia?.status==='COMPLIANT'?'':'neutral'}">${o.sharia?.status==='COMPLIANT'?'متوافق موثّق':'غير معروفة'}</span><small>${esc(o.sharia?.source||'لا يوجد مصدر مؤهل')}</small></td><td><button class="link-button detail-open" data-id="${o.id}">التفاصيل ←</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">لا توجد فرص تطابق هذه الفلاتر.<br>الحالة غير المعروفة لا تتحول إلى أهلية مؤكدة.</td></tr>';
 $('#ready-list').innerHTML=ready.length?ready.map(o=>`<button class="secondary detail-open" data-id="${o.id}">${esc(o.symbol)} · فحص الدليل</button>`).join(''):'<span class="ready-icon">◎</span><div><strong>لا توجد فرصة مكتملة الشروط في هذا العرض.</strong><p>في الأرشيف، بيانات الأهلية التاريخية والشرعية وعروض التنفيذ غير متوافرة. تأكيد مرحلة الحركة وحده لا يكفي للدخول.</p></div>';
 $('#history-list').innerHTML=list.length?list.map(o=>`<article class="history-card"><div><strong>${esc(o.symbol)}</strong><br><small>${o.session}</small></div><div><p>اكتشاف أول عند <span class="num">$${price(o.first_price)}</span> · ${time(o.first_at)} NY</p><small>${o.timeline.filter(x=>x.kind==='STATE').length} انتقالات · ${o.timeline.filter(x=>x.kind==='BASELINE_REDETECTION').length} إشارات متكررة مرتبطة</small></div><button class="secondary detail-open" data-id="${o.id}">افتح المسار ←</button></article>`).join(''):'<div class="empty">لا توجد سجلات مطابقة.</div>';
 $$('.detail-open').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));
 if(selected&&!list.some(o=>o.id===selected)){$('#details').innerHTML='';selected=null;}
 if(selected)renderDetail();renderQuality(list);
}
function chart(o,cutoff){const bs=(o.bars||[]).filter(b=>b[0]+60000<=cutoff);if(!bs.length)return '<div class="empty">مسار الشموع غير متاح في هذا الوضع.</div>';
 const w=650,h=225,pad=30,min=Math.min(...bs.map(b=>b[3])),max=Math.max(...bs.map(b=>b[2])),lo=bs[0][0],hi=bs.at(-1)[0],x=t=>pad+(t-lo)/Math.max(60000,hi-lo)*(w-2*pad),y=v=>h-pad-(v-min)/Math.max(max-min,.0001)*(h-2*pad);
 let paths=[],path='',gaps=[];bs.forEach((b,i)=>{const gap=i&&b[0]-bs[i-1][0]>60000;if(gap){paths.push(path);path='';gaps.push(`<line x1="${x(bs[i-1][0])}" y1="${y(bs[i-1][4])}" x2="${x(b[0])}" y2="${y(b[4])}" stroke="#d1ac69" stroke-width="1.1" stroke-dasharray="3 4"/>`);}path+=(path?' L':'M')+x(b[0]).toFixed(2)+' '+y(b[4]).toFixed(2);});if(path)paths.push(path);
 const grid=[0,.25,.5,.75,1].map(r=>{const v=min+(max-min)*r,yy=y(v);return `<line x1="${pad}" y1="${yy}" x2="${w-pad}" y2="${yy}" stroke="#edf1ee"/><text x="${w-pad+5}" y="${yy+3}" font-size="8" fill="#94a59b">${price(v)}</text>`;}).join('');
 const first=Date.parse(o.first_at)-60000;const mark=first>=lo&&first<=hi?`<line x1="${x(first)}" y1="15" x2="${x(first)}" y2="${h-pad}" stroke="#b2c9c0" stroke-dasharray="4 4"/><circle cx="${x(first)}" cy="${y(o.first_price)}" r="4" fill="#143e36"/><text x="${Math.min(x(first)+7,w-100)}" y="18" font-size="9" fill="#698b7b">FIRST DETECTION</text>`:'';
 return `<svg class="chart" role="img" aria-label="مسار الأسعار المرصودة للسهم ${esc(o.symbol)}؛ الخط المتقطع يمثل فجوات" viewBox="0 0 ${w} ${h}">${grid}${gaps.join('')}${paths.map(d=>`<path d="${d}" fill="none" stroke="#178567" stroke-width="2.2" stroke-linecap="round"/>`).join('')}${mark}</svg><div class="chart-labels"><span>${time(bs.at(-1)[0])} NY</span><span>${time(bs[0][0])} NY</span></div>`;
}
function openDetail(id){selected=id;timelineIndex=null;if(tab!=='watch')switchTab('watch');render();$('#details').scrollIntoView({behavior:'smooth',block:'start'});}
function renderDetail(){const o=rows.find(x=>x.id===selected);if(!o)return;const events=o.timeline.filter(x=>['DISCOVERY','STATE'].includes(x.kind)),index=timelineIndex??events.length,at=index<events.length?Date.parse(events[index].at):Date.parse(o.updated_at),e=index<events.length?events[index]:null;
 const current=e?.to||o.state,f=e?.features||(!e?o.features:null),q=e?.quality||(!e?o.quality:o.first_quality),shownPrice=e?.price??o.current_price;
 const title=e?'التقييم المحفوظ عند الانتقال':'آخر تقييم محفوظ';
 $('#details').innerHTML=`<article class="detail-panel"><div class="detail-heading"><div><h2><span class="num">${esc(o.symbol)}</span> <span class="num">$${price(shownPrice)}</span></h2><p>${esc(o.session)} · ${title} · ${time(at)} NY · ${mode==='REPLAY'?'إعادة تشغيل تاريخي':'رصد موازٍ'}</p></div><div>${badge(current)} <button class="link-button" id="close-detail" aria-label="إغلاق التفاصيل">✕</button></div></div><div class="detail-grid"><div class="chart-box" id="chart">${chart(o,at)}<p class="chart-note">خط متقطع = بيانات غير مرصودة. القمة ليست سعر خروج قابلًا للتنفيذ.</p><label class="range-control">اعرض حتى هذا التقييم <input id="timeline-range" type="range" min="0" max="${events.length}" value="${index}" aria-label="وقت إعادة العرض"><span class="num">${time(at)} NY</span></label></div><div class="evidence"><h3>ما الذي يدعم التقييم؟</h3><div class="fact"><span>أول اكتشاف</span><strong class="num">$${price(o.first_price)} · ${time(o.first_at)}</strong></div><div class="fact"><span>حجم نسبي · آخر 3 شموع مرصودة</span><strong class="num">${number(f?.volumeRatio3ObservedBars)}×</strong></div><div class="fact"><span>VWAP النظامية · المتاح فقط</span><strong class="num">${price(f?.vwapRegularObserved)}</strong></div><div class="fact"><span>حجم نسبي لنفس الوقت تاريخيًا</span><strong>${f?.sameTimeRelativeVolume?number(f.sameTimeRelativeVolume)+'×':'سجل غير كافٍ'}</strong></div><div class="fact"><span>دقائق متصلة في نهاية النافذة</span><strong class="num">${q?.contiguousBars??'—'}</strong></div><div class="fact"><span>مستوى استعادة معروف آنذاك</span><strong class="num">${price(e?.level??(!e?o.recoveryLevel:null))}</strong></div><div class="scenario"><b>ما الذي ينتظر التأكيد؟</b>${e?'هذا تقييم مؤرّخ؛ المستويات محسوبة بالبيانات المتاحة آنذاك.':esc(o.awaiting)}<br><b>الإبطال</b>${e?'إغلاقان متتاليان دون الدعم مع هامش التذبذب المحسوب وقت القرار.':`إغلاقان دون مستوى الفشل الحالي <span class="num">$${price(o.invalidation?.failureLevel)}</span>.`}<br><b>الدخول التجريبي</b>${e?'لم تُوثّق أهلية تاريخية أو عروض تنفيذ لهذا التقييم.':(o.blocking||[]).slice(0,3).map(x=>esc(reasons[x]||x)).join(' · ')}</div></div></div><div class="timeline">${events.filter(x=>Date.parse(x.at)<=at).slice(-9).map(x=>`<div class="timeline-item"><span class="num">${time(x.at)} NY</span><strong>${states[x.to]||'اكتشاف'}</strong><small class="num">$${price(x.price)}</small></div>`).join('')}</div><div class="scenario"><b>الأخبار المتاحة عند هذا التقييم</b>${(o.news||[]).filter(n=>Date.parse(n.received_at)<=at&&Date.parse(n.published_at)<=at).map(n=>`${esc(n.headline)} · ${esc(n.source)} · النشر ${time(n.published_at)} / الوصول ${time(n.received_at)}`).join('<br>')||'لا توجد أخبار موثقة بوقت وصولها في هذا السجل. هذا لا يثبت عدم وجود خبر.'}</div></article>`;
 $('#timeline-range').onchange=e=>{timelineIndex=Number(e.target.value);renderDetail();};$('#close-detail').onclick=()=>{selected=null;$('#details').innerHTML='';};
}
function renderResearch(){const s=summary;if(!s)return;$('#research-content').innerHTML=`<div class="research-head"><div><h2>الاكتشاف محفوظ. أفضلية التداول لم تثبت.</h2><p>نفس 210 فرص أولى، و322 إشارة أصلية مرتبطة. العينة مكشوفة مسبقًا، والأرقام أدناه تشخيص مشروط للتنفيذ؛ لا تمثل اختبارًا مستقلًا أو عائد محفظة.</p></div><span class="badge amber">لا ترقية للقواعد</span></div><div class="table-wrap"><table><thead><tr><th>الصعود بعد الاكتشاف</th><th>بلوغ مرصود</th><th>عدم بلوغ بمسار كامل</th><th>نتيجة مجهولة</th></tr></thead><tbody>${[10,20,50].map(n=>`<tr><td class="num">+${n}%</td><td>${s.outcomes[n].observed}</td><td>${s.outcomes[n].notHit}</td><td>${s.outcomes[n].unknown}</td></tr>`).join('')}</tbody></table></div><div class="panel"><h3>مقارنة نماذج الدخول والخروج · افتراضات تنفيذ معلنة</h3><p>الكمية 100 سهم، سبريد مفترض 40 نقطة أساس، انزلاق 10 نقاط لكل طرف ورسوم نقطة واحدة لكل طرف. التنفيذ عند أول افتتاح دقيقة بعد مهلة القرار، والقدرة تقاس بحجم الدقيقة السابقة. حالات الأهلية التاريخية المؤكدة: <b>صفر</b>. تختلف العينات القابلة للتقييم؛ لا يصح ترتيب النماذج من المتوسط وحده.</p><div class="table-wrap"><table><thead><tr><th>النموذج</th><th>صفقات قابلة للتشخيص</th><th>مسار مجهول</th><th>متوسط صافٍ مفترض</th><th>الوسيط</th><th>المتوسط دون أكبر رابح</th></tr></thead><tbody>${Object.entries(s.diagnostic).map(([k,v])=>`<tr><td>${families[k]}</td><td>${v.scorableTrades}</td><td>${v.unknownTrades}</td><td class="num">${percent(v.meanNetPct)}</td><td class="num">${percent(v.medianNetPct)}</td><td class="num">${percent(v.meanWithoutBest)}</td></tr>`).join('')}</tbody></table></div></div><div class="quality-grid"><div class="quality-card"><h3>فصل زمني بلا ادعاء استقلال</h3><p>6 جلسات تطوير، جلستان للتحقق التشخيصي، وجلستان للاختبار التشخيصي. جميعها استُخدمت في أبحاث سابقة؛ نحتاج جلسات جديدة محفوظة بعد تجميد التعريفات لاختبار مستقل.</p><span class="badge neutral">${s.walkForward.length} نوافذ Walk-forward تشخيصية</span></div><div class="quality-card"><h3>ما لم نتمكن من قياسه</h3><p>الفرص المفقودة في السوق كاملًا، وحركة قبل الافتتاح، وتأثير الخبر عند وصوله، وتدفق الأوامر: لا تسمح التغطية الحالية بإثباتها. لا نستخدم أهلية اليوم في التاريخ.</p><span class="badge amber">95% أو أي دقة نهائية: غير متاحة</span></div></div><div class="panel"><h3>حساسية السبريد وحجم الصفقة</h3><div class="table-wrap"><table><thead><tr><th>السبريد المفترض</th><th>الكمية</th><th>أول تنفيذ · عدد / متوسط</th><th>استعادة · عدد / متوسط</th><th>إعادة دخول · عدد / متوسط</th></tr></thead><tbody>${s.sensitivity.map(r=>`<tr><td>${r.spreadBps} نقطة أساس</td><td class="num">${r.quantity}</td>${Object.values(r.summary).map(v=>`<td class="num">${v.scorableTrades} / ${percent(v.meanNetPct)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;}
function renderQuality(list){const missing=list.reduce((a,o)=>a+(o.quality?.missingMinutes||0),0);$('#quality-content').innerHTML=`<div class="research-head"><div><h2>نعرض ما نعرفه، وما ينقصه الدليل.</h2><p>جودة المصدر منفصلة عن حالة الحركة. لا نعوّض الدقيقة المفقودة بسعر سابق ولا ننسب الحجم تلقائيًا إلى أموال جديدة.</p></div></div><div class="quality-grid"><div class="quality-card"><h3>التاريخي: SIP · الحي: IEX</h3><p>SIP تغطية مجمعة في الأرشيف. IEX يغطي سوقًا واحدًا في الاتصال الحالي. لا نفترض تكافؤ الحجم أو الإشارات بينهما.</p><span class="badge amber">المقارنة بين المصدرين محدودة</span></div><div class="quality-card"><h3>الدقائق المفقودة في العرض الحالي</h3><strong class="num" style="font-size:30px">${number(missing,0)}</strong><p>السبب غير معروف ما لم يرد دليل على توقف تداول أو دقيقة بلا صفقات أو انقطاع تغذية. هذه فجوات نوافذ الرصد وليست عدد فجوات السوق كله.</p></div><div class="quality-card"><h3>القيمة السوقية والشرعية</h3><p>النطاق الافتراضي ناسداك وأقل من 100 مليون دولار. لا توجد أهلية تاريخية موثقة لهذه العينة. المجهول يظهر كما هو، ويمنع انتقال الفرصة إلى قائمة الدخول المكتمل.</p><span class="badge neutral">مصادر تاريخية مؤهلة: غير متصلة</span></div><div class="quality-card"><h3>استمرارية الخادم</h3><p>الخادم الحالي يعمل عند الطلب. قاعدة SQLite تدعم الاستئناف عند ثبات القرص، لكن مساحة الخادم الحالية مؤقتة ولا يثبت حفظها عبر إعادة النشر. التشغيل المستمر والتخزين الدائم غير مفعّلين.</p><span class="badge amber">بوابة إطلاق لم تُجتز بعد</span></div><div class="quality-card"><h3>توقيت البيانات والتصحيحات</h3><p>UTC في السجل، ونيويورك للجلسات. وقت الوصول الفعلي محفوظ في الرصد الجديد. أرشيف الدراسة يفترض إتاحة الشمعة عند اكتمالها؛ لا يتوفر سجل وصولها الأصلي.</p></div><div class="quality-card"><h3>سجل القرار قابل للمراجعة</h3><p>الاكتشاف الأول وانتقالات الحالة محفوظة مع إصدار القواعد وجودة البيانات. التصحيحات وإعادة التحليل لا تستبدل التقييم الأصلي. لا يوجد مسار لإرسال أوامر تداول.</p></div></div>`;}
function switchTab(name){tab=name;$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.tab-panel').forEach(x=>x.classList.toggle('hidden',x.id!==name));$('#details').style.display=name==='watch'?'':'none';if(name==='research')renderResearch();}
async function liveRefresh(){if(busy||mode!=='SHADOW')return;busy=true;$('#connection').textContent='جارٍ الاتصال بالرصد الحي…';try{await get(API+'/api/scanner');const data=await get(API+'/api/elite/opportunities');rows=data.opportunities||[];dates();render();const status=data.status||{};$('#connection').textContent=status.lastObservedAt?'رصد IEX · '+time(status.lastObservedAt)+' NY':'متصل · انتظار اكتمال الرصد';$('#footer-data').textContent=`IEX · تخزين ${status.storage==='EPHEMERAL_SQLITE'?'مؤقت':'غير مثبت الاستمرارية'} · رصد موازٍ`;if(status.lastError)toast('حالة الرصد: '+status.lastError);}catch{$('#connection').textContent='الاتصال غير متاح';toast('تعذّر جلب الرصد الحي. لم نستبدله بأسعار افتراضية.');}finally{busy=false;}}
function setMode(next){mode=next;clearInterval(liveTimer);selected=null;$('#details').innerHTML='';$('#replay-mode').classList.toggle('selected',mode==='REPLAY');$('#live-mode').classList.toggle('selected',mode==='SHADOW');if(mode==='REPLAY'){rows=archive;dates();$('#connection').textContent='أرشيف موثّق · 10 جلسات';$('#mode-notice').innerHTML='<span class="notice-icon">◷</span><div><strong>أرشيف حقيقي · نتائج بحثية</strong><span>بيانات SIP من 24 أغسطس إلى 4 سبتمبر 2026. لا تعني هذه الشاشة وجود فرص حية الآن.</span></div><span class="badge amber">غير مثبت تداوليًا</span>';$('#footer-data').textContent='UTC للتخزين · نيويورك لتقسيم الجلسة';render();}else{rows=[];dates();render();$('#mode-notice').innerHTML='<span class="notice-icon">◉</span><div><strong>رصد حي موازٍ · IEX</strong><span>تحديث أثناء فتح الصفحة. المصدر سوق واحد، والتخزين الحالي مؤقت؛ لا توجد توصيات تنفيذ أو خدمة مستمرة مضمونة.</span></div><span class="badge amber">تجريبي</span>';liveRefresh();liveTimer=setInterval(liveRefresh,30000);}}
$('#search').oninput=render;$('#session').onchange=render;$('#stage').onchange=render;$('#verified-only').onchange=render;$$('.nav').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#replay-mode').onclick=()=>setMode('REPLAY');$('#live-mode').onclick=()=>setMode('SHADOW');$('#refresh').onclick=()=>mode==='SHADOW'?liveRefresh():toast('الأرشيف ثابت ومحفوظ بإصدار 25 سبتمبر 2026.');
$('#export').onclick=()=>{const b=new Blob([JSON.stringify({product:'TAG elite',mode,version:summary?.version,exportedAt:new Date().toISOString(),originalEvaluations:filtered(),notPortfolioReturns:true},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='tag-elite-records.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('تم تصدير السجلات مع مصدرها وإصدارها.');};
try{summary=await get('./data/summary.json');const dates=[...summary.partitions.development,...summary.partitions.validationDiagnostic,...summary.partitions.testDiagnostic];archive=(await Promise.all(dates.map(async d=>{const r=await fetch('./data/'+d+'.json.gz');if(!r.ok)throw Error('ARCHIVE_UNAVAILABLE');return new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json();}))).flat();setMode('REPLAY');renderResearch();}catch{$('#connection').textContent='تعذّر تحميل الأرشيف';$('#opportunity-rows').innerHTML='<tr><td colspan="8" class="empty">لم نستطع تحميل ملفات النتائج. أعد تحميل الصفحة.</td></tr>';}
