import {priceEvidence,reviewEvidence,visibleBars,newsEvidence,safeNewsUrl} from './presentation.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const price=n=>number(n,n<1?4:2),percent=n=>Number.isFinite(n)?`${n>0?'+':''}${number(n)}%`:'—';
const time=t=>t?new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t)):'—';
const states={DETECTED:'نشاط غير اعتيادي',ACTIVE:'اندفاع نشط',PULLBACK:'تراجع تحت المراقبة',RECOVERY_PENDING:'استعادة قيد التأكيد',RECOVERY_CONFIRMED:'استعادة مؤكدة تجريبيًا',FAILED:'ضعف أو فشل',RENEWED:'تجدد الفرصة'};
const phases={OPENING:'بداية التداول',MORNING:'الصباح',MIDDAY:'منتصف الجلسة',FINAL:'الفترة الأخيرة',PREMARKET:'قبل الافتتاح',AFTERHOURS:'بعد الإغلاق'};
const reasons={POINT_IN_TIME_METADATA_MISSING:'الأهلية التاريخية غير موثقة',SHARIA_UNVERIFIED:'التوافق الشرعي غير موثّق',FRESH_EXECUTION_QUOTE_MISSING:'العرض والطلب غير متاحين عند القرار',DATA_QUALITY:'جودة البيانات غير كافية للدخول',RECOVERY_NOT_CONFIRMED:'انتظار استعادة مؤكدة',ENTRY_EXTENDED:'امتداد سعري مرتفع',SESSION_END_APPROACHING:'اقتراب نهاية الجلسة',STALE_METADATA:'بيانات الأهلية متأخرة',MARKET_CAP_UNKNOWN:'القيمة السوقية غير معروفة',MARKET_CAP_OUT_OF_SCOPE:'القيمة السوقية خارج النطاق',WIDE_SPREAD:'سبريد مرتفع',MISSING_SOURCE:'مصدر الأهلية غير موثق'};
const families={FIRST_EXECUTABLE:'أول فرصة تنفيذ',WAIT_RECOVERY:'انتظار الاستعادة',FAILURE_REENTRY:'الخروج عند الفشل وإعادة الدخول'};
const API=location.hostname==='tufeeq.github.io'?'https://tagit-next-quotes.onrender.com':'';
let archive=[],rows=[],summary=null,mode='REPLAY',tab='watch',selected=null,timelineIndex=null,liveTimer=null,busy=false,clockOffset=0,liveStatus=null;
const viewTime=()=>Date.now()+clockOffset;
const evidence=o=>priceEvidence(o,mode==='SHADOW'?viewTime():Date.parse(o.updated_at),mode==='SHADOW');
const review=o=>reviewEvidence(o,mode==='SHADOW'?viewTime():Date.parse(o.updated_at),mode==='SHADOW');
const ageText=ms=>ms===null?'العمر غير معروف':ms<60000?`${number(ms/1000,0)} ث`:`${number(ms/60000,1)} د`;
const changed=n=>`<span class="change ${n<0?'negative':n>0?'positive':''} num">${percent(n)}</span>`;
const priceNote=p=>`${p.kind==='TRADE'?'آخر صفقة IEX':'إغلاق دقيقة'} · ${time(p.at)} NY${mode==='SHADOW'?' · قبل '+ageText(p.ageMs):''}`;
const blockText=o=>(o.blocking||[]).map(x=>reasons[x]||x).join(' · ');
function badge(state){return `<span class="badge ${state==='FAILED'?'red':state==='PULLBACK'||state==='RECOVERY_PENDING'?'amber':state==='DETECTED'?'neutral':''}">${esc(states[state]||state)}</span>`;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3500);}
async function get(url){const r=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json();}
function filtered(){return rows.filter(o=>(!$('#session').value||o.session===$('#session').value)&&(!$('#search').value||o.symbol.includes($('#search').value.trim().toUpperCase()))&&(!$('#stage').value||o.state===$('#stage').value)&&(!$('#verified-only').checked||o.sharia?.status==='COMPLIANT'));}
function dates(){const chosen=$('#session').value;const days=[...new Set(rows.map(x=>x.session))].sort().reverse();$('#session').innerHTML='<option value="">جميع الجلسات</option>'+days.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');$('#session').value=days.includes(chosen)?chosen:(days[0]||'');}
function render(){
 const list=filtered(),ready=list.filter(o=>o.entryReady),paused=list.filter(o=>review(o).paused),below=list.filter(o=>evidence(o).change<0);
 $('#stats').innerHTML=[['فرص تحت المتابعة',list.length,'تشمل الاكتشافات السابقة'],['أقل من سعر الاكتشاف',below.length,'تغير سعري مرصود'],['شروط دخول مكتملة',ready.length,'الأهلية وجودة التنفيذ'],['تقييم يحتاج بيانات',paused.length,'مرحلة معلّقة أو سعر متأخر']].map(([label,value,note],i)=>`<div class="stat"><span>${label}</span><strong class="${i===1&&value?'negative':''} num">${value}</strong><small>${note}</small></div>`).join('');
 $('#watch-count').textContent=list.length;$('#ready-count').textContent=ready.length;
 $('#watch-context').textContent=mode==='SHADOW'?'السعر الأخير منفصل عن تقييم المرحلة':'تقييم نهاية الجلسة في الأرشيف';
 $('#opportunity-rows').innerHTML=list.length?list.map(o=>{const p=evidence(o),r=review(o);return `<tr class="${o.id===selected?'selected-row':''}"><td><div class="symbol">${esc(o.symbol)}</div><small>${esc(o.feed?.toUpperCase())} · ${esc(o.session)}</small></td><td><span class="number num">$${price(p.price)}</span> ${changed(p.change)}<small>${priceNote(p)}${p.stale?' · متأخر':''}</small></td><td><span class="num">$${price(o.first_price)}</span><small>${time(o.first_at)} NY</small></td><td><span class="badge ${r.paused?'amber':o.state==='FAILED'?'red':'neutral'}">${esc(r.title)}</span><small>${esc(states[o.state])}</small></td><td><span class="num">${number(o.ageMinutes,0)}</span> دقيقة<small>${phases[o.sessionPhase]||'—'}</small></td><td><span class="badge ${o.quality?.missingMinutes?'amber':'neutral'}">${o.quality?.contiguousBars??0} دقائق متصلة</span><small>${o.quality?.missingMinutes??'—'} دقيقة مفقودة في النافذة</small></td><td><span class="badge neutral">${o.sharia?.status==='COMPLIANT'?'متوافق موثّق':'غير موثّق'}</span><small>${esc(o.sharia?.source||'مصدر غير متصل')}</small></td><td><button class="secondary detail-open" data-id="${o.id}">عرض المسار</button></td></tr>`;}).join(''):'<tr><td colspan="8" class="empty">لم تُسجّل فرص مطابقة في هذا العرض.</td></tr>';
 $('#mobile-opportunities').innerHTML=list.length?list.map(o=>{const p=evidence(o),r=review(o);return `<article class="opportunity-card ${o.id===selected?'selected-card':''}"><div class="card-top"><div><strong class="symbol">${esc(o.symbol)}</strong><small>${esc(o.feed?.toUpperCase())} · ${esc(o.session)}</small></div><div class="card-price"><strong class="num">$${price(p.price)}</strong>${changed(p.change)}<small>منذ الاكتشاف</small></div></div><p class="price-timestamp ${p.stale?'negative':''}">${priceNote(p)}${p.stale?' · سعر متأخر':''}</p><div class="card-discovery"><span>أول اكتشاف <b class="num">$${price(o.first_price)}</b> · <b class="num">${time(o.first_at)} NY</b></span><span>${number(o.ageMinutes,0)} دقيقة</span></div><div class="movement-summary"><strong class="${r.paused?'warning':''}">${esc(r.title)}</strong><span>المرحلة المحفوظة: ${esc(states[o.state])}</span><p>${esc(r.explanation)}</p></div><div class="card-bottom"><span class="badge ${o.entryReady?'':'amber'}">${o.entryReady?'شروط تجريبية مكتملة':'شروط الدخول غير مكتملة'}</span><button class="secondary detail-open" data-id="${o.id}">المسار والتفاصيل ←</button></div></article>`;}).join(''):'<div class="empty">لم تُسجّل فرص مطابقة في هذا العرض.</div>';
 $('#ready-list').innerHTML=ready.length?ready.map(o=>`<button class="secondary detail-open" data-id="${o.id}">${esc(o.symbol)} · فحص الدليل</button>`).join(''):`<div><strong>لا توجد فرصة مكتملة الشروط.</strong><p>${mode==='SHADOW'?'التوثيق الشرعي غير متاح من المصدر الحالي. تُعرض أسباب المنع الأخرى لكل سهم في تفاصيله.':'بيانات الأهلية التاريخية والشرعية وعروض التنفيذ غير متوافرة في الأرشيف.'}</p></div>`;
 $('#history-list').innerHTML=list.length?list.map(o=>`<article class="history-card"><div><strong>${esc(o.symbol)}</strong><br><small>${o.session}</small></div><div><p>اكتشاف أول <span class="num">$${price(o.first_price)}</span> · ${time(o.first_at)} NY</p><small>${o.timeline.filter(x=>x.kind==='STATE').length} انتقالات محفوظة · ${o.timeline.filter(x=>x.kind==='BASELINE_REDETECTION').length} إشارات متكررة مرتبطة</small></div><button class="secondary detail-open" data-id="${o.id}">عرض المسار</button></article>`).join(''):'<div class="empty">لا توجد سجلات مطابقة.</div>';
 $$('.detail-open').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));
 if(selected&&!list.some(o=>o.id===selected)){$('#details').innerHTML='';selected=null;}
 if(selected)renderDetail();renderQuality(list);
}
function chart(o,cutoff){const bs=visibleBars(o,cutoff);if(!bs.length)return '<div class="empty">لم تصل شموع قابلة للرسم لهذا التوقيت. يحتفظ السجل بالتقييم الأصلي حتى تتوفر بيانات جديدة.</div>';
 const w=650,h=225,pad=30,min=Math.min(...bs.map(b=>b[3])),max=Math.max(...bs.map(b=>b[2])),lo=bs[0][0],hi=bs.at(-1)[0],x=t=>pad+(t-lo)/Math.max(60000,hi-lo)*(w-2*pad),y=v=>h-pad-(v-min)/Math.max(max-min,.0001)*(h-2*pad);
 let paths=[],path='',gaps=[];bs.forEach((b,i)=>{const gap=i&&b[0]-bs[i-1][0]>60000;if(gap){paths.push(path);path='';gaps.push(`<line x1="${x(bs[i-1][0])}" y1="${y(bs[i-1][4])}" x2="${x(b[0])}" y2="${y(b[4])}" stroke="#d1ac69" stroke-width="1.1" stroke-dasharray="3 4"/>`);}path+=(path?' L':'M')+x(b[0]).toFixed(2)+' '+y(b[4]).toFixed(2);});if(path)paths.push(path);
 const grid=[0,.25,.5,.75,1].map(r=>{const v=min+(max-min)*r,yy=y(v);return `<line x1="${pad}" y1="${yy}" x2="${w-pad}" y2="${yy}" stroke="#edf1ee"/><text x="${w-pad+5}" y="${yy+3}" font-size="8" fill="#94a59b">${price(v)}</text>`;}).join('');
 const first=Date.parse(o.first_bar_at||o.first_at)-(o.first_bar_at?0:60000);const mark=first>=lo&&first<=hi?`<line x1="${x(first)}" y1="15" x2="${x(first)}" y2="${h-pad}" stroke="#b2c9c0" stroke-dasharray="4 4"/><circle cx="${x(first)}" cy="${y(o.first_price)}" r="4" fill="#143e36"/><text x="${Math.min(x(first)+7,w-100)}" y="18" font-size="9" fill="#698b7b">الاكتشاف الأول</text>`:'';
 return `<svg class="chart" role="img" aria-label="مسار الأسعار المرصودة للسهم ${esc(o.symbol)}؛ الخط المتقطع يمثل فجوات" viewBox="0 0 ${w} ${h}">${grid}${gaps.join('')}${bs.length===1?`<circle cx="${x(bs[0][0])}" cy="${y(bs[0][4])}" r="4" fill="#178567"/>`:""}${paths.map(d=>`<path d="${d}" fill="none" stroke="#178567" stroke-width="2.2" stroke-linecap="round"/>`).join('')}${mark}</svg><div class="chart-labels"><span>${time(bs.at(-1)[0])} NY</span><span>${time(bs[0][0])} NY</span></div>`;
}
function openDetail(id){selected=id;timelineIndex=null;if(tab!=='watch')switchTab('watch');render();$('#details').scrollIntoView({behavior:'smooth',block:'start'});}
function renderDetail(){
 const o=rows.find(x=>x.id===selected);if(!o)return;
 const events=o.timeline.filter(x=>['DISCOVERY','STATE'].includes(x.kind)),index=timelineIndex??events.length,e=index<events.length?events[index]:null;
 const at=e?Date.parse(e.at):mode==='SHADOW'?viewTime():Date.parse(o.updated_at);
 const f=e?.features||(!e?o.features:null),q=e?.quality||o.quality,current=e?.to||o.state,p=e?{price:e.price,change:(e.price/o.first_price-1)*100,kind:'SAVED',at:e.at}:evidence(o),r=review(o);
 const links=(o.news||[]).filter(n=>Date.parse(n.received_at)<=at&&Date.parse(n.published_at)<=at);
 const actualBlocking=blockText(o),technicalOpen=$('.technical-details')?.open,newsOpen=$('.news-details')?.open;
 $('#details').innerHTML=`<article class="detail-panel"><div class="detail-heading"><div><h2><span class="num">${esc(o.symbol)}</span> <span class="num">$${price(p.price)}</span> ${changed(p.change)}</h2><p>${e?'تقييم محفوظ · '+time(e.at)+' NY':priceNote(p)} · ${esc(o.session)}</p></div><button class="link-button" id="close-detail" aria-label="إغلاق التفاصيل">✕</button></div>
 <div class="decision-summary"><strong>${e?'التقييم المحفوظ عند الانتقال':esc(r.title)}</strong><p>${e?esc(states[current]):esc(r.explanation)}</p>${!e?`<span>آخر مرحلة محفوظة: ${esc(states[current])} · ${time(o.updated_at)} NY</span><p><b>الدخول التجريبي:</b> ${o.entryReady?'الشروط مكتملة في التقييم المحفوظ':esc(actualBlocking||'لم يكتمل التقييم')}</p>`:''}</div>
 <div class="detail-grid"><div class="chart-box"><h3>الشموع المرصودة · ${esc(o.feed.toUpperCase())}</h3>${chart(o,at)}<p class="chart-note">الخط المتقطع فجوة بيانات. الرسم لإغلاق الدقيقة؛ آخر صفقة تظهر في العنوان. لا تُملأ الفجوات بأسعار مفترضة.</p><label class="range-control">سجل التقييم <input id="timeline-range" type="range" min="0" max="${events.length}" value="${index}" aria-label="وقت إعادة العرض"><span class="num">${e?time(at):'الأحدث'}</span></label></div>
 <div class="evidence"><h3>دليل المتابعة</h3><div class="fact"><span>أول اكتشاف محفوظ</span><strong class="num">$${price(o.first_price)} · ${time(o.first_at)} NY</strong></div><div class="fact"><span>مرحلة الحركة المحفوظة</span><strong>${esc(states[current])}</strong></div><div class="fact"><span>دقائق متصلة في نهاية النافذة</span><strong class="num">${q?.contiguousBars??'—'}</strong></div><div class="fact"><span>الدقائق المفقودة في النافذة</span><strong class="num">${q?.missingMinutes??'—'}</strong></div>
 <div class="scenario"><b>ما الذي ينتظر التأكيد؟</b>${e?'هذه هي المعلومات المحفوظة وقت الانتقال.':esc(r.paused?'وصول شموع متصلة وحديثة قبل تأكيد مرحلة جديدة.':o.awaiting)}${!e?`<br><b>شرط فشل النموذج التجريبي</b>إغلاقان متتاليان دون <span class="num">$${price(o.invalidation?.failureLevel)}</span> وفق هامش التذبذب الحالي. هذا مستوى تصنيف للحركة، وليس أمر وقف خسارة أو سعر خروج موصى به.`:''}</div>
 <details class="technical-details" ${technicalOpen?'open':''}><summary>المؤشرات والتعريفات</summary><div class="fact"><span>حجم آخر 3 شموع / متوسط 20 سابقة</span><strong class="num">${number(f?.volumeRatio3ObservedBars)}×</strong></div><p>نافذة بعدد الشموع؛ لا تعني ثلاث دقائق متصلة إذا وجدت فجوات، ولا تثبت دخول أموال جديدة.</p><div class="fact"><span>VWAP النظامية · الشموع المتاحة</span><strong class="num">$${price(f?.vwapRegularObserved)}</strong></div><div class="fact"><span>حجم نسبي لنفس الوقت تاريخيًا</span><strong>${f?.sameTimeRelativeVolume?number(f.sameTimeRelativeVolume)+'×':'سجل غير كافٍ'}</strong></div><div class="fact"><span>مستوى استعادة معروف آنذاك</span><strong class="num">${price(e?.level??(!e?o.recoveryLevel:null))}</strong></div></details></div></div>
 <div class="timeline">${events.filter(x=>Date.parse(x.at)<=at).slice(-9).map(x=>`<div class="timeline-item"><span class="num">${time(x.at)} NY</span><strong>${esc(states[x.to]||'اكتشاف')}</strong><small class="num">$${price(x.price)}</small></div>`).join('')}</div>
 <details class="news-details" ${newsOpen?'open':''}><summary>الأخبار المرتبطة من المزود <span class="num">(${links.length})</span></summary><p>ربط المزود لا يثبت وجود محفز جوهري أو استمرار الصعود. النشر والوصول توقيتان مختلفان.</p>${links.map(n=>{const url=safeNewsUrl(n.url);return `<article class="news-item"><span class="badge neutral">${newsEvidence(n)==='MARKET_ROUNDUP'?'موجز حركة أسهم · ليس محفزًا مؤكدًا':'خبر مرتبط بحسب المزود'}</span>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer" dir="auto">${esc(n.headline)}</a>`:`<span dir="auto">${esc(n.headline)}</span>`}<small>${esc(n.source)} · النشر ${esc(n.published_at?.slice(0,10))} ${time(n.published_at)} NY · الوصول ${time(n.received_at)} NY</small></article>`;}).join('')||'<p>لا يوجد خبر موثّق في هذا السجل.</p>'}</details></article>`;
 $('#timeline-range').onchange=e=>{timelineIndex=Number(e.target.value);renderDetail();};$('#close-detail').onclick=()=>{selected=null;$('#details').innerHTML='';};
}
function renderResearch(){const s=summary;if(!s)return;$('#research-content').innerHTML=`<div class="research-head"><div><h2>الاكتشاف محفوظ. أفضلية التداول لم تثبت.</h2><p>نفس 210 فرص أولى، و322 إشارة أصلية مرتبطة. العينة مكشوفة مسبقًا، والأرقام أدناه تشخيص مشروط للتنفيذ؛ لا تمثل اختبارًا مستقلًا أو عائد محفظة.</p></div><span class="badge amber">لا ترقية للقواعد</span></div><div class="table-wrap"><table><thead><tr><th>الصعود بعد الاكتشاف</th><th>بلوغ مرصود</th><th>عدم بلوغ بمسار كامل</th><th>نتيجة مجهولة</th></tr></thead><tbody>${[10,20,50].map(n=>`<tr><td class="num">+${n}%</td><td>${s.outcomes[n].observed}</td><td>${s.outcomes[n].notHit}</td><td>${s.outcomes[n].unknown}</td></tr>`).join('')}</tbody></table></div><div class="panel"><h3>مقارنة نماذج الدخول والخروج · افتراضات تنفيذ معلنة</h3><p>الكمية 100 سهم، سبريد مفترض 40 نقطة أساس، انزلاق 10 نقاط لكل طرف ورسوم نقطة واحدة لكل طرف. التنفيذ عند أول افتتاح دقيقة بعد مهلة القرار، والقدرة تقاس بحجم الدقيقة السابقة. حالات الأهلية التاريخية المؤكدة: <b>صفر</b>. تختلف العينات القابلة للتقييم؛ لا يصح ترتيب النماذج من المتوسط وحده.</p><div class="table-wrap"><table><thead><tr><th>النموذج</th><th>صفقات قابلة للتشخيص</th><th>مسار مجهول</th><th>متوسط صافٍ مفترض</th><th>الوسيط</th><th>المتوسط دون أكبر رابح</th></tr></thead><tbody>${Object.entries(s.diagnostic).map(([k,v])=>`<tr><td>${families[k]}</td><td>${v.scorableTrades}</td><td>${v.unknownTrades}</td><td class="num">${percent(v.meanNetPct)}</td><td class="num">${percent(v.medianNetPct)}</td><td class="num">${percent(v.meanWithoutBest)}</td></tr>`).join('')}</tbody></table></div></div><div class="quality-grid"><div class="quality-card"><h3>فصل زمني بلا ادعاء استقلال</h3><p>6 جلسات تطوير، جلستان للتحقق التشخيصي، وجلستان للاختبار التشخيصي. جميعها استُخدمت في أبحاث سابقة؛ نحتاج جلسات جديدة محفوظة بعد تجميد التعريفات لاختبار مستقل.</p><span class="badge neutral">${s.walkForward.length} نوافذ Walk-forward تشخيصية</span></div><div class="quality-card"><h3>ما لم نتمكن من قياسه</h3><p>الفرص المفقودة في السوق كاملًا، وحركة قبل الافتتاح، وتأثير الخبر عند وصوله، وتدفق الأوامر: لا تسمح التغطية الحالية بإثباتها. لا نستخدم أهلية اليوم في التاريخ.</p><span class="badge amber">95% أو أي دقة نهائية: غير متاحة</span></div></div><div class="panel"><h3>حساسية السبريد وحجم الصفقة</h3><div class="table-wrap"><table><thead><tr><th>السبريد المفترض</th><th>الكمية</th><th>أول تنفيذ · عدد / متوسط</th><th>استعادة · عدد / متوسط</th><th>إعادة دخول · عدد / متوسط</th></tr></thead><tbody>${s.sensitivity.map(r=>`<tr><td>${r.spreadBps} نقطة أساس</td><td class="num">${r.quantity}</td>${Object.values(r.summary).map(v=>`<td class="num">${v.scorableTrades} / ${percent(v.meanNetPct)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;}
function renderQuality(list){const missing=list.reduce((a,o)=>a+(o.quality?.missingMinutes||0),0);$('#quality-content').innerHTML=`<div class="research-head"><div><h2>نعرض ما نعرفه، وما ينقصه الدليل.</h2><p>جودة المصدر منفصلة عن حالة الحركة. لا نعوّض الدقيقة المفقودة بسعر سابق ولا ننسب الحجم تلقائيًا إلى أموال جديدة.</p></div></div><div class="quality-grid"><div class="quality-card"><h3>التاريخي: SIP · الحي: IEX</h3><p>SIP تغطية مجمعة في الأرشيف. IEX يغطي سوقًا واحدًا في الاتصال الحالي. لا نفترض تكافؤ الحجم أو الإشارات بينهما.</p><span class="badge amber">المقارنة بين المصدرين محدودة</span></div><div class="quality-card"><h3>الدقائق المفقودة في العرض الحالي</h3><strong class="num" style="font-size:30px">${number(missing,0)}</strong><p>السبب غير معروف ما لم يرد دليل على توقف تداول أو دقيقة بلا صفقات أو انقطاع تغذية. هذه فجوات نوافذ الرصد وليست عدد فجوات السوق كله.</p></div><div class="quality-card"><h3>القيمة السوقية والشرعية</h3><p>النطاق الافتراضي ناسداك وأقل من 100 مليون دولار. لا توجد أهلية تاريخية موثقة لهذه العينة. المجهول يظهر كما هو، ويمنع انتقال الفرصة إلى قائمة الدخول المكتمل.</p><span class="badge neutral">مصادر تاريخية مؤهلة: غير متصلة</span></div><div class="quality-card"><h3>استمرارية الخادم</h3><p>الخادم الحالي يعمل عند الطلب. قاعدة SQLite تدعم الاستئناف عند ثبات القرص، لكن مساحة الخادم الحالية مؤقتة ولا يثبت حفظها عبر إعادة النشر. التشغيل المستمر والتخزين الدائم غير مفعّلين.</p><span class="badge amber">بوابة إطلاق لم تُجتز بعد</span></div><div class="quality-card"><h3>توقيت البيانات والتصحيحات</h3><p>UTC في السجل، ونيويورك للجلسات. وقت الوصول الفعلي محفوظ في الرصد الجديد. أرشيف الدراسة يفترض إتاحة الشمعة عند اكتمالها؛ لا يتوفر سجل وصولها الأصلي.</p></div><div class="quality-card"><h3>سجل القرار قابل للمراجعة</h3><p>الاكتشاف الأول وانتقالات الحالة محفوظة مع إصدار القواعد وجودة البيانات. التصحيحات وإعادة التحليل لا تستبدل التقييم الأصلي. لا يوجد مسار لإرسال أوامر تداول.</p></div></div>`;}
function switchTab(name){tab=name;$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.tab-panel').forEach(x=>x.classList.toggle('hidden',x.id!==name));$('#details').style.display=name==='watch'?'':'none';if(name==='research')renderResearch();}
async function liveRefresh(){if(busy||mode!=='SHADOW')return;busy=true;$('#connection').textContent='جارٍ تحديث الرصد…';try{await get(API+'/api/scanner');let data=await get(API+'/api/elite/opportunities');if(data.status?.busy){await new Promise(resolve=>setTimeout(resolve,1200));data=await get(API+'/api/elite/opportunities');}if(mode!=='SHADOW')return;clockOffset=Date.parse(data.serverTime)-Date.now();if(!Number.isFinite(clockOffset))clockOffset=0;rows=data.opportunities||[];liveStatus=data.status;dates();render();const status=data.status||{};$('.status-dot').classList.remove('offline');$('#connection').textContent=status.lastObservedAt?'تم التحديث · '+time(status.lastObservedAt)+' NY':'متصل · انتظار اكتمال الرصد';$('#footer-data').textContent=`IEX · تخزين ${status.storage==='EPHEMERAL_SQLITE'?'مؤقت':'غير مثبت الاستمرارية'} · رصد موازٍ`;if(status.lastError)toast('حالة الرصد: '+status.lastError);}catch{if(mode!=='SHADOW')return;render();$('.status-dot').classList.add('offline');$('#connection').textContent='تعذّر التحديث · آخر بيانات محفوظة';toast('تعذّر جلب الرصد الحي. لم نستبدله بأسعار افتراضية.');}finally{busy=false;}}
function setMode(next){mode=next;try{localStorage.setItem('tag-elite-mode',next);}catch{}clearInterval(liveTimer);selected=null;$('#details').innerHTML='';$('#replay-mode').classList.toggle('selected',mode==='REPLAY');$('#live-mode').classList.toggle('selected',mode==='SHADOW');if(mode==='REPLAY'){rows=archive;dates();$('#connection').textContent='أرشيف موثّق · 10 جلسات';$('#mode-notice').innerHTML='<span class="notice-icon">◷</span><div><strong>أرشيف حقيقي · نتائج بحثية</strong><span>بيانات SIP من 24 أغسطس إلى 4 سبتمبر 2026. لا تعني هذه الشاشة وجود فرص حية الآن.</span></div><span class="badge amber">غير مثبت تداوليًا</span>';$('#footer-data').textContent='UTC للتخزين · نيويورك لتقسيم الجلسة';render();}else{rows=[];dates();render();$('#mode-notice').innerHTML='<span class="notice-icon">◉</span><div><strong>رصد حي موازٍ · IEX</strong><span>آخر صفقة وإغلاق الدقيقة لهما توقيتان مختلفان. التحديث أثناء فتح الصفحة، والتخزين مؤقت.</span></div><span class="badge amber">تجريبي</span>';liveRefresh();liveTimer=setInterval(liveRefresh,30000);}}
$('#search').oninput=render;$('#session').onchange=render;$('#stage').onchange=render;$('#verified-only').onchange=render;$$('.nav').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#replay-mode').onclick=()=>setMode('REPLAY');$('#live-mode').onclick=()=>setMode('SHADOW');$('#refresh').onclick=()=>mode==='SHADOW'?liveRefresh():toast('الأرشيف ثابت ومحفوظ بإصدار 25 سبتمبر 2026.');
$('#export').onclick=()=>{const b=new Blob([JSON.stringify({product:'TAG elite',mode,version:summary?.version,exportedAt:new Date().toISOString(),originalEvaluations:filtered(),notPortfolioReturns:true},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='tag-elite-records.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('تم تصدير السجلات مع مصدرها وإصدارها.');};
try{summary=await get('./data/summary.json');const dates=[...summary.partitions.development,...summary.partitions.validationDiagnostic,...summary.partitions.testDiagnostic];archive=(await Promise.all(dates.map(async d=>{const r=await fetch('./data/'+d+'.json.gz');if(!r.ok)throw Error('ARCHIVE_UNAVAILABLE');return new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json();}))).flat();let chosen='REPLAY';try{chosen=new URLSearchParams(location.search).get('mode')==='live'?'SHADOW':localStorage.getItem('tag-elite-mode')||'REPLAY';}catch{}setMode(chosen==='SHADOW'?'SHADOW':'REPLAY');renderResearch();}catch{$('#connection').textContent='تعذّر تحميل الأرشيف';$('#opportunity-rows').innerHTML='<tr><td colspan="8" class="empty">لم نستطع تحميل ملفات النتائج. أعد تحميل الصفحة.</td></tr>';}
