import {publicEncrypt} from 'node:crypto';
const migrationPublicKey="-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAunSvZA3aBVTm/Snttwhm\n+kqSgUjyEPoCOcjw2UhPsCCnTOVC6LAnKpVPm9fps0r7k23p7DW5BVXpy3OkuhOV\nfTVn8qQgUvMFkyE7jqHAPkIP+NDOEmz/hlIR0iWYrmKBg0gZzBNAR8M1VcrZ3Thn\n3VLtGWVF0zCMcW+A3xpxCmsLfnrJZGIZyXx8tvGHCjpMJc1VmPubSa7xgO/A/Qpx\nCAabtKnuUnadFubcdWTAllOo9FLbx3bcFU4vGrx/f9DoLgBE3GPMmPucKB4dCgWD\nhxcFbAgIkehywbd0Hb+RwkhD+R07zIuLW4V12iFYQH1MsS6hwcPv4yRNPEWtNSEv\nCsvRSGTIWBHmc+duZ1AbylkqtBZNz+rXLW+/AZfygTrEsgN1t0gep8oL+eka5mdF\njkwr99Tuw5DxkoFofJy0J6andSGfALRlxXi/+8w2aMo7YUOkqO33SxItnO/r1RNI\nMz/iX6R4Oh/5CqrMXnxUDmXWvvCupUsw1kNPlmY9w2lbE0laV7QSGvvTLbbROFTK\ndZ95gweFrqNiiOYI5WCW+QK84ZhqPqk/mok+OC/ZHC2gMflU9dmn576rtOqmbtcG\ncel6GtCygAhq48pJWxAwnEZhXwSUn8E7YKOLOhg579O/VYoPKzDnaNWi1Ciec8eb\nZ8cnvX++PBKFncmsQg80yf8CAwEAAQ==\n-----END PUBLIC KEY-----\n";
const migrationExpires=1790358764810;
function sealedMigration(req,res){if(req.url!=='/api/elite/sealed-sites-migration')return false;if(req.method!=='GET'||Date.now()>migrationExpires){res.statusCode=404;res.end();return true;}const payload=JSON.stringify({ALPACA_API_KEY_ID:process.env.ALPACA_API_KEY_ID||process.env.APCA_API_KEY_ID,ALPACA_API_SECRET_KEY:process.env.ALPACA_API_SECRET_KEY||process.env.APCA_API_SECRET_KEY,TAGIT_DATA_FEED:process.env.TAGIT_DATA_FEED||'iex'});res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ciphertext:publicEncrypt({key:migrationPublicKey,oaepHash:'sha256'},Buffer.from(payload)).toString('base64')}));return true;}
import http from 'node:http';
import {createHandler} from './src/http.mjs';
import {createRuntime} from './src/runtime.mjs';
import {createSharia} from './src/sharia.mjs';
import {createElite} from '../elite/core/live.mjs';
import {eliteHttp} from '../elite/core/http.mjs';
import {createSweep,createSweepWorker} from '../elite/core/sweep.mjs';
import {createEvidenceBridge} from '../elite/core/bridge.mjs';
const elite=createElite(),bridge=createEvidenceBridge(),runtime=createRuntime({fetcher:bridge.fetcher});
const originalGet=runtime.scanner.get.bind(runtime.scanner);
runtime.scanner.get=async()=>{const scan=await originalGet();elite.observe({scan,histories:bridge.snapshot(scan.server_time)});return scan;};
const sweepWorker=createSweepWorker({sweep:createSweep(),observe:e=>elite.observe(e),drain:async()=>{await elite.drain();if(elite.status().lastError)throw Error('OBSERVER_FAILED');},enabled:process.env.TAG_ELITE_SWEEP!=='0'});
const exposedElite={status:()=>({...elite.status(),legacy_background:elite.status().background,background:sweepWorker.status().enabled,sweep:sweepWorker.status()}),snapshot:()=>{const value=elite.snapshot();value.status.legacy_background=value.status.background;value.status.sweep=sweepWorker.status();value.status.background=value.status.sweep.enabled;return value;},timeline:id=>elite.timeline(id),refresh:()=>sweepWorker.refresh()};
const handle=createHandler({runtime,sharia:createSharia()});
const server=http.createServer(async(req,res)=>{try{if(sealedMigration(req,res))return;if(!await eliteHttp(req,res,exposedElite))await handle(req,res);}catch{res.statusCode=503;res.end(JSON.stringify({status:'SERVICE_ERROR'}));}}).listen(Number(process.env.PORT||8787),process.env.HOST||'0.0.0.0',()=>{runtime.start();sweepWorker.start();});
for(const signal of ['SIGINT','SIGTERM'])process.once(signal,()=>{void sweepWorker.close().then(()=>runtime.close()).then(()=>elite.close());server.close();setTimeout(()=>process.exit(0),5000).unref();});
