'use strict';
(function(){
const KEY='tag500.temporal.v509';
const LEGACY='tag500.temporal.v508';
const MAX_AGE=8*60*60*1000;
function read(){try{let raw=localStorage.getItem(KEY);if(!raw){raw=localStorage.getItem(LEGACY);if(raw)localStorage.setItem(KEY,raw)}const x=JSON.parse(raw||'{}');return x&&typeof x==='object'?x:{}}catch{return {}}}
function write(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}}
function metrics(ticker,currentChange){const db=read(),a=Array.isArray(db[ticker])?db[ticker]:[];if(!a.length)return{count:0,firstSeen:null,delta:null,slope:null,retention:null,trajectory:'NO_HISTORY'};const now=Date.now(),v=a.filter(o=>now-o.ts<=MAX_AGE&&Number.isFinite(o.change)).sort((a,b)=>a.ts-b.ts);if(!v.length)return{count:0,firstSeen:null,delta:null,slope:null,retention:null,trajectory:'NO_HISTORY'};const first=v[0],all=v.concat([{ts:now,change:currentChange}]).filter(o=>Number.isFinite(o.change));const peak=Math.max(...all.map(o=>o.change));const retention=peak>0&&Number.isFinite(currentChange)?Math.max(0,Math.min(1,currentChange/peak)):null;let slope=null;if(all.length>=2){const t0=all[0].ts;const xs=all.map(o=>(o.ts-t0)/36e5),ys=all.map(o=>o.change);const xm=xs.reduce((s,x)=>s+x,0)/xs.length,ym=ys.reduce((s,y)=>s+y,0)/ys.length;let num=0,den=0;for(let i=0;i<xs.length;i++){num+=(xs[i]-xm)*(ys[i]-ym);den+=(xs[i]-xm)**2}if(den>0)slope=num/den;}let trajectory='STABLE';if(v.length<1)trajectory='NO_HISTORY';else if(Number.isFinite(slope)&&Number.isFinite(retention)&&slope>=3&&retention>=.75)trajectory='ACCELERATING';else if(Number.isFinite(slope)&&Number.isFinite(retention)&&slope>=.5&&retention>=.65)trajectory='BUILDING';else if((Number.isFinite(slope)&&slope<=-2)||(Number.isFinite(retention)&&retention<.55))trajectory='FADING';return{count:v.length,firstSeen:first.ts,delta:Number.isFinite(currentChange)?currentChange-first.change:null,slope,retention,trajectory};}
function save(){if(!Array.isArray(window.rows)||!window.sourceMeta?.updated)return;const stamp=new Date(window.sourceMeta.updated).getTime();if(!Number.isFinite(stamp))return;const db=read(),cut=Date.now()-MAX_AGE;for(const x of window.rows){if(!x?.ticker||!Number.isFinite(x.changePct))continue;const a=(Array.isArray(db[x.ticker])?db[x.ticker]:[]).filter(o=>o.ts>=cut);if(!a.some(o=>o.ts===stamp))a.push({ts:stamp,change:x.changePct,price:Number.isFinite(x.price)?x.price:null,volume:Number.isFinite(x.volume)?x.volume:null});db[x.ticker]=a.slice(-20);}write(db);}
function trajectoryLabel(t){return{ACCELERATING:'يتسارع',BUILDING:'يبني',STABLE:'ثابت',FADING:'يتلاشى',NO_HISTORY:'لقطة واحدة'}[t]||t}
function firstSeenLabel(ts){if(!Number.isFinite(ts))return'—';try{return new Intl.DateTimeFormat('ar-SA',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit'}).format(new Date(ts))+' ET'}catch{return'—'}}
const baseAnalyze=window.analyze;
if(typeof baseAnalyze==='function')window.analyze=function(x){const z=baseAnalyze(x),m=metrics(z.ticker,z.changePct);z.temporal=m;const hugePostMove=Number.isFinite(z.rvol)&&z.rvol>=12&&Number.isFinite(z.changePct)&&z.changePct>=20;const alreadyExtended=Number.isFinite(z.changePct)&&z.changePct>=25;const exhausted=Number.isFinite(z.exhaustion)&&z.exhaustion>=65;z.discoveryCredit=!(hugePostMove||alreadyExtended||exhausted);if(z.stage==='DISCOVERY'&&!z.discoveryCredit)z.stage='LATE';if(z.stage==='IGNITION'&&Number.isFinite(z.changePct)&&z.changePct>=35)z.stage='LATE';if(Number.isFinite(m.slope))z.reasons.push(`Persistence ${m.slope>=0?'+':''}${m.slope.toFixed(1)} نقطة/ساعة`);if(Number.isFinite(m.retention))z.reasons.push(`Gain retention ${(m.retention*100).toFixed(0)}%`);if(m.trajectory!=='NO_HISTORY')z.reasons.push(`المسار: ${trajectoryLabel(m.trajectory)}`);if(hugePostMove)z.reasons.unshift('RVOL متأخر: لا يُحتسب اكتشافًا مبكرًا');return z;};
const baseRender=window.render;
if(typeof baseRender==='function')window.render=function(){baseRender();save();const head=document.querySelector('.table-panel thead tr');if(head&&!head.querySelector('[data-tag509-trajectory]')){const th=document.createElement('th');th.dataset.tag509Trajectory='1';th.textContent='المسار';const stageTh=[...head.children].find(el=>el.textContent.trim()==='المرحلة');if(stageTh)stageTh.after(th);else head.appendChild(th)}document.querySelectorAll('#scannerBody tr[data-ticker]').forEach(tr=>{const z=(window.analyzed||[]).find(x=>x.ticker===tr.dataset.ticker);if(!z?.temporal)return;const cells=[...tr.children];const stageCell=cells.find(td=>td.querySelector('.pill'));if(stageCell&&!tr.querySelector('[data-tag509-trajectory]')){const td=document.createElement('td');td.dataset.tag509Trajectory='1';const m=z.temporal;td.innerHTML=`<strong>${trajectoryLabel(m.trajectory)}</strong><small style="display:block;color:#8fa9bd;font-size:10px;margin-top:3px">${firstSeenLabel(m.firstSeen)}${Number.isFinite(m.delta)?` · Δ ${m.delta>=0?'+':''}${m.delta.toFixed(1)}pp`:''}${Number.isFinite(m.retention)?` · ret ${(m.retention*100).toFixed(0)}%`:''}</small>`;stageCell.after(td)}});const top=document.querySelector('#topOpportunity');if(top&&window.analyzed?.length){const best=window.analyzed.filter(x=>x.valid).sort((a,b)=>(b.score??-1)-(a.score??-1))[0];if(best?.temporal&&best.temporal.trajectory!=='NO_HISTORY'){const note=document.createElement('div');note.style.cssText='margin-top:8px;color:#9fb6c8;font-size:12px';note.textContent=`المسار الزمني: ${trajectoryLabel(best.temporal.trajectory)} · أول رصد ${firstSeenLabel(best.temporal.firstSeen)}${Number.isFinite(best.temporal.delta)?` · التغير منذ أول رصد ${best.temporal.delta>=0?'+':''}${best.temporal.delta.toFixed(1)} نقطة`:''}`;top.appendChild(note)}}const log=document.querySelector('#integrityLog');if(log){const n=(window.analyzed||[]).filter(x=>x.temporal?.count>=1).length,a=(window.analyzed||[]).filter(x=>x.temporal?.trajectory==='ACCELERATING').length,f=(window.analyzed||[]).filter(x=>x.temporal?.trajectory==='FADING').length;log.insertAdjacentHTML('beforeend',`<div class="log-item">Temporal Trajectory: ${n} سهم بمقارنة زمنية · ${a} يتسارع · ${f} يتلاشى · التصنيف وصفي ولا يغير thresholds.</div>`)}};
})();