'use strict';
(function(){
const KEY='tag500.temporal.v508';
const MAX_AGE=8*60*60*1000;
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return {}}}
function write(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}}
function metrics(ticker,currentChange){const db=read(),a=Array.isArray(db[ticker])?db[ticker]:[];if(!a.length)return{count:0,firstSeen:null,delta:null,slope:null,retention:null};const now=Date.now(),v=a.filter(o=>now-o.ts<=MAX_AGE&&Number.isFinite(o.change)).sort((a,b)=>a.ts-b.ts);if(!v.length)return{count:0,firstSeen:null,delta:null,slope:null,retention:null};const first=v[0],all=v.concat([{ts:now,change:currentChange}]).filter(o=>Number.isFinite(o.change));const peak=Math.max(...all.map(o=>o.change));const retention=peak>0&&Number.isFinite(currentChange)?Math.max(0,Math.min(1,currentChange/peak)):null;let slope=null;if(all.length>=2){const t0=all[0].ts;const xs=all.map(o=>(o.ts-t0)/36e5),ys=all.map(o=>o.change);const xm=xs.reduce((s,x)=>s+x,0)/xs.length,ym=ys.reduce((s,y)=>s+y,0)/ys.length;let num=0,den=0;for(let i=0;i<xs.length;i++){num+=(xs[i]-xm)*(ys[i]-ym);den+=(xs[i]-xm)**2}if(den>0)slope=num/den;}return{count:v.length,firstSeen:first.ts,delta:Number.isFinite(currentChange)?currentChange-first.change:null,slope,retention};}
function save(){if(!Array.isArray(window.rows)||!window.sourceMeta?.updated)return;const stamp=new Date(window.sourceMeta.updated).getTime();if(!Number.isFinite(stamp))return;const db=read(),cut=Date.now()-MAX_AGE;for(const x of window.rows){if(!x?.ticker||!Number.isFinite(x.changePct))continue;const a=(Array.isArray(db[x.ticker])?db[x.ticker]:[]).filter(o=>o.ts>=cut);if(!a.some(o=>o.ts===stamp))a.push({ts:stamp,change:x.changePct,price:Number.isFinite(x.price)?x.price:null,volume:Number.isFinite(x.volume)?x.volume:null});db[x.ticker]=a.slice(-16);}write(db);}
const baseAnalyze=window.analyze;
if(typeof baseAnalyze==='function')window.analyze=function(x){const z=baseAnalyze(x),m=metrics(z.ticker,z.changePct);z.temporal=m;const hugePostMove=Number.isFinite(z.rvol)&&z.rvol>=12&&Number.isFinite(z.changePct)&&z.changePct>=20;const alreadyExtended=Number.isFinite(z.changePct)&&z.changePct>=25;const exhausted=Number.isFinite(z.exhaustion)&&z.exhaustion>=65;z.discoveryCredit=!(hugePostMove||alreadyExtended||exhausted);if(z.stage==='DISCOVERY'&&!z.discoveryCredit)z.stage='LATE';if(z.stage==='IGNITION'&&Number.isFinite(z.changePct)&&z.changePct>=35)z.stage='LATE';if(Number.isFinite(m.slope))z.reasons.push(`Persistence ${m.slope>=0?'+':''}${m.slope.toFixed(1)} نقطة/ساعة`);if(Number.isFinite(m.retention))z.reasons.push(`Gain retention ${(m.retention*100).toFixed(0)}%`);if(hugePostMove)z.reasons.unshift('RVOL متأخر: لا يُحتسب اكتشافًا مبكرًا');return z;};
const baseRender=window.render;
if(typeof baseRender==='function')window.render=function(){baseRender();save();document.querySelectorAll('#scannerBody tr[data-ticker]').forEach(tr=>{const z=(window.analyzed||[]).find(x=>x.ticker===tr.dataset.ticker);if(!z?.temporal)return;const td=tr.querySelector('td');if(!td)return;const m=z.temporal;if(m.count||Number.isFinite(m.slope)){const s=document.createElement('small');s.style.cssText='display:block;color:#8fa9bd;font-size:10px;margin-top:3px';s.textContent=`${m.count+1} لقطات${Number.isFinite(m.slope)?` · slope ${m.slope>=0?'+':''}${m.slope.toFixed(1)}/س`:''}${Number.isFinite(m.retention)?` · retention ${(m.retention*100).toFixed(0)}%`:''}`;td.appendChild(s);}});const log=document.querySelector('#integrityLog');if(log){const n=(window.analyzed||[]).filter(x=>x.temporal?.count>=1).length;log.insertAdjacentHTML('beforeend',`<div class="log-item">Temporal Persistence: ${n} سهم لديه مقارنة زمنية محفوظة · لا يُمنح Discovery credit للحركة الممتدة أو RVOL المتأخر.</div>`);}};
})();