'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TAGX2Engine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
 const num=v=>Number.isFinite(Number(v))?Number(v):null;
 const ageMin=t=>{const ms=t?Date.now()-new Date(t).getTime():Infinity;return Number.isFinite(ms)?ms/60000:Infinity};
 function stageOf(c){const ch=num(c.changePct),r5=num(c.priceVelocity5mPct),r15=num(c.priceVelocity15mPct);if(ch==null)return'DISCOVERY';if(ch>=10&&((r5!=null&&r5<=0)||(r15!=null&&r15<=0)))return'EXHAUSTION';if(ch>=12)return'LATE';if(ch<1)return'DISCOVERY';if(ch<3)return'WAKE_UP';if(ch<7)return'PRE_IGNITION';return'IGNITION'}
 function scoreCandidate(c,ctx={}){const ch=num(c.changePct),v5=num(c.priceVelocity5mPct)||0,v15=num(c.priceVelocity15mPct)||0,va=num(c.volumeAcceleration5m),to=num(c.turnover5mPctFloat),ers=num(c.earlyRegimeShiftScore),ign=num(c.ignitionScore);const session=String(ctx.session||c.session||'unknown'),stage=stageOf(c),trace=[];const dataAge=num(ctx.liveAgeMin),dataHigh=String(ctx.dataConfidence||'').toUpperCase()==='HIGH',baselineOk=c.baselineIntegrity==='VERIFIED_POINT_IN_TIME'||c.baselineIntegrity==='VERIFIED',liquidityProof=c.extendedLiquidityVerified===true||(va!=null&&va>=2)||(to!=null&&to>=.20),coverageOnly=!!c.coverageOnly;
  let dataScore=0;if(dataHigh)dataScore+=35;if(dataAge!=null&&dataAge<=6)dataScore+=35;else if(dataAge!=null&&dataAge<=10)dataScore+=15;if(baselineOk)dataScore+=30;dataScore=clamp(dataScore);
  const momentum=clamp(Math.max(0,v5)*22+Math.max(0,v15)*10),accel=v5-(v15/3),acceleration=clamp(Math.max(0,accel)*32),liquidity=clamp(Math.max(va!=null?va*15:0,to!=null?to*90:0)),regime=clamp(((ers||0)+(ign||0))/2);let earlyFit=0;if(ch!=null&&ch>=1&&ch<=9.5)earlyFit=100;else if(ch!=null&&ch>9.5&&ch<12)earlyFit=35;else if(ch!=null&&ch>=0&&ch<1)earlyFit=45;const persistence=clamp((v5>0?30:0)+(v15>0?25:0)+(liquidityProof?25:0)+(['pre-market','premarket','after-hours'].includes(session)?20:10));
  let score=.16*dataScore+.18*momentum+.12*acceleration+.17*liquidity+.16*regime+.12*earlyFit+.09*persistence;let risk=28;if(!dataHigh)risk+=28;if(dataAge==null||dataAge>6)risk+=22;if(!baselineOk)risk+=18;if(!liquidityProof)risk+=16;if(coverageOnly)risk+=22;if(ch!=null&&ch>=9.5)risk+=18;if(ch!=null&&ch>=12)risk+=30;if(v5<=0)risk+=18;if(v15<=0)risk+=12;if(session==='after-hours')risk+=8;risk=clamp(risk);
  trace.push([dataHigh?'+':'-',dataHigh?'High-confidence feed':'Feed confidence not HIGH']);trace.push([dataAge!=null&&dataAge<=6?'+':'-',dataAge!=null&&dataAge<=6?'Feed fresh ≤6m':'Feed older than execution window']);trace.push([baselineOk?'+':'-',baselineOk?'Point-in-time baseline verified':'Baseline not independently verified']);trace.push([v5>.4&&v15>.2?'+':'-',v5>.4&&v15>.2?'5m/15m continuation positive':'Continuation not proven']);trace.push([liquidityProof?'+':'-',liquidityProof?'Independent liquidity/float evidence':'No independent liquidity proof']);trace.push([ch!=null&&ch>=1&&ch<=9.5?'+':'-',ch!=null&&ch>=1&&ch<=9.5?'Still inside early displacement window':'Outside preferred early window']);if(coverageOnly)trace.push(['-','Coverage-rescue only: discovery, never execution']);
  const sharia=String(ctx.shariaStatus||'UNVERIFIED').toUpperCase(),dataGate=dataHigh&&dataAge!=null&&dataAge<=6&&baselineOk,continuation=v5>=.45&&v15>=.20,early=ch!=null&&ch>=1.5&&ch<=9.5,crossValidated=liquidityProof&&regime>=70&&continuation,researchPass=dataGate&&early&&crossValidated&&!coverageOnly&&score>=70&&risk<=58&&!['LATE','EXHAUSTION'].includes(stage);let action='IGNORE';if(['LATE','EXHAUSTION'].includes(stage))action='LATE';else if(!dataGate)action='BLOCKED_DATA';else if(researchPass&&sharia==='VERIFIED')action='READY_RESEARCH';else if(researchPass&&sharia==='UNVERIFIED')action='WATCH_SHARIA';else if(sharia==='EXCLUDED')action='EXCLUDED';else if(['PRE_IGNITION','IGNITION','WAKE_UP'].includes(stage))action='PROVE';else action='WATCH';
  const invalidation=[];if(v5<=0)invalidation.push('5m velocity ≤ 0');if(v15<=0)invalidation.push('15m velocity ≤ 0');if(ch!=null&&ch>=10)invalidation.push('displacement ≥ 10%');if(!liquidityProof)invalidation.push('liquidity confirmation lost');if(dataAge==null||dataAge>6)invalidation.push('feed stale');if(!invalidation.length)invalidation.push('5m/15m continuation breaks');return{ticker:String(c.ticker||'').toUpperCase(),stage,score:Math.round(clamp(score)),risk:Math.round(risk),action,researchPass,sharia,trace,invalidation,components:{dataScore:Math.round(dataScore),momentum:Math.round(momentum),acceleration:Math.round(acceleration),liquidity:Math.round(liquidity),regime:Math.round(regime),earlyFit:Math.round(earlyFit),persistence:Math.round(persistence)}}}
 function mergeSources(live={},rescue={}){const m=new Map();for(const e of(live.emergingCandidates||[])){const t=String(e.ticker||'').toUpperCase();if(!t)continue;m.set(t,{...e,ticker:t,sources:['live'],coverageOnly:false})}for(const e of(rescue.topMovers||[])){const t=String(e.ticker||'').toUpperCase();if(!t)continue;if(m.has(t)){const x=m.get(t);x.sources.push('coverage');for(const k of['price','changePct','priceVelocity5mPct','priceVelocity15mPct','volumeAcceleration5m'])if(x[k]==null&&e[k]!=null)x[k]=e[k]}else m.set(t,{...e,ticker:t,sources:['coverage'],coverageOnly:true})}return[...m.values()]}
 function weeklyLessons(history={}){const sessions=history.sessions||[],rows=sessions.map(s=>{const c=s.counts||{},early=c.earlyCohort||0,w=c.earlyWinners50||0,f=c.earlyFailuresUnder10||0;return{date:s.sessionDateET,early,winners50:w,failures:f,winner50Rate:early?100*w/early:0,failureRate:early?100*f/early:0,promotionEligible:!!s.promotionEligible}}),early=rows.reduce((a,b)=>a+b.early,0),wins=rows.reduce((a,b)=>a+b.winners50,0),fail=rows.reduce((a,b)=>a+b.failures,0);return{rows,total:{early,wins,fail,winner50Rate:early?100*wins/early:0,failureRate:early?100*fail/early:0}}}
 return{num,ageMin,stageOf,scoreCandidate,mergeSources,weeklyLessons};
});
