(()=>{
let enrichment={rows:{},updatedAt:null,sourceStatus:{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadEnrichment(){try{const r=await fetch('./data/enrichment.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)return;enrichment=await r.json();window.TAGEnrichment=enrichment;decorateStatus()}catch(e){console.warn('TAG enrichment unavailable',e)}}
function decorateStatus(){const s=document.getElementById('finvizStatus');if(!s||!enrichment.updatedAt)return;const st=enrichment.sourceStatus||{};const extra=` · مصادر مساندة: Yahoo ${st.Yahoo||'—'} · SEC ${st.SECSubmissions||st.SEC||'—'} · News ${st.News||'—'}`;if(!s.textContent.includes('مصادر مساندة'))s.textContent+=extra}
function card(t){const d=enrichment.rows?.[t];if(!d)return `<div class="tag-card-empty">لا توجد بيانات مساندة بعد لـ ${esc(t)}.</div>`;const p=d.price||{},id=d.identity||{};const news=(d.news||[]).slice(0,5),fil=(d.filings||[]).slice(0,5);return `<div class="tag-stock-card"><div class="tag-card-head"><div><small>${esc(id.company||'')}</small><h2>${esc(t)}</h2></div><div class="tag-card-price">${p.last!=null?'$'+Number(p.last).toFixed(Number(p.last)<1?4:2):'—'}<small class="${Number(p.changePct)>=0?'pos':'neg'}">${p.changePct!=null?(Number(p.changePct)>=0?'+':'')+Number(p.changePct).toFixed(2)+'%':'—'}</small></div></div><div class="tag-card-meta"><span>Yahoo: ${esc(p.timestampUTC||'—')}</span><span>CIK: ${esc(id.cik||'غير متحقق')}</span><span>${esc(p.exchange||'')}</span></div><h4>آخر الأخبار</h4><div class="tag-card-list">${news.length?news.map(n=>`<a href="${esc(n.url)}" target="_blank" rel="noopener"><b>${esc(n.title)}</b><small>${esc(n.published)} · ${esc(n.source)}</small></a>`).join(''):'<span>لا أخبار مجمعة.</span>'}</div><h4>إفصاحات SEC</h4><div class="tag-card-list">${fil.length?fil.map(f=>`<a href="${esc(f.url)}" target="_blank" rel="noopener"><b>${esc(f.form)} · ${esc(f.filed)}</b><small>${esc(f.description||'فتح الإفصاح')}</small></a>`).join(''):'<span>لا إفصاحات حديثة ضمن الأنواع المراقبة.</span>'}</div><div class="tag-card-note">هذه البيانات للمصالحة والسياق. لا يصبح السعر حقيقة تدريبية نهائية إلا بعد تطابق المصادر وفق Final Snapshot Reconciliation.</div></div>`}
function ensureModal(){if(document.getElementById('tagStockModal'))return;const m=document.createElement('div');m.id='tagStockModal';m.className='tag-modal';m.innerHTML='<div class="tag-modal-box"><button class="tag-modal-close" aria-label="إغلاق">×</button><div id="tagStockCard"></div></div>';document.body.appendChild(m);m.querySelector('.tag-modal-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};}
function openTicker(t){ensureModal();document.getElementById('tagStockCard').innerHTML=card(t);document.getElementById('tagStockModal').classList.add('open')}
document.addEventListener('click',e=>{const tr=e.target.closest('#scannerBody tr');if(!tr)return;const td=tr.querySelector('td.ticker');if(td)openTicker(td.textContent.trim().toUpperCase())});
window.addEventListener('DOMContentLoaded',()=>{ensureModal();loadEnrichment();setInterval(loadEnrichment,15*60*1000)});
})();