(() => {
  let loading=false;
  function nowETParts(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const o={};p.forEach(x=>o[x.type]=x.value);return o}
  function marketWindowOpen(){const p=nowETParts();if(['Sat','Sun'].includes(p.weekday))return false;const hm=(+p.hour)*60+(+p.minute);return hm>=240&&hm<=1200}
  async function loadGitHubFinviz() {
    if(loading)return; loading=true;
    const s=document.getElementById('finvizStatus'),b=document.getElementById('dataBadge');
    if(s){s.className='connector-status';s.textContent='جاري تحميل أحدث بيانات السوق…';}
    try{
      const r=await fetch('./data/finviz.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Data file HTTP '+r.status);
      const payload=await r.json(),finvizRows=Array.isArray(payload.data)?payload.data:(Array.isArray(payload.rows)?payload.rows:[]);if(!finvizRows.length)throw new Error('No Finviz rows found');if(typeof normalizeFinviz!=='function')throw new Error('TAG parser unavailable');
      const updatedMs=Date.parse(payload.updatedAt||payload.snapshotTimestampUTC||''),ageMinutes=Number.isFinite(updatedMs)?Math.max(0,(Date.now()-updatedMs)/60000):null,liveWindow=marketWindowOpen(),staleForLive=liveWindow&&(ageMinutes===null||ageMinutes>15),reconciled=payload.finalSnapshotReconciliation==='RECONCILED'&&(payload.independentSourceCount||0)>=2;
      window.TAGDataIntegrity={updatedAt:payload.updatedAt||null,snapshotTimestampUTC:payload.snapshotTimestampUTC||null,snapshotTimestampET:payload.snapshotTimestampET||null,session:payload.session||null,sessionBucket:payload.sessionBucket||null,snapshotType:payload.snapshotType||null,finalCandidate:Boolean(payload.finalCandidate),finalSnapshotReconciliation:payload.finalSnapshotReconciliation||'UNKNOWN',independentSourceCount:payload.independentSourceCount||0,trainingEligible:Boolean(payload.trainingEligible)&&!staleForLive,cadenceStatus:payload.cadenceStatus||null,bucketContinuityStatus:payload.bucketContinuityStatus||null,trainingBlockReasons:[...(Array.isArray(payload.trainingBlockReasons)?payload.trainingBlockReasons:[]),...(staleForLive?['STALE_SNAPSHOT_DO_NOT_TREAT_AS_LIVE']:[])],ageMinutes,stale:staleForLive,staleForLive,marketWindowOpen:liveWindow,reconciled};
      const normalized=normalizeFinviz(finvizRows),rawByTicker=new Map(finvizRows.map(o=>[String(o.Ticker||o.Symbol||'').toUpperCase(),o]));
      rows=normalized.map(x=>{const o=rawByTicker.get(x.ticker)||{};return {...x,snapshotTimestampUTC:o._snapshotTimestampUTC||payload.snapshotTimestampUTC||payload.updatedAt||null,snapshotTimestampET:o._snapshotTimestampET||payload.snapshotTimestampET||null,session:o._session||payload.session||null,sessionBucket:o._sessionBucket||payload.sessionBucket||null,snapshotType:o._snapshotType||payload.snapshotType||null,finalCandidate:Boolean(o._finalCandidate??payload.finalCandidate),finalReconciled:Boolean(o._finalReconciled),trainingEligible:Boolean(o._trainingEligible??payload.trainingEligible)&&!staleForLive,cadenceStatus:o._cadenceStatus||payload.cadenceStatus||null,bucketContinuityStatus:o._bucketContinuityStatus||payload.bucketContinuityStatus||null,persistenceTrainingEligible:Boolean(o._persistenceTrainingEligible??payload.persistenceTrainingEligible)&&!staleForLive,persistencePoints:Array.isArray(o._persistencePoints)?o._persistencePoints:[],persistenceBuckets:Array.isArray(o._persistenceBuckets)?o._persistenceBuckets:[],gainRetentionPct:o._gainRetentionPct??null,persistenceSlopePctPts:o._persistenceSlopePctPts??null,persistenceTrend:o._persistenceTrend||'INSUFFICIENT_HISTORY',independentSourceCount:o._independentSourceCount??payload.independentSourceCount??0,dataIntegrityState:o._dataIntegrityState||payload.dataIntegrityState||'UNKNOWN',firstObservedTimestampUTC:o._firstObservedTimestampUTC||null,firstObservedTimestampET:o._firstObservedTimestampET||null,firstObservedSession:o._firstObservedSession||null,firstObservedBucket:o._firstObservedBucket||null,firstObservedChange:o._firstObservedChange??null,firstObservedVolume:o._firstObservedVolume??null,firstSessionObservedTimestampUTC:o._firstSessionObservedTimestampUTC||null,firstSessionObservedTimestampET:o._firstSessionObservedTimestampET||null,firstSessionObservedBucket:o._firstSessionObservedBucket||null,firstActionableSignalTimestampET:o._firstActionableSignalTimestampET||null};});
      render();
      if(b){if(staleForLive){b.textContent='● البيانات: متقادمة لحظيًا';b.classList.remove('connected')}else if(!liveWindow){b.textContent='● البيانات: آخر جلسة';b.classList.add('connected')}else{b.textContent=reconciled?'● البيانات: مصالحة':'● البيانات: حديثة';b.classList.add('connected')}}
      if(s){const ageText=ageMinutes===null?'العمر غير معروف':`${ageMinutes.toFixed(0)} د`;if(staleForLive){s.className='connector-status err';s.textContent=`Finviz · ${finvizRows.length} سهم · ${ageText} · متقادم للتداول اللحظي`; }else if(!liveWindow){s.className='connector-status ok';s.textContent=`Finviz · ${finvizRows.length} سهم · آخر لقطة متاحة من ${payload.sessionBucket||payload.session||'الجلسة'} · ${ageText}`;}else{s.className=reconciled?'connector-status ok':'connector-status';s.textContent=`Finviz · ${finvizRows.length} سهم · ${ageText} · ${reconciled?'مصالحة':'قيد المطابقة'} · ${payload.sessionBucket||payload.session||'—'}`;}}
    }catch(e){rows=[];if(typeof render==='function')render();if(b){b.textContent='● خطأ بيانات';b.classList.remove('connected')}if(s){s.className='connector-status err';s.textContent='تعذر تحميل بيانات السوق: '+e.message}}
    finally{loading=false}
  }
  window.loadGitHubFinviz=loadGitHubFinviz;
  window.addEventListener('DOMContentLoaded',()=>{const btn=document.getElementById('connectFinviz');if(btn)btn.onclick=loadGitHubFinviz;const s=document.getElementById('finvizStatus');if(s)s.textContent='جاري تحميل أحدث لقطة…';setTimeout(loadGitHubFinviz,300);setInterval(loadGitHubFinviz,5*60*1000)});
})();