'use strict';
(function(){
 const $=s=>document.querySelector(s), n=v=>Number.isFinite(v)?v:null;
 function stageAr(s){return({DISCOVERY:'اكتشاف',WAKE_UP:'استيقاظ',PRE_IGNITION:'قبل الاشتعال',IGNITION:'اشتعال',LATE:'متأخر',EXHAUSTION:'إنهاك'}[s]||s||'—')}
 function potential(x){let s=n(x.score)??0; const ch=n(x.changePct)??0, rv=n(x.rvol),to=n(x.turnover); if(ch<3)s+=4;if(ch>=3&&ch<10)s+=12;if(ch>=10&&ch<20)s+=7;if(ch>=25)s-=22;if(ch>=50)s-=25;if(rv&&rv>=2)s+=7;if(to&&to>=.25)s+=6;if(x.stage==='IGNITION')s+=7;if(x.stage==='LATE'||x.stage==='EXHAUSTION')s-=18;if(x.sharia==='EXCLUDED')s=-99;return Math.max(0,Math.min(100,s))}
 function eligible(x){return x.valid&&x.sharia!=='EXCLUDED'&&x.stage!=='LATE'&&x.stage!=='EXHAUSTION'&&(n(x.changePct)??99)<25}
 function why(x){const a=[];if(n(x.rvol)>=2)a.push('تسارع حجم');if(n(x.turnover)>=.25)a.push('استحواذ فلوت');if((n(x.changePct)??99)<10)a.push('ما زال مبكرًا');if(x.stage==='IGNITION')a.push('بداية اشتعال');if(n(x.pmChange)>=5)a.push('استمرار ما قبل السوق');return a.slice(0,3).join(' · ')||'تحت المراقبة المبكرة'}
 function card(x,i){const sh=x.sharia==='VERIFIED'?'<span class="tagx10-chip ok">شرعي متحقق</span>':'<span class="tagx10-chip warn">الشرعية غير مكتملة</span>';const dc=x.quality>=70?'<span class="tagx10-chip ok">بيانات جيدة</span>':'<span class="tagx10-chip warn">بيانات محدودة</span>';return `<article class="tagx10-card ${i===0?'best':''}"><div class="tagx10-rank">#${i+1} · ${stageAr(x.stage)}</div><div class="tagx10-ticker">${x.ticker}</div><div class="tagx10-score">${Math.round(potential(x))}/100</div><div class="tagx10-meta">السعر ${n(x.price)!=null?'$'+x.price.toFixed(x.price<1?3:2):'—'} · الحركة ${n(x.changePct)!=null?(x.changePct>=0?'+':'')+x.changePct.toFixed(1)+'%':'—'}<br>إبطال المتابعة: فقدان التسارع/السيولة أو انتقال Late</div><div class="tagx10-why">لماذا الآن: ${why(x)}</div><div class="tagx10-gates">${sh}${dc}<span class="tagx10-chip">Research / Decision Support</span></div></article>`}
 function render(){if(!Array.isArray(window.analyzed)&&typeof analyzed==='undefined')return;const a=(window.analyzed||analyzed||[]).filter(eligible).sort((x,y)=>potential(y)-potential(x)).slice(0,4);let h=$('#tagx10Hero');if(!h){h=document.createElement('section');h.id='tagx10Hero';h.className='tagx10-hero';const anchor=$('.controls')||$('main')?.firstChild;anchor?.parentNode?.insertBefore(h,anchor)}h.innerHTML=`<h2>أفضل فرص TAGX المبكرة اليوم</h2><p>أربع حالات فقط قبل مرحلة المطاردة. الترتيب يدعم القرار ولا يضمن عائدًا؛ غير المتحقق شرعيًا يبقى غير مؤكد.</p><div class="tagx10-kpi"><span>الهدف: <b>اكتشاف مبكر قابل للتنفيذ</b></span><span>المقياس: <b>Top-4 Hit Rate · Lead Time · Early Capture</b></span><span>الحماية: <b>Data Integrity · Shariah · Late Penalty</b></span></div><div class="tagx10-grid">${a.length?a.map(card).join(''):'<div class="tagx10-empty">لا توجد الآن فرص مبكرة مكتملة بما يكفي. لن تملأ TAGX القائمة بأسهم متأخرة أو بيانات وهمية.</div>'}</div>`; const vb=$('#versionBadge');if(vb)vb.textContent='TAGX 1.0';}
 function hook(){const old=window.render;if(typeof old==='function'&&!old.__x10){const f=function(){const r=old.apply(this,arguments);setTimeout(render,0);return r};f.__x10=true;window.render=f}setTimeout(render,1800);setInterval(render,60000)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})();