(()=>{
const $=s=>document.querySelector(s),stateKey='tag8:webapp:filters';
const fmtAge=ts=>{const t=Date.parse(ts||'');if(!Number.isFinite(t))return 'غير معروف';const m=Math.max(0,Math.round((Date.now()-t)/60000));return m<60?`${m} د`:`${Math.floor(m/60)} س ${m%60} د`};
const loadJson=async p=>{const r=await fetch(`${p}?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()};
function mountBar(){const main=$('main.layout');if(!main||$('#appCommandBar'))return;const b=document.createElement('section');b.id='appCommandBar';b.className='app-command-bar';b.innerHTML=`<div class="app-command-left"><button id="appRefresh" class="primary">↻ تحديث</button><button id="installApp" class="app-secondary" hidden>تثبيت</button><span id="appSyncState" class="app-sync">فحص المصادر…</span></div><nav class="dashboard-quicknav"><a href="#opportunities">الفرص</a><a href="#analysis">تحليل سهم</a><a href="#data">البيانات</a></nav>`;main.insertBefore(b,main.firstChild);$('#appRefresh').onclick=async()=>{const x=$('#appRefresh');x.disabled=true;try{if(window.loadGitHubFinviz)await window.loadGitHubFinviz();await health()}finally{x.disabled=false}}}
function mountHealth(){if($('#sourceHealth'))return;const data=$('#data');if(!data)return;const el=document.createElement('section');el.id='sourceHealth';el.className='panel source-health';el.innerHTML=`<div class="section-head"><div><h3>المصادر</h3></div><span id="healthSummary" class="health-summary">…</span></div><div id="healthGrid" class="health-grid"></div>`;data.insertAdjacentElement('afterend',el)}
async function health(){const specs=[['السوق','./data/finviz.json','market'],['Yahoo · SEC · أخبار · Short','./data/enrichment.json','enrichment'],['الإغلاق النهائي','./data/final-reconciliation.json','rec']];const results=await Promise.all(specs.map(async([name,path,type])=>{try{const d=await loadJson(path),ts=d.updatedAt||d.snapshotTimestampUTC||d.generatedAt||d.timestampUTC||null;let status='ok',detail='متاح';if(type==='market'&&window.TAGDataIntegrity?.staleForLive){status='warn';detail='متقادم لحظيًا'}if(type==='enrichment'){const st=d.sourceStatus||{};const failures=Object.values(st).filter(v=>/UNAVAILABLE|ERROR|BLOCKED/i.test(String(v)));if(failures.length){status='warn';detail='بعض المصادر غير متاحة'}else detail='متعدد المصادر'}if(type==='rec'){const r=d.status||d.finalSnapshotReconciliation||d.reconciliationStatus||'';if(!/reconciled/i.test(String(r))){status='warn';detail='غير مكتمل'}else detail='مصالحة'}return{name,status,detail,age:fmtAge(ts)}}catch(e){return{name,status:'err',detail:'غير متاح',age:'—'}}}));const g=$('#healthGrid');if(g)g.innerHTML=results.map(x=>`<article class="source-card ${x.status}"><div><span class="source-dot"></span><strong>${x.name}</strong></div><b>${x.detail}</b><small>${x.age}</small></article>`).join('');const e=results.filter(x=>x.status==='err').length,w=results.filter(x=>x.status==='warn').length,h=$('#healthSummary');if(h){h.textContent=e?'خلل':w?'مراجعة':'سليم';h.className=`health-summary ${e?'err':w?'warn':'ok'}`}const s=$('#appSyncState');if(s)s.textContent='آخر فحص '+new Date().toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}
function filters(){const q=$('#search'),s=$('#stageFilter'),h=$('#shariaFilter');try{const v=JSON.parse(localStorage.getItem(stateKey)||'{}');if(q&&v.q)q.value=v.q;if(s&&v.stage)s.value=v.stage;if(h&&v.sharia)h.value=v.sharia}catch(e){};['input','change'].forEach(ev=>[q,s,h].forEach(el=>el?.addEventListener(ev,()=>localStorage.setItem(stateKey,JSON.stringify({q:q?.value||'',stage:s?.value||'all',sharia:h?.value||'all'})))))}
function keyboard(){document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName)){e.preventDefault();$('#search')?.focus()}if((e.key==='r'||e.key==='R')&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName))$('#appRefresh')?.click();if(e.key==='Escape'){const d=$('#stockDrawer');if(d?.classList.contains('open')){d.classList.remove('open');document.body.classList.remove('drawer-open')}}})}
let install=null;function pwa(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();install=e;const b=$('#installApp');if(b)b.hidden=false});document.addEventListener('click',async e=>{if(e.target?.id==='installApp'&&install){install.prompt();await install.userChoice;install=null;e.target.hidden=true}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
window.addEventListener('DOMContentLoaded',()=>{mountBar();mountHealth();filters();keyboard();pwa();health();setInterval(health,60000)});
})();